### ISSUE TITLE
[BUG] currency symbol not displayed when run from docker container

### ISSUE THREAD

**Issue by florianschroen** [hargata/lubelog#10]
related to https://github.com/hargata/lubelog/issues/1#issuecomment-1879772509 and #3 

I guess it is intended to show the $ Dollar sign.

![grafik](https://github.com/hargata/lubelog/assets/625094/f0f6a41c-1695-4138-a666-931562b6ee05)

The issue is browser independent. (tested FF, Chrome, Chromium)

My guess is that code files are saved in another encoding compared to the runtime inside the container. So maybe we have to set a locale or character set as environment or runtime configuration, or maybe convert file from windows default encoding to utf8 or whatever before checking into git?!

System:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
Codename:       vanessa

$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
``

**Comment by hargata** [comment]
I think it's due to env variable for culture, I updated the Dockerfile and it seemed to work, can you try again?

**Comment by florianschroen** [comment]
confirmed. $ sign is displayed now.

commit 05f8907 fixed it.

**Comment by hargata** [comment]
issue fixed.

**Comment by Battmain** [comment]
> issue fixed.

I've just installed Lubelogger using Docker on my Synology NAS and I'm having this issue as well. I pulled the latest image from the Docker registry but still showing up like the original author's picture.

**Comment by hargata** [comment]
@Battmain read the troubleshooting guide:

https://docs.lubelogger.com/Installation/Troubleshooting

**Comment by Battmain** [comment]
> @Battmain read the troubleshooting guide:
> 
> https://docs.lubelogger.com/Installation/Troubleshooting

Thanks. Got it figured out. I'm fairly new to all this so I'm still learning. I appreciate the help.
