### ISSUE TITLE
[Feature Request] Additional columns to fuel csv export.

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#100]
Is there a way to add the partialfillup missed fillup and filled to full columns on the fuel csv export
![2024-01-14_23-15-22](https://github.com/hargata/lubelog/assets/83042153/e65a2aba-2bc8-4269-8d20-b20835d6e2c0)

**Comment by hargata** [comment]
yes, this is now being worked on and will be released this afternoon.

**Comment by Abateman121** [comment]
Awesome!! looking forward to it!

**Comment by hargata** [comment]
Released.

**Comment by Abateman121** [comment]
looks good.  One question is if we want to reimport those values can we use the True/False in those columns or should we convert to 0 and 1?

**Comment by Abateman121** [comment]
thank you
