### ISSUE TITLE
 a visual nice to have

### ISSUE THREAD

**Issue by lraisbeck** [hargata/lubelog#101]
Just loaded Lubelogger (docker) today onto my Synology NAS and am loving it (but still finding my way around). It woudl be nice to be able to add pictures for maintenance items, as a picture speaks a thousand words. As a for example if a camblet has been changed photos could serve as a digital record. OK it isn't essential, and appreciate there are file size issues,  but it would make lubelogger even more awesome....(which just coincidentally is the name of the garage I use for most of my vehicle sercvicing needs here in Manchester UK) 
![FB_IMG_1690304682965](https://github.com/hargata/lubelog/assets/62262785/5cb69144-9117-4e2c-9274-688dfd9505c5)
![FB_IMG_1690304671612](https://github.com/hargata/lubelog/assets/62262785/185b2af1-be13-40c6-bb35-2a43add0514e)

Shoutout to Awesome   https://www.awesomegti.com/about-us/

**Comment by hargata** [comment]
@lraisbeck Just released a markdown parser for the notes field in the records, it will allow you to embed images in it.
![image](https://github.com/hargata/lubelog/assets/155338622/5115428f-9581-4824-92ff-0b9419d42549)
![image](https://github.com/hargata/lubelog/assets/155338622/ca421ffe-0fbf-4bc4-b59e-40a4179b5dd4)

**Comment by hargata** [comment]
Closing this since you can now embed images in the notes section of records.
