### ISSUE TITLE
[Bug] Incorrect number shown in 'Expenses by Month' graph

### ISSUE THREAD

**Issue by SaturnusDJ** [hargata/lubelog#103]
This seems like a nice program. Well done.

![image](https://github.com/hargata/lubelog/assets/14320018/e3779cbe-f00a-4d9d-a92a-e1e08de4c6a5)
This information in report is correct. It can be seen on the individual tabs as well.

Dash however:
![image](https://github.com/hargata/lubelog/assets/14320018/3dd5042a-c483-42d8-90ee-8dce379dfb04)

2000, 250, 50.
2000 is incorrect. This should be 1000. It is doubled.

The 'Expenses by Type' graph (hover mouse for showing numbers) on the left is correct.
When selecting a year in the time filter ('All Time'), the numbers become correct, also when choosing 'All Time'. The number also becomes correct when checking/unchecking graph filter checkboxes. Thus it seems only the first 'rendering' of the page, including refreshing, results in that wrong number.

**Comment by hargata** [comment]
I have identified the source of this bug, it happens exclusively on the upgrades tab because I accidentally entered the row twice so it always all upgrade sums.
I will have a fix pushed out this afternoon(MST)

**Comment by hargata** [comment]
Fixed and released.

**Comment by SaturnusDJ** [comment]
Excellent, thanks. Will catch it in the next release.
