### ISSUE TITLE
PWA not working

### ISSUE THREAD

**Issue by Peppershade** [hargata/lubelog#104]
I installed the latest version via Docker with Traefik, installation has a valid SSL, but the PWA "Install App" button is not present in chrome on mobile, and chrome on desktop. I tested it with local address and using the SSL/Traefik domain.

**Comment by hargata** [comment]
Can you open up Chrome Console, navigate to "Manifest" tab and check if it's giving you any errors?

**Comment by Peppershade** [comment]
Sorry, it was my bad, Cloudflare Tunnel blocked it
