### ISSUE TITLE
[Visual Issue] File selector overflows its bounding box

### ISSUE THREAD

**Issue by mr-adult** [hargata/lubelog#110]
In the add service record screen, the file selector overflows its bounding box

![Screenshot from 2024-01-16 19-37-45](https://github.com/hargata/lubelog/assets/110244689/ece06218-dde3-4782-b63f-424bb9d262ff)

**Comment by hargata** [comment]
what web browser is this? I cannot re-produce this in Chrome.

**Comment by mr-adult** [comment]
Oh right, that's an important bit of information. I'm on Firefox

**Comment by hargata** [comment]
This is fixed.
