### ISSUE TITLE
[Feature Request] Official docker image tagging

### ISSUE THREAD

**Issue by edlucky1** [hargata/lubelog#117]
Docker is now supported and hargata/lubelogger shows on hub.docker.com, but no images are tagged. Tagging the latest image would be very helpful. This would make image updates much easier for certain applications and also notify users of updates. 

![image](https://github.com/hargata/lubelog/assets/76714493/09f92f68-3866-4790-8a46-f36013bd428f)

**Comment by hargata** [comment]
Done :)
https://hub.docker.com/repository/docker/hargata/lubelogger/general

**Comment by edlucky1** [comment]
Great work, everything works as expected now. Thank you!
