### ISSUE TITLE
[Visual] Mobile View Columns Cutoffs

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#119]
I was testing the app out on my mobile and noticed that the date column is cutoff in all but the fuel tab.  I am on an iphone 13 using the safari browser with the latest ios if that helps.

![IMG_8473](https://github.com/hargata/lubelog/assets/83042153/ec0a9fdd-fd5c-4785-ae2a-a402757e8c22)
![IMG_8474](https://github.com/hargata/lubelog/assets/83042153/f9258370-66fe-4a52-a393-a80b6e398120)
![IMG_8472](https://github.com/hargata/lubelog/assets/83042153/39267383-d8cd-4f0f-ae34-01fba5a33d83)
![IMG_8476](https://github.com/hargata/lubelog/assets/83042153/dc6ce227-1549-4106-a190-229e2d492a9e)
![IMG_8470](https://github.com/hargata/lubelog/assets/83042153/7ff6be54-f315-4741-9c4d-09b458944ebc)

**Comment by hargata** [comment]
See #112

**Comment by Abateman121** [comment]
> See #112

Sorry i thought one was firefox specific.
