### ISSUE TITLE
[Feature Request] Recurring Reminder Request

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#124]
For Reminders, understand they are currently based on Odometer and/or Date.  Is there a way to put in recurring reminders (ie. every 5,000 miles, every 15,000 miles, etc)?  The idea would be that once you complete that reminder interval, system would automatically pull the next interval.  

Thanks!

**Comment by Abateman121** [comment]
+1

**Comment by rtrickett337** [comment]
+1 on adding a 'maintenance interval' :)

**Comment by bigbadbabey** [comment]
+1

**Comment by hargata** [comment]
This has now been added, you can now mark a Reminder as Recurring based on either odometer reading or a future date, and once the Reminder becomes past due it will automatically push itself back by the interval. 
Note that this requires a lot of diligence from the user to take action on the reminder and not let it lapse.

The reminder becomes "Very Urgent" when it has less than 7 days to due date or less than 50 miles to the target odometer reading, so you'd have to intentionally ignore it for it to become past due.

Next I'm going to be working on a button that will allow users to manually push-back/refresh the reminder if they've done the service ahead of schedule.

**Comment by Hawkins1212** [comment]
Thanks for this.  I (and I am sure speak on behalf of others) appreciate you continuing to make improvements to this project.  It's becoming very useful with managing my home fleet (couple cars).  I DIY and I can stay on top of it and this makes it even more helpful!

**Comment by bigbadbabey** [comment]
Thank you for this feature! Could you change it to custom values? The preset you have set do not cover all my needs.

**Comment by bigbadbabey** [comment]
> 
> Next I'm going to be working on a button that will allow users to manually push-back/refresh the reminder if they've done the service ahead of schedule.


One thing that would be great is linking reminders with services so when you do the service it resets the reminder interval.

**Comment by hargata** [comment]
@bigbadbabey that's actually a really good idea. Also, I just inserted some of the more normal intervals, tbh it's pretty easy for me to add a new interval instead of adding a a custom interval field, so just let me know what interval you need.

**Comment by bigbadbabey** [comment]
At minimum what you have, 20000, 30000, 50000, 100000, and 150000, also 2 years and 3 years.

**Comment by Hawkins1212** [comment]
I know i have odd intervals. My first oil change will be 1000 miles then again at 5k and every 5k after that

**Comment by hargata** [comment]
Additional intervals added and released.

**Comment by bigbadbabey** [comment]
Can you also add 15000, it slipped my mind the first time.

**Comment by hargata** [comment]
@bigbadbabey Added :)

**Comment by samsclub91** [comment]
Any chance you could add an option for 40000 and 60000 mile intervals?  Some of my services are at those odd intervals instead of just calling it 50k.

Just found this project and love it!  Great work!

**Comment by hargata** [comment]
@samsclub91 added.

**Comment by hargata** [comment]
There is now an "Other" field for odometer intervals that will allow users to specify a custom recurring interval for odometer field. Closing this ticket since this feature is delivered.
