### ISSUE TITLE
[Feature Request] Parse HTML/Links from Notes

### ISSUE THREAD

**Issue by rtrickett337** [hargata/lubelog#135]
Really liking the Supplies section where I can keep a list of part numbers for supplies like oil filters, wiper blades, etc for each vehicle. I'm dropping in html (primarily amazon links) to where I typically purchase the parts so it's easier to re-order in the future. Would be great if there was a way to just click either in the Supplies listing page a 're-purchase now' button, or click into the supply and have the HTML be parsed and clickable to take me the product on Amazon or anywhere else.

**Comment by hargata** [comment]
I've added markdown parsing for the notes section in records. It's not perfect but it does allow URLs to be parsed. You just have to format them like so, and then click the "Markdown" button next to the Notes label

![image](https://github.com/hargata/lubelog/assets/155338622/153c809b-0975-470a-b2f0-aef79b02e76c)

![image](https://github.com/hargata/lubelog/assets/155338622/582f3940-1dd7-4f87-85a9-db9e3af4fb50)

**Comment by rtrickett337** [comment]
Nice! I’ll test that out. Thanks for adding that so fast!

**Comment by hargata** [comment]
@rtrickett337 no problem! I just tweaked it even further so that it now shows it as an overlay over the original note window instead of a popup.

**Comment by rtrickett337** [comment]
Yeah so that seems to work ok. I was thinking it would save the markdown version, but instead each time the record is opened, the markdown button has to be clicked to re-format the notes and get the URL.

**Comment by hargata** [comment]
@rtrickett337 I've added a user setting to load the notes in markdown if enabled and the notes field isn't blank.

![image](https://github.com/hargata/lubelog/assets/155338622/ad9b9d65-2cc3-448a-baf3-8cad48d59c61)

With this enabled, every time you pull up an existing record, the notes will be displayed in markdown format.

**Comment by rtrickett337** [comment]
That's perfect! And it can easily be turned off with the markdown button on each note if you need to add more to the notes field. I like it!
