### ISSUE TITLE
[Feature Request]: Additional Tabs on Main Screen and Vehicle Properties

### ISSUE THREAD

**Issue by s3rv3rn3rd** [hargata/lubelog#139]
I built a site years ago (significantly simpler, much uglier) and it's worked great but in need of an update for years. Then I saw this and I"m loving it. It's pretty directly comparable to what I built, just not very outdated and poorly written. I do have a few requests though:

1.) On the main page, could we have a few extra tabs. One would be "previously owned" as a means to see the vehicles we've sold and keep that record there but make it not visible on the home screen. Then one for "projects" and "motorcycles" as well. Basically, a property associated with each vehicle as a "Vehicle Category" or something and then have "Active," "Projects," "Motorcycles," and "Previously Owned" as options which are then leveraged via the tabs on the main page. 

2.) On the vehicle property pages. A separate tab to include vehicle specs. The ones I've been using that made sense to me are:
- Engine
- Transmission
- Drivetrain (FWD, AWD, RWD)
- Vehicle Type (Car, Truck, SUV, etc)
- A link to a photo album for the vehicle

**Comment by richard-lee-863** [comment]
Maybe Vehicle COST as well? Would be nice to know. Could even start calculating depreciation from it if people wanted.

**Comment by s3rv3rn3rd** [comment]
> Maybe Vehicle COST as well? Would be nice to know. Could even start calculating depreciation from it if people wanted.

I thought about this too. I included vehicle purchase price as a "transaction" type in the old system I built but I think it would make more sense in the list of vehicle properties and then use that as the base cost of the vehicle.

**Comment by hargata** [comment]
so...on the additional fields, are they purely informational? Because I only selected a handful of fields for vehicles because that makes them easily identified in the garage tiles. If they are purely informational they can probably go into the Notes tab. 

As for keeping track of vehicle depreciation, I believe that is a little bit out of scope for this app. Most users who will use this app don't care for straight line or double declining asset depreciation, and on the flip side, most accounting suites don't care about individual details of service/repair/upgrade records(which is what this app provides) and more about the aggregated sum so that it can be expensed or capitalized.

The vehicle category does sound interesting and I'll look into it.

**Comment by hargata** [comment]
@s3rv3rn3rd What if I add an ability to pin notes so that the most crucial notes always appear on top? The problem with adding additional fields or a tab is that there is always going to be a shortage going from user to user.

**Comment by s3rv3rn3rd** [comment]
Pinned notes could work. Especially if there was a way to add just the pinned notes to that main page. Just a query of the pinned notes. If it's at all possible to maintain a specific order (lil bit of the OCD here) that'd be icing on the cake but I think at minimum the pinned notes could accomplish the base concept here. If we could sneak the pinned notes on the Dash page that would be even better.

**Comment by hargata** [comment]
@s3rv3rn3rd pinned notes are now added, I'm looking into ways to be able to display the pinned notes in the garage tab.

**Comment by hargata** [comment]
@s3rv3rn3rd Pinned notes are now displayed in the garage as a tooltip when hovered over:
![image](https://github.com/hargata/lubelog/assets/155338622/647e4c50-ca10-4152-a44e-ebab27cf9893)
Please pull the latest docker image down and try it out.
Thanks!

**Comment by s3rv3rn3rd** [comment]
The on hover is working. That's working well.

**Comment by hargata** [comment]
@s3rv3rn3rd I didn't think the additional tabs was a good approach as it can potentially result in an infinite amount of tabs since people will want to categorize things differently. BUT, I did add a tags functionality so you can now add tags to vehicles and service/upgrade/repair records and filter them by tags.

**Comment by s3rv3rn3rd** [comment]
Has that change been added? I'm not seeing it when I refreshed. Or I'm missing how that's implemented. Does it allow me to filter on the garage page by vehicle tags? That would do what I was wanting to accomplish with the tabs.

**Comment by hargata** [comment]
@s3rv3rn3rd it has.

You can try it out on https://demo.lubelogger.com

Login with username test and password 1234

**Comment by s3rv3rn3rd** [comment]
I found the tags. This works great. I think this is now able to fully replace my old system. Thank you so much for being so responsive. One other thing I was thinking about. In my life I've owned I think 45 cars. I currently own 5. I like keeping the old records and had planned on entering in all that data here when I've got time. Now that the tags can help just filter out, if there's one last "nice to have" would be to be able to then sort the filtered results. This app has been great!

**Comment by hargata** [comment]
@s3rv3rn3rd Would sorting the vehicle by Year help?

**Comment by s3rv3rn3rd** [comment]
Yeah that'd be perfect. I really can't think of another way I'd even want to, really. Year makes the most sense. I've got old stuff but I don't daily it. So if i'm looking at the list, would just make me be able to be lazier, really, is what I'm getting at. Thank you so much

**Comment by hargata** [comment]
@s3rv3rn3rd just added that. You might have to clear your browser cache so that it'll work, but all you had to do is right click on the Garage tab and it will sort it ascending/descending.
