### ISSUE TITLE
Unreadable month names with LC_ALL = bg_BG.UTF-8 and some suggestions

### ISSUE THREAD

**Issue by zkvvoob** [hargata/lubelog#141]
Hello,

I've just started testing LubeLogger and after successfully importing my data, I noticed that the visualisation on the dashboard shows gibberish where the months names should be:

![SCR-20240122-g0c](https://github.com/hargata/lubelog/assets/7645808/75034f27-73e7-4d62-ac03-aacd51e7b393)

I've installed the app using Docker compose and the .env file contains these settings:
```
LC_ALL=bg_BG.UTF-8
LANG=en_UK.UTF-8
```

Also, the fuel mileage chart contains some bizzare numbers, both on the axis and on the tooltips:

![SCR-20240122-g68](https://github.com/hargata/lubelog/assets/7645808/0712593c-6373-4270-9147-9df7d4b01856)

A couple of tiny suggestions (from a guy, who makes his living in analytics): 

- the legend on the bar chart is misleading: it's green, but the bars have variable colours; either remove the legend altogether, or make the bars a uniform colour;
- the bar colours make no sense: why would the month with the lowest expenses be red? IMO, either change the scale from red (high expenses) to green (low expenses) or opt for a uniform colour.
- typically, when laying out tables, measures (i.e. numbers) and the respective column headers would be aligned to the right, whereas dimensions (categories) - to the left. 

Thank you for all your hard work on LubeLogger!

**Comment by hargata** [comment]
Can you try
LC_ALL=en_BG
LANG=en_BG
?
I think the problem stems from mixing and matching locale and languages. This seems to render currency in European format and BGN as the currency formatter, but it uses English month names.

And thanks for the barchart suggestions, I do agree that the colors are misleading, they actually aren't tied to the values but rather they are hardcoded in a gradient, I will get that fixed.

**Comment by hargata** [comment]
I have also fixed the bar chart, so now it displays highest cost is red and lowest cost is green. It's the opposite for the fuel mileage chart, highest is green and lowest is red:
![image](https://github.com/hargata/lubelog/assets/155338622/e955ec32-4977-4e29-abcc-1be1c4e97ea9)

**Comment by zkvvoob** [comment]
Brilliant! The month names are shown in English now, with `LC_ALL=en_BG`, and the colours of the bar charts make sense.

Thank you, @hargata !
