### ISSUE TITLE
[Feature Request] Automatically add odometer entry when adding fuel entry

### ISSUE THREAD

**Issue by Cheezelz** [hargata/lubelog#145]
Since fuel entries already have the odometer reading on a particular date, it would be great if when adding a fuel entry it would also use the given odometer reading and date as an entry in the standalone odometer tab (or an option to do so).

**Comment by hargata** [comment]
I can work on this, but the caveat is that it will only add an odometer record when adding a new service/repair/upgrade/gas record or when marking a planned task as completed. If you input the wrong odometer reading when adding a record you will have to correct the odometer reading on both tabs.

**Comment by hargata** [comment]
Added and released.
