### ISSUE TITLE
[Feature Request] Set dashboard graph to be spending over time

### ISSUE THREAD

**Issue by InputObject2** [hargata/lubelog#154]
The current dashboard lists months in low to high from what I can tell. It omits months that have not had any records. This feels a little unintuitive, I would have expected the graph to be a history graph in monthly order and show months with nothing as $0.

**Comment by hargata** [comment]
![image](https://github.com/hargata/lubelog/assets/155338622/4ef7c7bc-0257-4fbe-bf2d-91e25c95adda)
Released.
