### ISSUE TITLE
[BUG] Dash - Fuel Mileage by Month incorrect

### ISSUE THREAD

**Issue by Teonyr** [hargata/lubelog#161]
Hey, 
I'm running the latest docker image `Version 1.0.7`.

While visiting the new "Dash" - page, I noticed, that the bottom graph, which shows the "Fuel Mileage by Month" is way off, as you can see in the following image:

![grafik](https://github.com/hargata/lubelog/assets/75175693/6e9c38e2-8550-4bb6-aeb3-09578b266807)

The "Fuel" - page shows those numbers:

![grafik](https://github.com/hargata/lubelog/assets/75175693/78ccafe2-5c7d-417c-bc66-adc3f653610f)
(Note the incorrect "Average Fuel Economy" number, already reported in issue [#160 ](https://github.com/hargata/lubelog/issues/160))

Log seems to be inconspicious:
```
lubelogger  | info: Microsoft.Hosting.Lifetime[14]
lubelogger  |       Now listening on: http://[::]:8080
lubelogger  | info: Microsoft.Hosting.Lifetime[0]
lubelogger  |       Application started. Press Ctrl+C to shut down.
lubelogger  | info: Microsoft.Hosting.Lifetime[0]
lubelogger  |       Hosting environment: Production
lubelogger  | info: Microsoft.Hosting.Lifetime[0]
lubelogger  |       Content root path: /App
```

If you need more info, just ask, I'm happily sharing everything you need to fix it.  :)

Thx & keep up the great work!

**Comment by Teonyr** [comment]
@hargata thx for your reply.
I now have 1.0.8 (earlier today it only pulled 1.0.7) and the issue is fixed.

Thx 😄

**Comment by hargata** [comment]
@Teonyr Thank you!
