### ISSUE TITLE
[Bug] Average Fuel Economy not calculating properly

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#169]
I have noticed that on both my vehicles the average fuel economy is higher than my max fuel economy.   I am on V1.0.8

![image](https://github.com/hargata/lubelog/assets/83042153/5d455d7c-3a06-4b83-a7b1-563566da269b)

![image](https://github.com/hargata/lubelog/assets/83042153/97867736-04e5-4a30-907f-cc93b65d2b7a)

**Comment by hargata** [comment]
@Abateman121 That's interesting. I tweaked the average gas mileage calculation recently but didn't think it was possible for the average to exceed the maximum.

Do you have partial fuel ups in your fuel records?

**Comment by Abateman121** [comment]
I do have partial fill ups in there and some missed fill ups as well.

**Comment by Abateman121** [comment]
also noticed you put a new version out about an hour ago so i am going to update to 1.0.9 to see if it is still an issue.  I am 1.0.8

**Comment by hargata** [comment]
I think I figured out what's wrong, I was omitting the gallons of gas consumed by partial fuel ups, hold on. I'm working on a fix for this right now.

**Comment by Abateman121** [comment]
sounds good i also noticed that after i pulled the latest image it still says v 1.0.8.

**Comment by hargata** [comment]
kk I just pushed a new build out, it should say 1.0.9 now, sorry I'm terrible at updating version numbers lol.

**Comment by Abateman121** [comment]
no worries i just thought i was messing up pulling the latest image

**Comment by hargata** [comment]
@Abateman121 any luck with the fuel mileage?

**Comment by Abateman121** [comment]
Looks good and matches my math
