### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ZoXx** [hargata/lubelog#178]
Hello,
maybe the possibility in the near future to move entries from Service Records to Repairs or the other categories? 
So far all entries have been made in Service Records, with the new functions we would like to move them to the respective categories.

**Comment by hargata** [comment]
What do you mean by all entries being made in Service Records? This seem very much like a user error.

**Comment by ZoXx** [comment]
It was absolutely a user error. All entries were made in the Service Records category. Before these are now all deleted and recreated manually, the question was therefore whether it will be possible in future to move them to other categories via the selection option? :)

**Comment by hargata** [comment]
@ZoXx no worries, I've added this feature.
![image](https://github.com/hargata/lubelog/assets/155338622/1a2bacd3-f744-4a3f-8af2-17c53ddb45ef)

**Comment by ZoXx** [comment]
AWESOME!!!!
THANK YOU SO MUCH! :)
