### ISSUE TITLE
Unhandled exception -  Attempted to divide by zero

### ISSUE THREAD

**Issue by redge76** [hargata/lubelog#201]
Hi,

I tried to import a fuelly export file with the oldest FuelEconomy value equal to 0 and now I have this exception.
```
System.DivideByZeroException: Attempted to divide by zero.
         at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
         at System.Decimal.op_Division(Decimal d1, Decimal d2)
         at CarCareTracker.Helper.GasHelper.GetGasRecordViewModels(List`1 result, Boolean useMPG, Boolean useUKMPG) in /App/Helper/GasHelper.cs:line 85
```

The line 85 is:
`          gasRecordViewModel.MilesPerGallon = useMPG ? (unFactoredMileage + deltaMileage) / (unFactoredConsumption + convertedConsumption) : 100 / ((unFactoredMileage + deltaMileage) / (unFactoredConsumption + convertedConsumption));
`

Can you handle this with a "---" value instead of an exception ? 
I have no doubt that there is a good reason, but why are you storing this "FuelEconomy" value as it can (and should?) be calculated with the odometer and the FuelConsumed values. Performance ?

Thanks for this very nice project.

**Comment by hargata** [comment]
the "---" is handled in the front end. Fuel Economy is not stored, what you're seeing is just the backend calculation and it should be calculated in the backend so that front end is only responsible for what is displayed to the user.

I don't think the FuelEconomy is 0 in your case, since that method only calculates the consumption. Does the first record in your app also have a 0 for consumption?

**Comment by hargata** [comment]
anyways, I've released a workaround for this that will get around the div by zero error. Please pull down the latest docker image.

**Comment by redge76** [comment]
Yes it's fixed.

My import file had a 0 in FuelEconomy for the oldest record imported. (of course the first record is always 0 because it's a difference between the currend and previous record and there is no previous record.... In fact it shoud be a NULL value)

Thanks for the fix.
