### ISSUE TITLE
[Bug] Edit button in top right of vehicle page (yellow button) doesn't do anything

### ISSUE THREAD

**Issue by sprjr** [hargata/lubelog#205]
When selecting a vehicle in your garage, it opens to a vehicle-specific page. In the top right there's a yellow "edit" button that doesn't do anything when pressed, at least not that I can tell. Happy to provide screenshots if needed, or to be corrected if I'm just not seeing anything.

Happening on both of my vehicles.

**Comment by hargata** [comment]
did you just updated it recently? You might have to clear your cache.

**Comment by sprjr** [comment]
Yup. My bad. Thank you!
