### ISSUE TITLE
Broken: Newest update doesn't open input window

### ISSUE THREAD

**Issue by johenkel** [hargata/lubelog#220]
After upgrading to the newest update (1.1.1), when trying to edit something or adding a new record the small input overlay window will not open up.
Tried on Chrome desktop and Chrome on an Android mobile device.

docker instance of lubelogger is on Debian 12

**Comment by hargata** [comment]
clear your browser cache.

**Comment by johenkel** [comment]
Thank you for your fast response.
I deleted the cache & cookies. Still same issue on desktop and mobile chrome. 
Same on new firefox that didn't have any previous data.

To be correct, the add gas record and add reminder window do pop up.
What doesn't work is edit a vehicle, add service record, repairs, upgrades, taxes, and notes.

Error message popping up on the host is below.
Thank you for the docs/wiki link ! I do appreciate your great work on this project !

![Screenshot from 2024-02-02 20-04-16](https://github.com/hargata/lubelog/assets/9903140/5c57c399-bfca-4a27-8bb6-5ca838e69530)

**Comment by hargata** [comment]
do you get any errors when you pull up Chrome console(F12)?

**Comment by johenkel** [comment]
In fact I do.
When refreshing and clicking on editing vehicle:
![Screenshot from 2024-02-02 20-37-24](https://github.com/hargata/lubelog/assets/9903140/9b440a0e-28dc-4ae8-aadc-39835558a57a)

**Comment by hargata** [comment]
can you navigate to <yourlubeloggerdomain.com>/js/shared.js and check if that has the function initTagSelector and decodeHtmlEntities functions in it?

It should look something like this:
https://demo.lubelogger.com/js/shared.js

**Comment by hargata** [comment]
I'm not sure how only that file can potentially get cached, or maybe the docker pull command somehow missed out on that file.

**Comment by johenkel** [comment]
my shared.js looks like this ()not as neatly formatted as the demo):
`function successToast(message){Swal.fire({toast:true,position:"top-end",showConfirmButton:false,timer:3000,title:message,timerProgressBar:true,icon:"success",didOpen:(toast)=>{toast.onmouseenter=Swal.stopTimer;toast.onmouseleave=Swal.resumeTimer;}})}
function errorToast(message){Swal.fire({toast:true,position:"top-end",showConfirmButton:false,timer:3000,title:message,timerProgressBar:true,icon:"error",didOpen:(toast)=>{toast.onmouseenter=Swal.stopTimer;toast.onmouseleave=Swal.resumeTimer;}})}
function viewVehicle(vehicleId){window.location.href=`/Vehicle/Index?vehicleId=${vehicleId}`;}
function saveVehicle(isEdit){var vehicleId=getVehicleModelData().id;var vehicleYear=$("#inputYear").val();var vehicleMake=$("#inputMake").val();var vehicleModel=$("#inputModel").val();var vehicleLicensePlate=$("#inputLicensePlate").val();var vehicleIsElectric=$("#inputIsElectric").is(":checked");var hasError=false;if(vehicleYear.trim()==''||parseInt(vehicleYear)<1900){hasError=true;$("#inputYear").addClass("is-invalid");}else{$("#inputYear").removeClass("is-invalid");}
if(vehicleMake.trim()==''){hasError=true;$("#inputMake").addClass("is-invalid");}else{$("#inputMake").removeClass("is-invalid");}
if(vehicleModel.trim()==''){hasError=true;$("#inputModel").addClass("is-invalid");}else{$("#inputModel").removeClass("is-invalid");}
if(vehicleLicensePlate.trim()==''){hasError=true;$("#inputLicensePlate").addClass("is-invalid");}else{$("#inputLicensePlate").removeClass("is-invalid");}
if(hasError){return;}
$.post('/Vehicle/SaveVehicle',{id:vehicleId,imageLocation:uploadedFile,year:vehicleYear,make:vehicleMake,model:vehicleModel,licensePlate:vehicleLicensePlate,isElectric:vehicleIsElectric},function(data){if(data){if(!isEdit){successToast("Vehicle Added");hideAddVehicleModal();loadGarage();}
else{successToast("Vehicle Updated");hideEditVehicleModal();viewVehicle(vehicleId);}}else{errorToast("An error has occurred, please try again later.");}});}
function uploadFileAsync(event){let formData=new FormData();formData.append("file",event.files[0]);sloader.show();$.ajax({url:"/Files/HandleFileUpload",data:formData,cache:false,processData:false,contentType:false,type:'POST',success:function(response){sloader.hide();if(response.trim()!=''){uploadedFile=response;}}});}
function isValidMoney(input){const euRegex=/^\$?(?=\(.*\)|[^()]*$)\(?\d{1,3}(\.?\d{3})?(,\d{1,3}?)?\)?$/;const usRegex=/^\$?(?=\(.*\)|[^()]*$)\(?\d{1,3}(,?\d{3})?(\.\d{1,3}?)?\)?$/;return(euRegex.test(input)||usRegex.test(input));}
function initDatePicker(input,futureOnly){if(futureOnly){input.datepicker({startDate:"+0d",format:getShortDatePattern().pattern,autoclose:true});}else{input.datepicker({endDate:"+0d",format:getShortDatePattern().pattern,autoclose:true});}}
function showMobileNav(){$(".lubelogger-mobile-nav").addClass("lubelogger-mobile-nav-show");}
function hideMobileNav(){$(".lubelogger-mobile-nav").removeClass("lubelogger-mobile-nav-show");}
function bindWindowResize(){$(window).resize(function(){hideMobileNav();});}`

**Comment by hargata** [comment]
@johenkel you most definitely have an outdated version of the shared.js file, but I'm not sure how or why. does it work if you go to the your lubelogger site in incognito mode?

**Comment by johenkel** [comment]
Wait. I did pull it up in Incognito mode. 
Then refreshing it once again and it pulled up. 

So it still must have been a cache issue as you rightly pointed out before. 
No idea how that took until now to actually work.

Again, thanks BUNCH for your immediate help !!
