### ISSUE TITLE
[Feature Request] use number format for more input fields

### ISSUE THREAD

**Issue by johenkel** [hargata/lubelog#223]
When adding a new gas record on mobile, the odometer input format is for numbers, so when the onscreen keyboard pops up one can enter numbers easily.
![Screenshot from 2024-02-03 10-15-37](https://github.com/hargata/lubelog/assets/9903140/b829d553-d846-4c83-9c65-9a20da933a73)

However when one enters the fuel consumption and cost, it shows up as text input, ergo one gets a regular keyboard to enter numbers.
![Screenshot from 2024-02-03 10-16-16](https://github.com/hargata/lubelog/assets/9903140/06a1fd3f-9b1f-441e-8866-842440ca8e22)

Could the fuel consumption and cost fields be formatted to be number inputs as well ?
I know it only saves one step per field, but it would streamline entering a gas record quickly on the road.

**Comment by hargata** [comment]
@johenkel Can't because then European locales with "," as a decimal separator won't be able to enter their fuel consumption. It used to be a number only field just like odometer up until #46

**Comment by johenkel** [comment]
Ha !
those Europeans .... smh.
Thank you for the outstandingly fast reply and explanation !
