### ISSUE TITLE
Other image tags then latest?

### ISSUE THREAD

**Issue by tdkl** [hargata/lubelog#226]
Using latest is a bad idea itself, but it would be great if other tags would be available to pull, so users can control what image they run.

**Comment by jdh313** [comment]
Agreed. You're already creating releases, which is awesome and much appreciated, and it should be possible to create tagged images in the same workflow.

**Comment by hargata** [comment]
I have no clue how to add the latest github release tag onto the github actions workflow lol. If anyone got this figured out feel free to contribute.

**Comment by hargata** [comment]
@jdh313 You can just fork and create a pull request, see #216 

As for versioning, I wish I could say it was semver but I got lazy and just incremented the patch number by 1 until it reaches 9 then I increment the minor number. Regarding when I increment those numbers, well, at the beginning of each week I plan out what feature request / enhancements I should add to the app, then once those features are delivered I'll increment it.

**Comment by jdh313** [comment]
Just created a PR to fix this issue. I've used a semantic versioning action in the past which auto-generated it based on the commit messages. I'd be happy to create a separate PR in the future if you're interested, but it probably wouldn't be today.

**Comment by hargata** [comment]
@jdh313 Thank you! I don't think we'll need to auto-generate semantic versioning, your contribution works great!

**Comment by jdh313** [comment]
@hargata You bet! Thank you for all you've done here! If you aren't doing semver, maybe try to differentiate tagging a bit from it (such as x.y only, date based, etc.)?

**Comment by hargata** [comment]
@jdh313 the goal is to do semver once the project is a little more stable and is feature-rich enough/when I can manage the backlog a little better. Otherwise with my release schedule the minor version is going to increment extremely quickly.

**Comment by jdh313** [comment]
That's totally fair. Thank you for all your hard work!
