### ISSUE TITLE
Feature Request Edit Uploaded Documents Name

### ISSUE THREAD

**Issue by AmIBeingObtuse** [hargata/lubelog#23]
Allow us to edit the document name after being uploaded.

Image: https://imgur.com/a/Qxzwzfe

Thanks for this app its great!

**Comment by hargata** [comment]
great idea, this will be next on the to-do

**Comment by hargata** [comment]
@AmIBeingObtuse can you pull down the latest docker image and test
![image](https://github.com/hargata/lubelog/assets/155338622/a499bed7-c4a0-4d95-87d8-d408e2f8026c)

**Comment by AmIBeingObtuse** [comment]
Thank you very much this is amazing! and so quick to implement! Thanks! Works perfectly so far.

**Comment by hargata** [comment]
You're welcome! I'll close the issue.
