### ISSUE TITLE
Did the Import CSV feature disappear?

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#230]
the dropdown next to "Add Record" seems to have disappeared and I have no way to import logs via CSV for my vehicles.

![image](https://github.com/hargata/lubelog/assets/10135929/4631ad65-c7e7-4b97-9a78-3102a16ccc8f)

**Comment by hargata** [comment]
Do you mean the import via CSV feature?

**Comment by alternativesurfer** [comment]
Yes

**Comment by hargata** [comment]
It's still there you just have to enable it in the settings?

**Comment by alternativesurfer** [comment]
Oh JFC I am blind, sorry!

**Comment by jacobburrell** [comment]
I don't see this feature either.

Searching the [docs](https://docs.lubelogger.com/Getting%20Started) only seems to reference setting   "EnableCsvImports": true or enabling via the GUI

<img width="238" alt="image" src="https://github.com/user-attachments/assets/ed34596f-d8c6-47e4-8b93-10a1b1ad23c4">

I don't see where I can actually use this feature from the GUI.

Probably best to add this to documentation.

**Comment by hargata** [comment]
@jacobburrell 
https://docs.lubelogger.com/Records/Service%20Records#searching-records
