### ISSUE TITLE
the cii variable is not set

### ISSUE THREAD

**Issue by schweizerhaus** [hargata/lubelog#231]
Hey all, I'm getting an error message that says "the cii variable is not set, defaulting to a blank string." I'm not sure what I did or didn't do to cause this. Can you help me troubleshoot? I don't see anything named CII referenced anywhere in my /env or docker-compose.yml file so I'm not sure where else to look. Thanks!

**Comment by hargata** [comment]
You might have to re-create your .env file.

**Comment by schweizerhaus** [comment]
I deleted everything in .env and pasted in the standard fields without populating it and I no longer get the error. Thanks for the quick reply, I'll figure out where I made the formatting error at some point tomorrow when I try and set up notifications again.
