### ISSUE TITLE
Support for UTF-8 Latin-1 | SO/IEC 8859-1

### ISSUE THREAD

**Issue by joaoferreira-git** [hargata/lubelog#232]
As the title says, I'm asking for support for Latin languages because, so far, it doesn't support the Latin characters that are used in Portuguese.
![image](https://github.com/hargata/lubelog/assets/19786598/a3f217d3-b49c-4356-8cea-65da20c6a61f)

At the top it should be showing: **Lembretes por Urgência**
The other one is: **Não Urgente**

**Comment by hargata** [comment]
Thanks for bringing this to my attention, is this only an issue in the reminder chart or is it happening elsewhere?

**Comment by joaoferreira-git** [comment]
I only noticed on the reminder chart, its seems to be working everywhere except for the reminder 
Currently trying to figure out how to make a pull request for the translation.
![image](https://github.com/hargata/lubelog/assets/19786598/81ead1ff-b6df-4bde-ad97-155570b322a2)
![image](https://github.com/hargata/lubelog/assets/19786598/70ab5fb3-2705-482a-b6bd-fea31c67a6b5)

**Comment by hargata** [comment]
I just released 1.1.3, this bug should be fixed, there are also more strings to translate with it.

**Comment by joaoferreira-git** [comment]
Just finished translating the new strings and confirmed the reminder dashboard is fixed.
I asked some friends to review the translation even though i was talking to them in VC on discord while translating it and they found 2 strings that could be improved.
![image](https://github.com/hargata/lubelog/assets/19786598/603f5a33-5a6e-47d9-ac3a-e47ec744182f)
