### ISSUE TITLE
[Feature Request] Insurance Costs

### ISSUE THREAD

**Issue by Geezuhs** [hargata/lubelog#236]
It would be great if the program could allow users to input their monthly insurance expenses. As a pay-per-mile user, my monthly insurance cost varies depending on the mileage driven. It would be helpful to see the monthly cost listed and graphed along with other expenses tracked by the program to understand better the total cost incurred throughout the year. This is not directly related to service or maintenance but would add an additional feature.

**Comment by hargata** [comment]
Can this be inputted in the Taxes tab? 
https://docs.lubelogger.com/Records/Taxes

**Comment by Geezuhs** [comment]
I did not think of utilizing that feature; that would work for the miscellaneous costs.

Thank you.
