### ISSUE TITLE
[Feature Request] Mileage difference between previous odometer value

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog#238]
Hello,

What would be useful is to see the difference in mileage between each fuel mileage records. Like I had 241339 km on my previous odometer and on last refuiling I my odometer was 242313. So difference is 242313 - 241339 = 974 km. Like this for example:

![image](https://github.com/hargata/lubelog/assets/13857043/b7777aac-428a-4e4f-bfe2-66c4feee23b2)

Thank you.

**Comment by hargata** [comment]
Added in 1.1.4
![image](https://github.com/hargata/lubelog/assets/155338622/8aea9dc8-93d7-4258-8f01-3c165ecea1e3)

**Comment by thehijacker** [comment]
Thank you! Perfect.
