### ISSUE TITLE
Coordinate Translation Efforts

### ISSUE THREAD

**Issue by hargata** [hargata/lubelog#241]
To coordinate translation efforts, I've made this thread in the discussion section:

The thread is where we can get translations reviewed / updated.

https://github.com/hargata/lubelog/discussions/240

**Comment by dabenzel** [comment]
An Addition to translations: Please make translation-files updatable.
Situation; `de.json` exists.
Current behaviour:  If I want to upload a newer `de.json`, I get an empty error-message. Then I delete `de.json`, after this, I have a language with a uid in the select-box which holds the updated strings. 
If I then upload a new `de.json`, I have the old strings again. So deletion doesn't really delete the file, I guess?

**Comment by hargata** [comment]
@dabenzel the language files are cached in memory to save IO, if you have deleted and re-uploaded a translation file, you must restart your container to view the changes.

**Comment by lcabrera** [comment]
Are you already working on the Spanish translation?

**Comment by hargata** [comment]
@lcabrera please create a pull request here: https://github.com/hargata/lubelog_translations/pulls

**Comment by lcabrera** [comment]
Done.
