### ISSUE TITLE
Docs site as a static site

### ISSUE THREAD

**Issue by userbradley** [hargata/lubelog#245]
Howdy, I'm back again 

I was wondering if you'd be opposed to the lubelogger wiki being an mkdocs site?

I've been running an mkdocs site for a while (documentation.breadnet.co.uk) and I'm more than happy to convert the otter wiki site to an mkdocs site, that can be deployed via github actions to either github pages, or (what I personally do) fly.io (https://documentation.breadnet.co.uk/cloud/fly/mkdocs-on-fly/)

Let me know! I'm hopeless at coding, but documentation is where I shine so would be happy to contribute

**Comment by hargata** [comment]
Does MKDocs support uploading images by copying and pasting the image onto the markdown editor or do I have to upload them elsewhere and link it there?

**Comment by userbradley** [comment]
It _does_ technically if your IDE supports pasting images in markdown and auto-referencing it. IntelliJ does

Its best practice to have an assets folder, but it can be done your way 100%

**Comment by hargata** [comment]
A flatfile repository for LubeLogger's wiki can be found here: https://github.com/hargata/lubelog_docs
