### ISSUE TITLE
Container runs as root

### ISSUE THREAD

**Issue by Vyerni** [hargata/lubelog#25]
The docker container runs as root, and therefore all files owned by root. 

It would be beneficial if the container could be edited to work with the `user: ` command in the docker compose. 

I tried it, and it caused the container webpage to not show

**Comment by Vyerni** [comment]
So I'm not sure if I did something different last night, or something has changed since. 

But I can now access the webpage, with a container running as not root. However, when I went to add an image to a vehicle, it just timed out

**Comment by hargata** [comment]
@Vyerni that's interesting, does adding files work(besides image) or do all uploads time out?

**Comment by Vyerni** [comment]
> @Vyerni that's interesting, does adding files work(besides image) or do all uploads time out? I believe it's mainly a permission issue. Make sure the non-root user has read/write/delete permissions on the folders of the mounted volume.

I never tried any further. But 100% my user has permission. All folders were created by my user

**Comment by Vyerni** [comment]
@hargata 

So, finally had a little time to play around with it. Recreated the container using `user: 1000:1000`, and same issue as last time. 

I reviewed the container logs, and saw a line saying `System.UnauthorizedAccessException: Access to the path '/App/wwwroot/temp/' is denied.`. Had a double check to make sure I didn't miss it, and couldn't see it. 

But once I added the following line to my volumes for the container, and recreated, it worked a treat: 
`- ./lubelogger/temp:/App/wwwroot/temp/`

**Comment by hargata** [comment]
@Vyerni thank you for helping me diagnose this! I originally didn't include the temp folder as a volume because I didn't want the data in it to persist(it's where uploaded files initially go before they get processed/moved to more permanent folders), but I didn't know that it would cause issues.
For now I think I will just add the temp folder to the docker-compose and add a note in there to tell people to clear out that folder from time to time.

**Comment by hargata** [comment]
temp volume has been added to docker compose. I'm leaving a note here so that users know to clean out the temp folder from time to time.

**Comment by florianschroen** [comment]
@hargata

You can add a `RUN mkdir -p -m 777 /App/wwwroot/temp` in Dockerfile after copying your code into the image.

This way the temp folder is existing in the image and every user has write access to the folder. (no matter which user id is used)

This will solve the problem in a flexible way where the user can decide if hi wants to add a volume for temp or not and under which uid he wants to run the container. 

Just leave the volume line commented out in the compose file. 😊
