### ISSUE TITLE
Feature Request - When Adding a Service Record, pull the Services from the Reminders

### ISSUE THREAD

**Issue by robant85** [hargata/lubelog#252]
In Simply Auto (the app I am migrating from), when adding a service record, you have the ability to select from services that have already been completed on the vehicle. This way, when you select the service from the service record menu, the reminder gets updated automatically. And it avoids the possibility of mis-typing the service, or creating "duplicate" services.

**Comment by iotech-fvtt** [comment]
Could also find the service in the Planning Section and advance it to In Progress or Done depending on state of the Service task.

**Comment by hargata** [comment]
@robant85 @iotech-fvtt You can now create Plan Records from Recurring Reminders as of 1.2.1: https://youtu.be/J2ymGhFuTTw?si=z7q2sFx8vK0_6qtc&t=278

Once the plan has been marked as done it will automatically push the recurring reminder back by the interval.

Don't forget to clear your browser cache after updating otherwise things will appear broken on the user's end.

**Comment by robant85** [comment]
Thanks to @iotech-fvtt for hopping on with an extra suggestion, but that's not exactly what I was looking for. I actually don't use the "Planning" section like that. I only go based off of the reminders section of scheduled maintenance from my car's service manual. 

I'm never going to "plan ahead" for the service that I know needs to occur at a certain mileage. 

Now, while the feature you have added is excellent, it doesn't necessarily solve the issue I'm looking to solve. I need a "bank" of services that I would do on all of the cars in my garage. It's very similar to the way you have supplies implemented, except for I need the services selectable in the "Add a Service Record" page, and when it's saved there it pushes the reminder back.

Is this possible/feasible?

**Comment by iotech-fvtt** [comment]
I second this, that would be VERY useful!

**Comment by robant85** [comment]
Kinda. They don't even have to be available for all vehicles. Each vehicle can have it's own menu of services linked to reminders. 

The planner feature could actually work, and it's really close, it's just an extra step to create the template, activate the plan, move it to done, then input the ODO.

What I'm wishing for is creating a service record, and in the service record, I pick from a recurring reminder, then when that service record is saved, it also pushes the reminder back.

Does that make sense @hargata ?

**Comment by hargata** [comment]
@robant85 oh yes, that makes a lot more sense, I'm super busy this week but I will try to work on that and get it released sometime next week.

**Comment by robant85** [comment]
Hey! You are awesome. There's no rush. This product is super awesome as is, and I look forward to any features you add as long as you have time for them! Thank you so much!

**Comment by hargata** [comment]
@robant85 hey I just added this feature, watch this walkthrough and let me know if this is more or less what you're asking for:

https://youtu.be/m_FAbZODdyY?si=a_TK1LpIVSPU_gck&t=72

**Comment by robant85** [comment]
Absolutely fantastic! That's exactly what I was looking for! This app fully replaces my old one now. I'm all in @hargata!! Keep up the awesome work!

**Comment by robant85** [comment]
I'm so sorry. One more request. Can you select multiple reminders to add into a record? I never go to get my car fixed and get just one service, the stealership is all about the up-sell!

**Comment by hargata** [comment]
@robant85 If you always get the same services done at the same time(e.g.: oil, windshield wipers, etc) with every visit to the dealership, wouldn't it make more sense to create a single reminder item called "Dealership Services" and just list out the services in the Notes section? Multiple reminders only make sense if you stick to the interval of those services instead of getting them done at the same time regardless of their intervals

**Comment by robant85** [comment]
Well, no because I may not get the same services done every time.. It may be a reminder suggestion, but I can't afford it, or some other factor. I use the intervals more than dealers suggestions. But if I go for an Oil Change and my coolant service isn't due, I wouldn't do both. But if I get an Oil Change and they think my coolant looks dark, I might go ahead and do it. 

The point is that I have services that I know need to be done on an interval that I need to track, and if they suggest something I might not need I can look at my app and say, no thanks I just had that done 2 months ago. 

I also want to be able to select the services I have done each time I visit the shop and they may not be the same each time, therefore I can't always plan for them.

**Comment by hargata** [comment]
@robant85 ahh okay, that makes a lot of sense, I'll look into it

**Comment by robant85** [comment]
Okay, I can do that @hargata  .. thanks for the suggestion. I'll just have multiple service records for each service that has a reminder until the ability to select multiple reminders within the service record becomes deployed. Thank you so much for all of your hard work. This product is really becoming awesome.

**Comment by hargata** [comment]
@robant85 Just wanted to provide an update, this is now being worked on and will be shipped in the next release, but the release date is still tbd as we're still trying to determine the scope/other features to ship for the next release.

![multi reminder](https://github.com/hargata/lubelog/assets/155338622/0d68fefc-2f5b-4c2e-9ec0-d8fde43ecef4)

**Comment by hargata** [comment]
@robant85 released in 1.2.9

**Comment by robant85** [comment]
Thank you, thank you, thank you. This closes the gap for me. That's exactly what was needed for me. You have such an awesome product here and I look forward to the continued growth and development!
