### ISSUE TITLE
[Feature Request] 🇪🇺 Euro currency  [€]  🇪🇺 

### ISSUE THREAD

**Issue by sastromo** [hargata/lubelog#255]
€ € € € € € € € € € € € € € €

Thanks from all the europeans within the ⚡ eurozone ⚡

**Comment by hargata** [comment]
euro currency is supported by LubeLogger, if you're running this in Docker you just have to set the LC_ALL and LANG environment variables and you will start seeing euro currencies and dates :)
more info see here:
https://docs.lubelogger.com/Getting%20Started
