### ISSUE TITLE
Make the exportable report follow translations

### ISSUE THREAD

**Issue by matthewstocker** [hargata/lubelog#257]
Hello there,

Would it be possible to get the exportable PDF that gets produced by LubeLogger to follow translations more accurately?

I have currently got my instance set to en_GB, and most if not all of the $ have been correctly turned into £.
However, when I go to export the PDF, everything is still listed in $.

I know its something small and petty, but I thought I should still bring it up.

Thank you, and thanks for bringing something so cool out!

**Comment by hargata** [comment]
are you sure you have the locale and lang set up correctly? I just switched over to en_GB and my currency formats show up as pounds, note if you're running in Docker you have to have both LC_ALL and LANG environment variables set to the same thing.
![image](https://github.com/hargata/lubelog/assets/155338622/448d57a6-42cf-4943-aaeb-0e80daeb45ac)
