### ISSUE TITLE
Same text other meaning problem in translation

### ISSUE THREAD

**Issue by radim-ek** [hargata/lubelog#259]
`                            <button onclick="makeBackup()" class="btn btn-primary btn-md">@translator.Translate(userLanguage, "Make")</button>`
change to 
`                            <button onclick="makeBackup()" class="btn btn-primary btn-md">@translator.Translate(userLanguage, "Make Backup")</button>`
because same "text" but other meaning.
https://github.com/hargata/lubelog/blob/dd9f754e85e070bfc1de75301ccdf55870cc4f81/Views/Home/_Settings.cshtml#L160C1-L160C143

**Comment by hargata** [comment]
will be fixed on tomorrow's release, the "Make" Backup button will be renamed to "Create"

**Comment by hargata** [comment]
Fix is released today.
