### ISSUE TITLE
Add Linux/Arm64/v8 support

### ISSUE THREAD

**Issue by nicolopozzato** [hargata/lubelog#26]
Hi, I would like to test and try this new veichle management container, but I wuold like to use that in an ARM cpu.

It's possible to have an arm64/v8 support for the docker container?

(I tested with a build and I got it working so it's possible to run lubelog on arm)

**Comment by hargata** [comment]
Is this still a request or can this be closed?

**Comment by florianschroen** [comment]
this would be relevant to the workflow for building and pushing the image to the container registry. (ghcr.io is the current plan).

For arm build we need to build on a arm machine or cross-compile.

Maybe someone can point us to a github project which already builds arm images via github workflow, so we can have a look at how to do it.

**Comment by nicolopozzato** [comment]
> Is this still a request or can this be closed?
For this time I can manually build the image myself in my arm machine but I think that could be an interesting thing to have a ready to deploy image.

**Comment by florianschroen** [comment]
https://docs.docker.com/build/building/multi-platform/ 

And

https://docs.docker.com/engine/reference/commandline/buildx_create/

There are some general build infos. Search for `--platform`

I guess for github builds there are some extra strategies.

**Comment by florianschroen** [comment]
@nicolopozzato you are absolutely right. Pulling prebuild images from a registry is the easy and preferred way for users. User builds should be needed only for customization. 

At the moment, @hargata is trying to get the workflow running which should build and push the image to the registry.

When done we can automatically get new images at the time a new commit, pull request or version tag getting applied to the main branch.

So please give him a little bit of time to figure this out.

Or if you are fluent with gitlab workflows for docker cross platform builds, you are welcome to contribute with a PR. 😊

**Comment by hargata** [comment]
hi all, I tried to build the image for linux/arm64 but it failed:
https://github.com/hargata/lubelog/actions/runs/7452437431/job/20275699133

The workflow for linux/amd64 ran fine but failed for arm64, any help? Died on the MSBuild process.

**Comment by hargata** [comment]
I found this: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md
I don't think we can release a Docker Image via GitHub Actions as it requires QEMU to emulate the arm64 environment and .NET 8 does not support QEMU.
I'm sorry, I'm open to any other suggestions on how to get an image built any other way besides Docker BuildX.

**Comment by nicolopozzato** [comment]
> Or if you are fluent with gitlab workflows for docker cross platform builds, you are welcome to contribute with a PR. 😊

Sorry but I'm relatively new to the docker/github world. I'm a developer on other tecnologies.
For arm I'm using the free tier on oracle and the building work fine, so it's possible to run the project on that, I can't help in the github action and similar

**Comment by mmBesar** [comment]
An Arm64 support would be nice. Thanks.
