### ISSUE TITLE
v1.1.5 Connection timeout

### ISSUE THREAD

**Issue by iotech-fvtt** [hargata/lubelog#268]
With v1.1.5, trying to connect from any device other than localhost:5000 results in a timeout. Firewall is verified open on port 5000 for TCP and UDP

For example, even on the host machine, connecting to 10.0.0.4:5000 (IP of the host) fails with timeout. Trying to connect from other machines on the LAN times out.

**Comment by hargata** [comment]
Is this the Windows standalone copy instead of Docker?

**Comment by iotech-fvtt** [comment]
Correct, standalone

**Comment by hargata** [comment]
Ah, it's because Kestrel by default only allows localhost to access localhost, why Microsoft built it this way, I'm not sure, but all you have to do is open up appsettings.json and add the following section:
"Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://10.10.0.4:5000"
      },
      "Https": {
        "Url": "https://10.10.0.4:5011"
      },
}

**Comment by hargata** [comment]
I have a video on this from a while back, it's a bit older but you can use it as a reference
https://youtu.be/3u1WMfnta04?si=dguKeoWP0tPJtRV7&t=227
The video also covers setting up https which has mostly been superseded by https://docs.lubelogger.com/HTTPS

**Comment by iotech-fvtt** [comment]
Got it, even working with my domain name now, Thanks!
