### ISSUE TITLE
Feature Request: Supplies Location

### ISSUE THREAD

**Issue by iotech-fvtt** [hargata/lubelog#270]
We have supplies in two different shops, and multiple racks, bins, etc in those shops. Request new fields in the Supplies and Shop Supplies objects for Warehouse/Area/Rack/Shelf/Bin please

**Comment by iotech-fvtt** [comment]
See #271 and #272, i98f you add Tools and separate Parts from Supplies, it would be handy to have location fields for those objects too.

**Comment by hargata** [comment]
@iotech-fvtt Added the ability for users to add as much additional fields as they want as of 1.1.6

Watch: https://www.youtube.com/watch?v=FIlo9Q6eQBo

**Comment by hargata** [comment]
@iotech-fvtt hey just wondering if I can close this ticket since you can now add those custom fields on to the supply record?

**Comment by iotech-fvtt** [comment]
Oh, yes, certainly! Thank you!
