### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by izikavi** [hargata/lubelog#279]
HI,
I uploaded a translation file and the site is still in English.
I checked and the json file was uploaded to the right directory (/App/wwwroot/translations), and I also validate the json file in 2 sites.
![image](https://github.com/hargata/lubelog/assets/7503846/c178cf31-90a9-4bfe-8ce1-40a38448b1d1)
I also tried to restart the docker.
I'm using docker-compse on Debian server.

**Comment by hargata** [comment]
Can you upload your translation file here?

**Comment by izikavi** [comment]
[he_IL.json](https://github.com/hargata/lubelog/files/14269414/he_IL.json)
Here is the file.
I also tried changing to one line (like the source file) and it still didn't work.

**Comment by hargata** [comment]
Did you select the language in the dropdown?

![image](https://github.com/hargata/lubelog/assets/155338622/6f079af4-1628-490d-9437-600ad357f02d)

![image](https://github.com/hargata/lubelog/assets/155338622/a648203a-6629-4e9e-8808-47b0622a4bc1)

It works fine on my side, some strings are not translated, but the language loaded

![image](https://github.com/hargata/lubelog/assets/155338622/201802cd-4c6e-42a6-a70a-897e999deaf5)

**Comment by izikavi** [comment]
It's seem that I use \ (back slash) in the transition before " (apostrophes) in the middle of value.
Thanks for your help 😃

**Comment by izikavi** [comment]
I close this issue.
