### ISSUE TITLE
Error in calendar for UK

### ISSUE THREAD

**Issue by marc115uk** [hargata/lubelog#288]
Have a reminder set for 3rd of November (3/11/24 uk date format) however it is showing 11th March in calendar. Have LC_ALL set to gb in environment variables.

![image](https://github.com/hargata/lubelog/assets/57296217/8930c385-e23d-4d73-a15e-5fae6830549b)
![image](https://github.com/hargata/lubelog/assets/57296217/0326518c-3cd8-47f0-b9c0-76fd7841458f)

**Comment by hargata** [comment]
@marc115uk hey I just pushed a fix out for this, can you pull down the latest docker image tagged 1.1.7 and try it out? I tested it on my machine with UK locale and it worked.

**Comment by marc115uk** [comment]
> @marc115uk hey I just pushed a fix out for this, can you pull down the latest docker image tagged 1.1.7 and try it out? I tested it on my machine with UK locale and it worked.

Hey, yep seems to be now thank you 😃

**Comment by hargata** [comment]
Sweet, thank you!
