### ISSUE TITLE
[Bug] [Users Issue] Cannot Add Records

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#292]
So I just upgrade to 1.1.8 and migrated to postgres.  The migration was super easy.  Thank you for the youtube and writeup.  Now i am having an issue where i cannot add a new record.  I can create a new vehicle but cannot add fuel, service, odometer, etc records.  I also cannot edit existing records or do a file import/export to add records.

**Comment by hargata** [comment]
Does it work in incognito mode?

**Comment by Abateman121** [comment]
I will check when I get home-Adam BatemanOn Feb 14, 2024, at 12:34 PM, Hargata Softworks ***@***.***> wrote:﻿
Does it work in incognito mode?

**Comment by hargata** [comment]
@Abateman121 You might just have to clear the cache on your device.

**Comment by Abateman121** [comment]
yea... i am a dumbass and forgot to do that even though your instructions on the youtube video mentioned it. So thank you for the great app!
