### ISSUE TITLE
Feature Request: Ability to select date format

### ISSUE THREAD

**Issue by myharries** [hargata/lubelog#293]
Have the ability to change the date format.
In the USA 10th March = 03/10/2024 (mm/dd/yyyy)
In Australia it equals 10/03/2024 (dd/mm/yyyy).

Perhaps this could be selected based on which Language file you select

Cheers
David

**Comment by hargata** [comment]
The date formats changes based on your environment variables, if you have it configured to en_AU it will show up correctly.

**Comment by myharries** [comment]
Ahh, my bad! Was looking at the language settings on the settings page. Forgot all about the docker settings
Sorry about that!
David
