### ISSUE TITLE
Issue/ Feature Request: There is no way to see what supplies have been used after the page is updated

### ISSUE THREAD

**Issue by myharries** [hargata/lubelog#294]
As part of the Service/ Repair & Upgrade screens, after you have selected the supplies, and saved the record, you can no longer see what supplies were allocated.
Also, after adding a record, and you have forgotten to add a supply, there is no way to select any more

cheers
David

**Comment by hargata** [comment]
@myharries Hey this is now available in 1.2.1
Watch this video to learn how it works: https://youtu.be/J2ymGhFuTTw?si=08fOCYPtY3W7MwQd&t=106
