### ISSUE TITLE
Feature Proposal: Support for Displaying Dates in DD/MM/YYYY Format

### ISSUE THREAD

**Issue by jackthomasanderson** [hargata/lubelog#298]
I'm reaching out to suggest a feature enhancement for LubeLogger that would offer users the flexibility to view dates in the DD/MM/YYYY format, aligning with the preferences of many users in regions where this format is commonly used.

This proposal entails integrating functionality into LubeLogger to enable users to select the DD/MM/YYYY date format as an alternative to the default format. By accommodating diverse date format preferences, LubeLogger can enhance user satisfaction and usability.

Date Format Selection: Implement a setting within the app where users can choose their preferred date format, including the option for DD/MM/YYYY.

Thank you for considering this proposal.

Regards

**Comment by jackthomasanderson** [comment]
I partially agree with you, as indeed in some places it is the case, but the display format is M/D/YYYY (not DD/MM/YYYY) but here I am nitpicking.

I am in France, and here is a list of areas where the display is in the M/D/YYYY format:

- Add New Service Record (after selecting a past or future date, or even the current date, the display switches to MM/DD/YYYY)
- Add New Repair Record (after selecting a past or future date, or even the current date, the display switches to MM/DD/YYYY)
- Add New Upgrade Record (after selecting a past or future date, or even the current date, the display switches to MM/DD/YYYY)
etc... in fact, all menus allowing data entry are affected.

**Comment by hargata** [comment]
That doesn't make sense, you most likely have a configuration issue.
here I used en_DE(German) locale:
![image](https://github.com/hargata/lubelog/assets/155338622/3ba52d1a-4a9d-4825-8ef7-d7b916efb7a4)

date is displayed in dd/MM/yyyy

Even after saving, it is still displayed as dd/MM/yyyy

![image](https://github.com/hargata/lubelog/assets/155338622/be101012-77c1-4885-8ffe-18475e5dd2e1)

**Comment by jackthomasanderson** [comment]
Great job! I've just checked my container's environment variables and realized I had been using the en_EN.UTF-8 locale setting. After making the necessary adjustments, everything is functioning properly again. I apologize for any inconvenience caused by raising an issue for such a minor problem. Thank you for your understanding.
