### ISSUE TITLE
Date and Currency Formats

### ISSUE THREAD

**Issue by TopicsLP** [hargata/lubelog#3]
### Issue
With the **date format** MM/DD/YYYY the application can be open for confusion for the rest of the globe using different formats like:
- DD.MM.YYYY
- YYYY-MM-DD

The **currency** of $/USD may not be appealing to everyone, considerations should be taken to include other common values.

### Proposed Solutions
For the **date format** you maybe able to add a setting to toggle to use a display of the date based on ISO8601/RFC3339 ```YYYY-MM-DD``` this is probably the simplest solution and I think a good compromise, but maybe also a drop-down to just selected the favored date format.

**Currency**, similar approach could be taken in the settings a drop-down to select common currency's:
- $ (USD)
- € (EUR)
- £ (GBP)
- Fr. (CHF)

**Comment by hargata** [comment]
@TopicsLP I was able to see the currency and date format changes by changing the regional culture on my computer, example(in English(Germany) is selected):
![image](https://github.com/hargata/lubelog/assets/155338622/d5354270-f5f6-4bcd-a83b-407729594621)

Is there a potential use case where the user might have their culture set to something else but need the currency on the app to display in another culture?

**Comment by TopicsLP** [comment]
Ok I did not verify that first,so besides the docker container issue it is not needed.
I agree on that most likely nearly no one needs a different date and currency format to their system locals, but maybe Linux (Desktop) Users ?

**Comment by manawenuz** [comment]
how do you change the regional culture on your docker container ? 
also adding currency conversion at the time of fueling using an API would be super

**Comment by hoferbeck** [comment]
> how do you change the regional culture on your docker container ? 
I was able to change the culture by changing two Lines in the Dockerfile:
from:
```
ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8
```
to
```
ENV LC_ALL=de_DE.utf8 \
    LANG=de_DE.utf8
```
Its now looking better (but it seems to me, that the header isn't dynamic)
![Screenshot 2024-01-07 113945](https://github.com/hargata/lubelog/assets/30021673/f1506afc-3719-47f4-900e-54ad1006b95a)

**Comment by manawenuz** [comment]
ok, thank god, it doesn't change the language, i thought it's to change the language, and the word culture i guess is something from windows world and it was rather confusing, thanks, it solved my issue.

**Comment by florianschroen** [comment]
Only locale has been changed, which is for character encoding.

See https://wiki.debian.org/Locale for reference.
