### ISSUE TITLE
[Feature request] Calendar view honoring locale settings

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog#302]
Hi,

Just noticed that popup calendar in fields where you select date is not based on locale and always starts week with Sunday.

My environment settings are set to Slovenian (I see € for currency, etc.):

```
- LC_ALL=sl_SI.UTF-8
- LANG=sl_SI.UTF-8
```

Usualy in other software locale setting will also update calendar view to change the names of days to selected locale language and show first day of week based on same locale.

![image](https://github.com/hargata/lubelog/assets/13857043/9abd600b-2bd1-4304-be0a-dd6d14194cc7)

Would this be possible to implement?

Thank you.

**Comment by hargata** [comment]
This is now added as of 1.2.0

en_US:
![image](https://github.com/hargata/lubelog/assets/155338622/1ec58888-f03c-42a1-a8ab-bd125a290865)

en_DE:
![image](https://github.com/hargata/lubelog/assets/155338622/bb97c521-6a3c-4c65-83d7-21fd602cb44b)

**Comment by thehijacker** [comment]
Just updated. Monday is first day of week now. Shame only that days in week are not translatable. We can close this ticket then.

Thank you.
