### ISSUE TITLE
[Feature Request] - Location Entry

### ISSUE THREAD

**Issue by rhino53150** [hargata/lubelog#309]
Add a feature for the entry of the location where the service, repair, or fueling occurred. Entry of the name and full address of the location for that record. Ultimately it would be nice for a find my location feature but I know aCar requires subscription for that feature. But at least a person could enter it manually.

**Comment by hargata** [comment]
You can easily just add extra fields to the records for those extra entries.

**Comment by rhino53150** [comment]
> You can easily just add extra fields to the records for those extra entries, see https://docs.lubelogger.com/Additional%20Fields

Nice, Didn't notice that feature. I will try it out.

**Comment by hargata** [comment]
@rhino53150 let me know if that works, if it does, can you close this ticket?
