### ISSUE TITLE
Do not update mileage on entry

### ISSUE THREAD

**Issue by roady356** [hargata/lubelog#312]
If I've not recorded my mileage when performing an action I would prefer to not have to enter 0 or guess so having a way of making that field not required would be great.

Plus, there seems to be a bug with the odometer. I have quite a few entries entered from setup and all have a mileage reading however my graph on the homepage is showing months that do have entries as zero.

**Comment by hargata** [comment]
@roady356 The primary purpose of the odometer field is sorting, the secondary purpose of that field is to calculate the last known mileage for reminders, etc. If you don't know the odometer reading at the time of service it is perfectly safe to input a zero for the odometer field.

As for the mileage traveled chart on the Dashboard page, please ensure that there are at least two records with non-zero odometer reading, see https://docs.lubelogger.com/Dashboard#notes-on-distance-traveled for how distance traveled is calculated.

**Comment by hargata** [comment]
Additional note on making the odometer field optional: we did consider doing this earlier on in the app to make odometer field optional, see this reddit comment from a month ago: https://www.reddit.com/r/selfhosted/comments/18zjwl9/comment/ki9akd3/?context=3

The real technical issue is that under the hood, odometer is an integer type and blank inputs will basically be converted and treated as a 0, which means that after the user has saved the record, when it comes back to the user it's very difficult to determine if the user left it blank intentionally or inserted a 0. From my experience working in the auto industry as a lube tech when I was younger, a lot of the fleet software used in the industry requires a 0 input for odometer if it's not available for the very same reason.

**Comment by edlucky1** [comment]
@hargata I see a use case for non-highway equipment. Boats, lawn mowers, ATVs, tractors, etc. will likely not have an odometer. Having an optional toggle (at the vehicle level) for odometer requirement would make sense in those cases. Using "0" will likely work for my use case, but I could see this becoming annoying for heavy users of these kinds of equipment.

**Comment by hargata** [comment]
Next release:
![optionalodometer_upgrades](https://github.com/user-attachments/assets/0e5f0a9d-6171-4033-ab73-253dbe4c4213)

Note that if you have "auto-insert odometer record" enabled and you add a record without odometer reading it will not create that odometer record.

**Comment by hargata** [comment]
Released.
