### ISSUE TITLE
[Feature Request] Bulk Editing

### ISSUE THREAD

**Issue by jackthomasanderson** [hargata/lubelog#320]
Currently, we are faced with the tedious task of individually editing data entries such as date, mileage, description, cost, and notes in LubeLogger. This approach consumes a lot of time and effort, especially when we need to make modifications to multiple entries.

Therefore, I suggest implementing a feature that would allow users to select multiple entries at once and apply bulk modifications. Specifically, we would need the following features:

- Bulk Editing of Data: The ability to select multiple entries and simultaneously modify fields such as date, mileage, description, cost, and notes.
- Bulk Data Deletion: The capability to select multiple entries and delete them in a single action.
- Bulk Data Duplication: The ability to select multiple entries and create identical copies in a single action.
- Bulk Data Movement: The facility to select multiple entries and move them to another category or section in a single action.

I am confident that integrating these features would significantly streamline the data management process for LubeLogger users, saving them time and effort.

Thank you very much for your attention to this request and for your ongoing work on LubeLogger.

Best regards,

**Comment by hargata** [comment]
Currently working on this, Items 2, 3, and 4 can be worked on pretty easily, biggest technical challenge with Item 1 is determining whether a user actually wants to overwrite those fields or just modify certain fields, i.e.: when a user selects a bunch of rows and click the edit button, there is only one window that will show up, it's very tricky to know if the user only wants to overwrite the description and leave notes, dates, costs, etc. as is.

**Comment by hargata** [comment]
Released in 1.2.2

Watch this video: https://youtu.be/m_FAbZODdyY?si=CGC3SR5vN-xuZ5rj&t=188
