### ISSUE TITLE
[Feature Request] All pulled data for 'export' 

### ISSUE THREAD

**Issue by Uncanny5180** [hargata/lubelog#324]
Greetings, hear me out on this suggestion. I'd like to see a zip file of everything from a vehicle of record, when requesting an export. For instance, I want an export of a 1994 honda accord, it has 200 entries for fuel, service, and has 40 some attached receipts. Let's say I am selling the car. I'd like to hit export, the app would put together the csv's for each of the record categories, and then just dump the attachments into an 'attachments' folder of some sort. I can then hand this off to the buyer, and they have everything they need in terms of record keeping. Does that make sense? Good idea/bad idea??

**Comment by hargata** [comment]
This is already implemented in some shape or form in the dashboard page. The attachments can be exported in a chronological order in a zip file and you can view all of the records in a consolidated view using the consolidated report function. Building a feature to export all the other data in zip file containing the CSV exports seems redundant when both those functionality already exists.

**Comment by Uncanny5180** [comment]
> This is already implemented in some shape or form in the dashboard page. The attachments can be exported in a chronological order in a zip file and you can view all of the records in a consolidated view using the consolidated report function. Building a feature to export all the other data in zip file containing the CSV exports seems redundant when both those functionality already exists.

Oh,...well ok then. I was not aware of that feature from the dashboard, and I'll have to look into it a bit more.
