### ISSUE TITLE
[Feature Request] Adding support for recurring cost i.e insurance costs

### ISSUE THREAD

**Issue by hoferbeck** [hargata/lubelog#33]
Hello,

I like the project so far! (thanks for the work)

But a feature what i would like to have, is to have support  to automatically create recurring costs.

For example, in Europe you pay (monthly / quartly or yearly) a fixed cost for the insurance, 
or some pay a recurring fee for a automobile club (and in exchange, if your car is broken its free to tow you car, if you book it over the the  automobile club)

Best regards

**Comment by hargata** [comment]
I can add this, but it will be under the "Tax" tab, because records in that tab does not require a mileage field.
I should probably also rename that tab so it's registration/insurance/etc. costs that aren't tied to mileage.

**Comment by jstebenne** [comment]
I would probably rename the tab "Fees"

**Comment by richard-lee-863** [comment]
Was just going to ask about a separate "Fees" category for Parking fines, speeding fines, etc..? Would that be suitable as a different type of record? Or would you just put it under this current "Taxes" field?

**Comment by hargata** [comment]
@hoferbeck recurring tax/fees are now added in the tax tab.
