### ISSUE TITLE
Date format and currency

### ISSUE THREAD

**Issue by desosav** [hargata/lubelog#331]
Hello,
i have changed the LC_ALL & LANG variables to be compatible with European date format (DD/MM/YY) and the euro currency symbol.
Galons and miles have changed to liters and kilometers respectively which is great, but the date remains in (MM-DD-YY) format and the euro symbol is not properly displayed.
![image](https://github.com/hargata/lubelog/assets/47779640/b91163b4-9e62-4fe9-bcb8-5fa7ac0f7424)

**Comment by hargata** [comment]
Your environment variables are not injected correctly, you need to either recreate your .env file or find out why, a user reported a problem with portainer/synology in the past and they had to insert the environment variables in a different way

**Comment by hargata** [comment]
Will be closing this issue since this has been been answered plenty of times. Please read the troubleshooting guide,.
