### ISSUE TITLE
Service Record tags are not shared across multiple vehicles?

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#335]
I have entered many tags for one of my cars

![image](https://github.com/hargata/lubelog/assets/10135929/505ffdc6-9e23-41f6-9d04-08c6343388c0)

But they do not appear as options in my 2nd car:
![image](https://github.com/hargata/lubelog/assets/10135929/4f8156b2-a11a-4806-b05d-511eb7cc07b4)

Is there any way to migrate/share them across vehicles?

**Comment by hargata** [comment]
Do you mean the suggested inputs like this?
![image](https://github.com/hargata/lubelog/assets/155338622/d0a9b8a4-e634-493e-8c5c-5095872e4a44)

**Comment by alternativesurfer** [comment]
Yes, sorry if I wasn't more clear.
That is what I mean.

**Comment by hargata** [comment]
@alternativesurfer hey so I've looked into this, I wasn't able to find a scalable/performant way of compiling all tags across all vehicles, BUT as of 1.2.3, I have added a copy/paste method for the tags input.

So what you can do, is you can hit CTRL+C when the tags input is selected(you need HTTPS connection for this), and it will copy all of the tags, and then you can hit CTRL+V to paste those tags into the tags input of another vehicle.

I know it's not perfect, but this should cover your use case to some extent, you can actually try this on the demo site right now.

![tagsinputcopypaste](https://github.com/hargata/lubelog/assets/155338622/1e2cee7f-8d61-400c-9241-513d35b037a3)
