### ISSUE TITLE
Context menu closes when right click is released

### ISSUE THREAD

**Issue by 6asc** [hargata/lubelog#339]
**Checklist**

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
The context menu only stays open if I hold down right-click. As soon as I release right-click, the menu closes.
I can still use the menu if I left-click on an option while I'm holding down right-click to keep the menu open.
This seems to be a Linux specific issue as I could not reproduce it on Windows. It happens with Firefox and Chrome.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
No errors

**App/Container Console Error**
No errors

**Comment by hargata** [comment]
I don't have a linux system to test this with, but can you pull the `:edge` tagged docker image into a **test** container and see if this still happens?

**Comment by 6asc** [comment]
With the :edge image, it doesn't happen anymore and the context menu is working correctly. Thank you ! (Not closing the issue since the fix is not released yet)

**Comment by hargata** [comment]
Thanks for testing it out!

This fix is now released in 1.2.3

Closing this ticket.
