### ISSUE TITLE
[Feature Request] Multiple Tanks for one car 

### ISSUE THREAD

**Issue by nicolopozzato** [hargata/lubelog#34]
Hi, my car is a petrol and LPG/gasoline and LPG so I have two tanks that I like to monitor.

With the same feature you can have a petrol/natural gas (petrol/methane) but also for the new diesel car you can monitor the diesel and AdBlue tanks.

Other ideas after that, that could be implement are that the page can show two different fuel economy graph but also a composed one and a medium price per km/mile.

**Comment by ricowalker** [comment]
I'd like this feature as well, Have a CNG/Petrol car which could make use of this as well.

**Comment by hargata** [comment]
@nicolopozzato @ricowalker 
I have rolled out a new tags feature that can help with this. When you fuel up, you can tag the fuel record with the fuel type(e.g.: Petrol, CNG, etc) and after that you can filter it with the tag and it will automatically calculate the average, min, and max mpg for the tagged records.

In my example below I tagged it with gas stations but you can tag it with whatever you want and it will calculate the MPG.

![gas tab tag](https://github.com/hargata/lubelog/assets/155338622/5e4c17e1-9a27-4798-aa76-1638bcf90971)
