### ISSUE TITLE
[Feature Request] Add Option for other curency and km

### ISSUE THREAD

**Issue by setime** [hargata/lubelog#341]
It would be great if there would be an option to change the format to km and an other currency (euro ;))
This is cosmetics but would be nice :)

**Comment by hargata** [comment]
European locale is already supported. Please see #255 #293 
More info:
https://docs.lubelogger.com/Getting%20Started
https://docs.lubelogger.com/Troubleshooting#locale-issues

Km is supported by disabling the Use Imperial Calculation setting in the "Settings" page
https://docs.lubelogger.com/Records/Fuel%20Records#fuel-units

Will be closing this as a duplicate
