### ISSUE TITLE
Feature Request - Integrate Bouncie Vehicle Data Sync Functionality

### ISSUE THREAD

**Issue by mplawner** [hargata/lubelog#345]
## Feature Request: Bouncie Data Integration

Hello LubeLogger Team!

I've developed a script, [bouncie-lubelogger-sync](https://github.com/mplawner/bouncie-lubelogger-sync), that automates odometer updates in LubeLogger by syncing vehicle data from Bouncie. This script has been a great personal helper in ensuring my vehicle maintenance records are up-to-date without manual intervention.

**Suggested Feature:**
Integrating this script's functionality directly into LubeLogger could significantly enhance user experience by:
- Automating odometer updates
- Ensuring maintenance records are always accurate
- Saving time for users managing vehicle data across platforms

I believe this integration could be a valuable addition to LubeLogger, further streamlining vehicle maintenance tracking for all users.

Thank you for considering this integration to make LubeLogger even more powerful!

**Comment by hargata** [comment]
@mplawner Thanks for reaching out, unfortunately, LubeLogger is a web app and is not designed to make API calls to a third party API such as Bouncie on an interval.

There is also concern regarding third party APIs in LubeLogger as it will be nearly impossible for us to maintain those API contracts, i.e.: If we attempt to integrate Bouncie API into LubeLogger it is only a matter of time before users of other Bouncie-like apps want us to integrate their platform as well, and we can't possibly keep up on all of the API contracts.

**Comment by mplawner** [comment]
Makes sense! Thanks for the reply and all the excellent work on LubeLogger!
