### ISSUE TITLE
FEATURE Request - New stats and fields

### ISSUE THREAD

**Issue by varunpan** [hargata/lubelog#351]
Hi, I am loving this application and thank you for building this as the existing ones did not provide information at this level. 

1. I would love to see if how many miles between specific types of service(tags). For example, average of 5,100 miles between Oil changes. Ideally based on tags from the service records. I am tagging my service tags with component names like Front Brake Pads or Front Brake Rotors and etc.

2. New Vehicle fields: 
- VIN Number
- Trim
- Engine
- Paint Code
- Radio Code
- Purchase Date
- Purchase Mileage
- Purchase Dealership
- Purchase Price

**Comment by hargata** [comment]
As of 1.2.4 you can now add extra fields at the vehicle level. Still looking into item 1 tho.

**Comment by hargata** [comment]
@varunpan released in 1.2.5
Watch: https://youtu.be/I2KlO5PVHCc?si=wGxBt72q6UNFLxJy&t=267

**Comment by hargata** [comment]
In 1.2.5, if you hold down CTRL and select the records, you can actually select multiple records not just consecutive ones. You can also use the Search feature to filter the Oil Change records

**Comment by hargata** [comment]
Hmm I haven't got a Mac to try, does shift+click do anything on Macs? I might have to look into adding that as an alternative for next release, for now I think you can use the search feature along with tagging records.
