### ISSUE TITLE
1.2.4 - Custom Field

### ISSUE THREAD

**Issue by mickelsr** [hargata/lubelog#355]
Created under Vehicle 2 extra fields. If i write something and open it up. No Text is in the field :/ Looks like the Input doesnt run on the DB

**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)

**Description**

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**Comment by hargata** [comment]
Have you tried clearing your browser cache? Alternatively you can try hitting CTRL+SHIFT+R a few times
