### ISSUE TITLE
Feature request: Environment variables for root user credentials

### ISSUE THREAD

**Issue by tigattack** [hargata/lubelog#356]
Hi, love this app, thank you for your work! Super useful.

Would you consider adding environment variables for the root user/pass? I think this would be a really useful feature.

**Comment by hargata** [comment]
@tigattack I'm curious about the use case for this. Are you attempting to change the username and password pretty frequently through an automated process?

**Comment by tigattack** [comment]
From a more generic POV, I think this would provide value as far as the user having one less thing to configure – If they want authentication, they need only specify two env-vars, rather than deploying, browsing, and clicking a few times to get that set up.

My use case is probably fairly niche and/or specific to my preferences, but here it is: simply a fully automated/zero config deployment from an authentication POV. I manage all of my deployments with Ansible and source credentials from a secrets manager, so the ability to specify credentials with env-vars would justify putting them into my secrets manager (otherwise there's a clear disconnect between what's actually configured and what's in the secrets manager, leading to inevitable problems). At that point, I could further automate things such as backups and custom scripts (I plan to write a script for automated imports from Fuelio), sourcing the credentials for such actions from my secrets manager.

**Comment by hargata** [comment]
@tigattack that's understandable. I've built something that can probably fulfill this use case and will be released in 1.2.5

You're going to need the following:
- The ability to hash the username and password to SHA256 (here's an online tool that can do that: https://emn178.github.io/online-tools/sha256.html)
- Pass in the following environment variables: EnableAuth: true, UserNameHash: <hashedUserName>, UserPasswordHash: <hashedUserPassword>
- Delete userConfig.json located in /App/config - Note that this step forces LL to load the user credentials from the environment variables but will also result in the other settings such as Dark Mode, etc to be cleared out, if you don't want to delete it, you can remove the following attributes from it EnableAuth, UserNameHash, and UserPasswordHash

This will be released in 1.2.5 which is scheduled for 03/08/24

**Comment by hargata** [comment]
@tigattack Released in 1.2.5, watch: https://youtu.be/I2KlO5PVHCc?si=Yx2Pvf9dSU08qE3w&t=655

**Comment by tigattack** [comment]
Thanks a ton @hargata, it works great.

I noticed this repeated a bunch in the logs:

```
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Corrupted credentials
```

Everything seems to work fine, but thought I'd mention it.

I removed the specified keys from my userConfig.json before deploying the new image with UsernameHash and UserPasswordHash variables, so it looks like this now (file contents are still minified, just expanded here for readability):

```json
{
  "UseDarkMode": true,
  "EnableCsvImports": true,
  "UseMPG": true,
  "UseDescending": true,
  "HideZero": false,
  "UseUKMPG": true,
  "UseThreeDecimalGasCost": true,
  "UseMarkDownOnSavedNotes": false,
  "EnableAutoReminderRefresh": false,
  "EnableAutoOdometerInsert": true,
  "EnableShopSupplies": false,
  "PreferredGasUnit": null,
  "PreferredGasMileageUnit": null,
  "UserLanguage": "en_GB",
  "VisibleTabs": [
    0,
    8,
    1,
    4,
    2,
    3,
    5,
    9
  ],
  "DefaultTab": 8
}
```

**Comment by hargata** [comment]
@tigattack that's just informational, add this environment variable to get rid of those logs:
`LOGGING__LOGLEVEL__DEFAULT=Error`
