### ISSUE TITLE
[Feature Request] Supplies/Parts

### ISSUE THREAD

**Issue by Bovive** [hargata/lubelog#36]
I would love to see a parts and supplies section, which allows me to enter a parts picture, price, and supplier. Then have the ability to add those parts and supplies to a service and have the parts/supplies that were used added to the cost. This would be very helpful for those that do a lot of self service. 

Having the ability for those parts and supplies to either be "Universal" or vehicle specific would also be beneficial. It also helps track exactly what was serviced and replaced when you do it yourself. Thanks!

**Comment by hargata** [comment]
this is now being worked on.

**Comment by hargata** [comment]
This is now available as of 1.0.6!
It is a tab that is hidden by default, you will have to enable it in Settings.
https://www.youtube.com/watch?v=r_n9ncgv31E

**Comment by hargata** [comment]
Eventually I will have plans to be able to create service/repair/upgrade records from the parts page itself and it will automatically fill in the costs and deduct the quantity from the supplies page, but that is a little further down the road.

**Comment by Bovive** [comment]
Simply amazing. You are on fire with these updates. Would it be possible to add the option to upload an image to the supply item? I think it would be nice to browse through the part list with seeing a small image of the part.

**Comment by hargata** [comment]
@Bovive Thanks! Thumbnails are currently not on the list of items being planned, Problem is primarily with horizontal screen real estate on smaller screens such as phones. For now I think we can just close this feature request as it's completed.

**Comment by bigbadbabey** [comment]
Is there a way to have Parts used by multiple vehicles? So let's say I have multiple vehicle's that all use the same oil, I can track the total oil available, not just per vehicle?

**Comment by hargata** [comment]
@bigbadbabey I just made a ticket for that, #246 will be worked on after PostgresSQL backend is released.

**Comment by bigbadbabey** [comment]
I can’t express enough how amazing you are! Thank you so much!!!!

**Comment by hargata** [comment]
@bigbadbabey can you pull down the :edge tagged image and try it out, you should see a Supplies tab on the garage level, anything put in there can be requisitioned by any vehicle.

**Comment by bigbadbabey** [comment]
I pulled down Edge, and that is working perfect! Thank you. I did run into a weird issue on Safari 17.3, at first the tab was there but showed a blank page.  On Firefox (macOS) it was fine. I changed the user agent on Safari to Firefox, then the page displayed correctly. Probably just a safari bug but I wanted to bring it up just incase.

**Comment by hargata** [comment]
@bigbadbabey it's actually a caching issue, basically your web browser cached an older version of the javascript file and that's why it didn't display, switching browsers or clearing your cache will force your browser to update the local copy of the JS file and hence it will work. Before I release the shop supplies feature, I'm actually going to hide it behind a setting in the "Settings" tab so that users who don't care about shop supplies can hide the tab by default.

**Comment by bigbadbabey** [comment]
Would it also be Possible to add a "Part Number" column to the "Select Supplies" List?

**Comment by hargata** [comment]
@bigbadbabey done.
