### ISSUE TITLE
Feature Request: User Defined Reminder Urgency Mileage Fields

### ISSUE THREAD

**Issue by mherman95** [hargata/lubelog#366]
I have a trucking company with just a few trucks and was going to set this up to manage our service records as well as give us reminders of when services are coming up, however we run 400-500 miles per day on average with service intervals between 15K miles and 30K miles.  It would be nice if we could actually set our own reminder intervals for more high mileage vehicles such as ours.  Just a thought.  Thanks again for creating this great software!

**Comment by hargata** [comment]
Hey, you can already set your own mileage intervals for the reminders, just select "Other" in the dropdowns and it will prompt you to enter a custom mileage or month interval
![image](https://github.com/hargata/lubelog/assets/155338622/47b5866f-0111-4ef8-82de-804e69c372a7)

**Comment by mherman95** [comment]
Yes. The urgency ranges. For me, I drive 2000-2800 miles per week. Having the urgency chance when it's within 100 miles wouldn't be ideal. I would prefer to be told when I'm within 2500 miles to prepare and schedule the service.

**Comment by hargata** [comment]
@mherman95 Got it, is this for Docker or Windows? and are you pretty familiar with configuring environment variables or appsettings.json?

I might be able to come up with something for this upcoming release

**Comment by mherman95** [comment]
I use it in a docker container. I'm not too familiar with it but definitely would love to learn!  Thank you!

**Comment by mherman95** [comment]
Is there a variable that I can set in appsettings.json that can set the urgency ranges?

**Comment by hargata** [comment]
@mherman95 in 1.2.5 I'll include a menu in the settings that will make setting the urgency thresholds a piece of cake

**Comment by mherman95** [comment]
Thank you!

**Comment by hargata** [comment]
@mherman95 Released in 1.2.5, watch: https://youtu.be/I2KlO5PVHCc?si=U7L3XY_ih0bouC6n&t=869

**Comment by mherman95** [comment]
Thank you so much!
