### ISSUE TITLE
Feature Request - choice of currencies

### ISSUE THREAD

**Issue by projector22** [hargata/lubelog#370]
Hi, thanks for a great app, I had fun last night spinning it up and putting in my vehicle's particulars.

I would very much like to be able to localize the app, at least in terms of currency - where I live we do not use the USD.

Appreciate the work.

**Comment by hargata** [comment]
Hi, you can already localize currencies and date format by changing the environment variables. Please see

https://docs.lubelogger.com/Getting%20Started

**Comment by projector22** [comment]
Sweet - thank you
