### ISSUE TITLE
Unable to Send Emails

### ISSUE THREAD

**Issue by dnburgess** [hargata/lubelog#371]
**Description**
I created an app password for my email account to be accessed by LubeLogger, I am unable to send emails of any kind.

I don't know if this matters, but I'm using a Proxmox 8.1.4 and deployed LubeLogger v1.2.4 on a Proxmox LXC based on Debian 11.9.0.

I've also tried via local IP address and on a domain name. Both methods gave me the same result.

**Platform**
- [x ] Docker Image

**Browser Console Errors(F12)**
Nothing was generated in the browser console. I tried multiple times and nothing happened.

**App/Container Console Error**
![image](https://github.com/hargata/lubelog/assets/5509008/313ef433-3468-48d3-a5ca-9a8ec678f755)

**Screenshots(optional)**
This is my .env file. It was created when I cloned the repository. I also tried deleting everything in it and starting over with a fresh file. 

![image](https://github.com/hargata/lubelog/assets/5509008/5f75c07f-4d23-41c4-a593-e6ff6589391d)

Here is the docker-compose. This file was created when I cloned the repository.

![image](https://github.com/hargata/lubelog/assets/5509008/987a0236-c4b4-40e7-9a72-ab6f753fff83)

Literally everything else seems to work, but when I try to create a new user, the "Auto Notify" is greyed out, so I can't click it. I'm able to create users, vehichles, update each of the different tabs for vehicles, etc.

Thanks for any help I can get on this :)

**Comment by hargata** [comment]
Did you re-create the docker container?

**Comment by dnburgess** [comment]
Every time I made a change to the .env file I restarted the container. Forgot to mention that earlier.

I just tried removing the quotes from the key values (and restarted the container) and I get the same end result.

**Comment by hargata** [comment]
@dnburgess does your currency format show up correctly or does it show ¤ ?

**Comment by hargata** [comment]
If your currency symbols aren't showing up correctly, it can mean that the environment variables aren't making into the Docker Container, this isn't the first time this has happened, not sure why.

but...

If your currency symbols show up correctly as $, try switching LC_ALL and LANG to en_GB and check if your currency symbols have switched from British Pounds. If they don't, that means the updated environment variables didn't get passed into the docker container.

Instead of restarting the container can you "docker compose up -d"? This will redeploy the image and hopefully pass in the new environment variables.

**Comment by dnburgess** [comment]
Just checked my Supplies page and am seeing  $

**Comment by hargata** [comment]
@dnburgess can you see the other comment I posted above about checking if the environment variables are being updated as the container is being restarted?

**Comment by dnburgess** [comment]
Thank you for the info. I'll have to give your troubleshooting steps a try tomorrow. I'll update when I have more information.

**Comment by hargata** [comment]
Thanks for being patient, I'll need to make it easier to troubleshoot environment variables related issues in future releases.

**Comment by dnburgess** [comment]
Ok. So it seems that any time the .env file is updated, a docker compose -d has to be run. Simply restarting the container doesn't do it.

My .env file looks like this and it worked after I did brought it back up via docker compose -d:

![image](https://github.com/hargata/lubelog/assets/5509008/bbf69941-115a-4660-8a7b-e8ee7fe98e09)

I am now able to send emails.

**Comment by hargata** [comment]
Sweet!
