### ISSUE TITLE
[Bug] Vehicle Maintenance Report - giant black box

### ISSUE THREAD

**Issue by edlucky1** [hargata/lubelog#373]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Vehicle Maintenance Report shows a giant black box below the report (see below). This wastes printer ink and doesn't look professional.

This happens using Chrome and Safari on Windows 10, iOS and iPadOS.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
n/a

**App/Container Console Error**
n/a

**Screenshots(optional)**

![Report](https://github.com/hargata/lubelog/assets/76714493/3a6db4b1-ba49-4576-b9e5-aa4ac1a8efa7)

**Comment by hargata** [comment]
This is now being worked on and will be released next week.

**Comment by hargata** [comment]
Fixed in 1.2.6.
