### ISSUE TITLE
[FEATURE REQUEST] The odometer columns in each of the pages are too wide

### ISSUE THREAD

**Issue by myharries** [hargata/lubelog#376]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [ x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [ x] I have searched through existing issues.

**Description**

**Platform**
- [ x] Docker Image
- [ ] Windows Standalone Executable

The odometer & costs columns in each of the pages are too wide, they could be at least half the width ( if not a third) this would allow for any extra fields to be displayed

Thanks
David

**Comment by hargata** [comment]
This is now  being worked on. On the next release, the column(s) will automatically shrink if needed.

![image](https://github.com/hargata/lubelog/assets/155338622/f2ea9fcc-ea2b-4689-8ea8-c699c223e63b)

![image](https://github.com/hargata/lubelog/assets/155338622/1c8f36d4-3458-4d30-a737-8669e8f71d9e)

**Comment by myharries** [comment]
Thanks, heaps!

**Comment by hargata** [comment]
Fixed in 1.2.6
Watch: https://youtu.be/x4xY-YQN-5w?si=HWToCyU30u8NBCih&t=270

**Comment by myharries** [comment]
Excellent, Thanks.
