### ISSUE TITLE
Not able to add a car after docker compose up

### ISSUE THREAD

**Issue by hsaade-algo** [hargata/lubelog#379]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Coming from Django, I would say there might be a DB migration issue. Here is my docker-compose.yml:
version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - config:/App/config
      - data:/App/data
      - translations:/App/wwwroot/translations
      - documents:/App/wwwroot/documents
      - images:/App/wwwroot/images
      - temp:/App/wwwroot/temp
      - log:/App/log
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8083:8080
    env_file:
      - .env

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: "lubelogger"
      POSTGRES_PASSWORD: "lubepass"
      POSTGRES_DB: "lubelogger"
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  config:
  data:
  translations:
  documents:
  images:
  temp:
  log:
  keys:
  postgres:
  
  I uncommented the POSTGRES_CONNECTION variable in the .env file.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

fail: CarCareTracker.External.Implementations.PGReminderRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 22
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 22
fail: CarCareTracker.External.Implementations.PGNoteDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGServiceRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGGasRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGCollisionRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGTaxRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGUpgradeRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGSupplyRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGPlanRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGPlanRecordTemplateDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGOdometerRecordDataAccess[0]
      3F000: schema "app" does not exist
      
      POSITION: 28
fail: CarCareTracker.External.Implementations.PGExtraFieldDataAccess[0]
      42P01: relation "app.extrafields" does not exist
      
      POSITION: 18
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGExtraFieldDataAccess[0]
      42P01: relation "app.extrafields" does not exist
      
      POSITION: 18
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
fail: CarCareTracker.External.Implementations.PGVehicleDataAccess[0]
      42P01: relation "app.vehicles" does not exist
      
      POSITION: 13
**Screenshots(optional)**

**Comment by hargata** [comment]
problem seems pretty obvious here, you just need to create a schema named "app" under the lubelogger database.

Please see: https://docs.lubelogger.com/Postgres

Otherwise this is not a bug.
