### ISSUE TITLE
[Feature Request] Calculate number of miles on separate sets of tires

### ISSUE THREAD

**Issue by samluyk** [hargata/lubelog#382]
If people have multiple sets of wheels or tires, this project could calculate the number of miles on separate sets of tires.

For example, I switch between summer and winter wheels, and want to know how may miles are on each set. I calculate it by manually entering the date and mileage, as seen here:

![Untitled](https://github.com/hargata/lubelog/assets/11977644/1ddadce3-89ac-42e1-b25a-4ec055eff635)

**Comment by hargata** [comment]
In 1.2.6 which will be released on 03/15/2024, there will be an enhancement for odometer records, you can tag the odometer records like so:

![image](https://github.com/hargata/lubelog/assets/155338622/2e5cf275-5f96-4e4c-b525-304f911e87b9)

Notice there is a total distance traveled on the odometer record and that some of the records are tagged with "goodyear" and some are tagged with "cooper" you can probably tag it with wintertires or summer tires, alternatively you can also create an extra field like I did which allows me to enter the full tire name similar to your spreadsheet.

Now, if I sort it by tag "goodyear" :
![image](https://github.com/hargata/lubelog/assets/155338622/822c0aff-6f91-4383-9772-193b953f6a17)

Notice the total distance traveled has been updated to only show total distance traveled by records with the "goodyear" tag.

If you don't want to use tagging, you can also do a search like this:
![image](https://github.com/hargata/lubelog/assets/155338622/9cc8f85d-1375-4c45-8bc7-e0cc44d3b984)

Notice that "Tires" will refer to the name of the extra column/field you added, in this case it's tires but it can be whatever you want, and then "Cooper" just refers to the data in the column that contains the keyword "Cooper"

![image](https://github.com/hargata/lubelog/assets/155338622/c8014e43-dfe3-4ac5-8717-dc4f81e175ac)

This is scheduled to be released 3/15 so it's not available yet.

**Comment by hargata** [comment]
Feature released 03/13/2024 in 1.2.6

Watch: https://youtu.be/x4xY-YQN-5w?si=vhDgYet8fmtNVL2m&t=195

**Comment by hargata** [comment]
We decided to re-visit this issue, and we think you're really going to like the new Equipment tab that we added for LubeLogger.

Documentation: https://docs.lubelogger.com/Records/Equipment

Video walkthrough: https://www.youtube.com/watch?v=Xi6eqN2bKzk
