### ISSUE TITLE
Odometer Initial Data Reverts to Zero

### ISSUE THREAD

**Issue by elykrk** [hargata/lubelog#396]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X] I have searched through existing issues.

**Description**

In the odometer section, when manually inputting initial odometer data, it reverts back to 0 when saved.

I am using version 1.2.6.

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

<img width="1315" alt="Screenshot 2024-03-13 at 10 57 09 PM" src="https://github.com/hargata/lubelog/assets/69878955/dcc8d80c-5b5a-4490-b0ff-38b3309153d5">

**Comment by hargata** [comment]
Select all, right click, and click "recalculate distance"

**Comment by elykrk** [comment]
Thanks but this had no effect. I just tried to re-add the latest entry but the initial data continues to revert to 0.

**Comment by elykrk** [comment]
Update: Looks like this only affected this when I was using the IP of the server over http. I switched over to using https and it seemed to resolve the issue. Thank you for the great app!
