### ISSUE TITLE
[Question] Database Choice

### ISSUE THREAD

**Issue by lapius** [hargata/lubelog#397]
I noticed you are using LiteDB by default and suggesting to use Postgres. But why not MySQL? I have mariaDB docker container on my server, and I use it with few other containers. Would be great if I could use it instead of Postgres. 

Or is it similar and I can just use MariaDB?

**Comment by hargata** [comment]
See this comment here:
https://github.com/hargata/lubelog/issues/4#issuecomment-1937787071
