### ISSUE TITLE
(Feature Request) Allow Adding Loan/Insurance/Registration Payment Amounts

### ISSUE THREAD

**Issue by chooch79** [hargata/lubelog#398]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X] I have searched through existing issues.

**Description**

I would like to add tracking of my vehicle payments for the loan/lease, insurance, and registration payments. This would provide a great way to track total cost of ownership.

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

No error, just feature request.
**App/Container Console Error**

No error, just feature request.
**Screenshots(optional)**

**Comment by hargata** [comment]
@chooch79 can you check out if the Taxes tab will fulfill your needs?

**Comment by chooch79** [comment]
The taxes could definitely be used for the registration. I overlooked that. Are you suggesting to use the Taxes for the Monthly payment and insurance as well?

**Comment by hargata** [comment]
@chooch79 yeap. You can even set up recurring expenses in there. The name Taxes is kinda misleading but it's basically a catch all for expenses that aren't tied to odometer readings.
