### ISSUE TITLE
Non-file based database support

### ISSUE THREAD

**Issue by userbradley** [hargata/lubelog#4]
## What is the issue you're reporting

 Currently `lubelog` only uses a flat file similar to sqlite, this means scaling becomes a huge issue as, for example, users of k8s at home are unable to properly run this highly available as it requires a single pod accessing a single database file.

## What is the proposed solution

implement a database driver for either `mysql` (`mariadb`) or `postgres` 

From my understanding, [Postgres is more _developer_ friendly](https://medium.com/lucid-plexus/why-use-postgresql-over-sql-server-in-your-project-modern-age-of-database-management-5afed16878ba) 

## Are you willing to contribute

I am not good at coding, but I can happily write documentation!

**Comment by hargata** [comment]
This is now being worked on actively.

**Comment by userbradley** [comment]
Much love! I am happy to test this, and document anything if needed

**Comment by hargata** [comment]
can you pull down the :edge tagged docker image and test it out?

Here's how to set it up LubeLogger to use a postgres backend:
https://docs.lubelogger.com/Postgres

**Comment by hargata** [comment]
@userbradley Released, watch this youtube walkthrough on how to set up LubeLogger to use PGSQL and how to migrate existing data: https://www.youtube.com/watch?v=qc9pn5vFC6Q

**Comment by monsieurpouet** [comment]
Do you think is possible to implement same thing with mysql ? <3

**Comment by hargata** [comment]
@monsieurpouet unlikely, not because of technicalities, but because of mySQL's and MariaDB's copyleft licensing model.

**Comment by hargata** [comment]
Closing this ticket since the feature is released
