### ISSUE TITLE
[Feature Request] Webhooks

### ISSUE THREAD

**Issue by reedhaffner** [hargata/lubelog#400]
I'd like to have Webhooks fired when events happen either on specific vehicles or to any on the program. It would be nice to get Discord notifications when someone submits a log, or I could fire an event in Home Assistant

**Comment by hargata** [comment]
would it be okay if I do just one webhook for all actions / all vehicles on the app and you can parse the json data and decide what you want to do with it depending on the vehicle id / user id ?

**Comment by reedhaffner** [comment]
Yeah I think that's reasonable, it's more of an administrative tool so I don't think each vehicle would need it

**Comment by hargata** [comment]
kk, the payload will look somewhat like this:

![image](https://github.com/hargata/lubelog/assets/155338622/13df4bef-dfc7-4dda-bac7-e1260cb598ea)

Currently I have the following triggers:

- Add / Edit / Delete Vehicle
- Add / Edit / Delete Plan/Odometer/Service Record/Repair/Upgrade/Gas(Fuel)/Tax/Notes/Supply/Reminder
- Bulk Move Service Record/Repair/Upgrade
- Bulk Delete and Duplicate Odometer/Service Record/Repair/Upgrade/Gas(Fuel)/Tax/Notes/Supply/Reminder
- API actions for adding records stated above.

This will be released 03/17

**Comment by hargata** [comment]
Released in 1.2.7

**Comment by hargata** [comment]
Forgot to attach the video link to this: 
https://youtu.be/fJJtoFDSVrs?si=K7-BKR0ibKnWvkN3&t=409
