### ISSUE TITLE
[feature request] include VIN number field with vehicle info

### ISSUE THREAD

**Issue by dmt408** [hargata/lubelog#41]
It would be nice to also be able to record the VIN number under the license plate. This is useful for when you need to get parts and need the vin to make sure you are getting the right ones.

**Comment by hargata** [comment]
I think the VIN is better suited to be stored in the "Notes" portion of the vehicle. The design choice of including the license plate was to be able to quickly identify vehicles by their garage tile just in case someone manages a fleet of vehicles with the same year, make, and model.

**Comment by dmt408** [comment]
ahhhh. that does make more sense.
