### ISSUE TITLE
Feature Request - Wiki for the Vehicle

### ISSUE THREAD

**Issue by varunpan** [hargata/lubelog#410]
I want to be able to include detailed instructions on how to perform a specific Services/Repairs/Upgrades on one of the vehicles in my garage. 

I would like to track the following in the instructions:
- Supplies needed with an amount quantities and estimated cost.
- Tools need for the service.
- Estimated time needed to perform the service. 
- actually instructions, preferably with a way to SEE photos that were added in the instructions when viewing.
- ability to add links to YouTube videos or websites for reference.

This way I can make sure I have everything I need and enough time to complete the service before I start and have the instructions ready to go. 
As a new DIYer, I find myself looking up the youtube videos and website for instructions before hand and its would be nice to have it part of this application in one place. 

I would prefer it at the vehicle level so I can have vehicle specific instructions with the appropriate torque settings and photos/links for that specific vehicle

**Comment by hargata** [comment]
This sounds like a Plan Template.

**Comment by hargata** [comment]
hm? You don't have to re-write the steps. If you create a plan template, you can just re-use the template over and over again and it will automatically apply the supplies and the notes, files, attachments, etc. to it.

**Comment by hargata** [comment]
https://www.youtube.com/watch?v=qnew5I6UU8c&t=174s

**Comment by hargata** [comment]
If you create a template for it you can.

**Comment by hargata** [comment]
You can just delete the old template and re-create it.
