### ISSUE TITLE
[Feature Request] Add URL field for attached documents

### ISSUE THREAD

**Issue by auer1329** [hargata/lubelog#412]
I don't know if I am alone with my request, but I think it would be nice to link attachments like receipt PDFs via links to an external document management system like Paperless-ngx.

E.g. my receipts are all stored on dms.domain.de/documents/5734/details and I'd like to be able to store a clickable link to the document in the lubelog records, so I don't have to store duplicates here.

Currently I copy the URL to the notes field, but I have to copy it every time I want to open a file.

**Comment by redge76** [comment]
You can user markdown. 
https://docs.lubelogger.com/Records/Notes

For example:
[Gas Receipt](https:// dms.domain.de/documents/5734/details)

**Comment by auer1329** [comment]
> You can use markdown. https://docs.lubelogger.com/Records/Notes https://adamvleggett.github.io/drawdown/
> 
> For example: [Gas Receipt](https:// dms.domain.de/documents/5734/details)

Thanks for the hint, I just tried it and it's definitely better than copying the URL.
But unless the notes are displayed in Markdown with clickable links in the table view, it is not really an advantage.

**Comment by auer1329** [comment]
> You can use markdown. https://docs.lubelogger.com/Records/Notes https://adamvleggett.github.io/drawdown/
> 
> For example: [Gas Receipt](https:// dms.domain.de/documents/5734/details)

Thanks for the hint, I just tried it and it's definitely better than copying the URL.
But unless the notes are displayed in Markdown with clickable links in the table view, it is not really an advantage.

**Comment by hargata** [comment]
@auer1329 you can set the notes to be displayed in markdown by default in the Settings. "Display Saved Notes in Markdown"

**Comment by auer1329** [comment]
> @auer1329 you can set the notes to be displayed in markdown by default in the Settings. "Display Saved Notes in Markdown"

Yes I tried this, but it does not affect the Notes preview in the list view, or am I missing something?

**Comment by hargata** [comment]
@auer1329 it doesn't render it in the list view, you have to click on the item itself see the link.

**Comment by auer1329** [comment]
> @auer1329 it doesn't render it in the list view, you have to click on the item itself see the link.

Exactly, that is what my feature request is about :)

**Comment by hargata** [comment]
@auer1329 in 1.2.8, I will add a automatic parser for links in Extra Field columns, if the value in the extra field is a URL, then it will be clickable like this:

![image](https://github.com/hargata/lubelog/assets/155338622/066052ba-a403-4011-b79f-f6e210a144aa)

Otherwise it will not be clickable like "Test"

**Comment by auer1329** [comment]
This is very helpful, thank you!

**Comment by hargata** [comment]
This is released in 1.2.8
