### ISSUE TITLE
When there are two refuel on same date, the distance is not calculated correctly

### ISSUE THREAD

**Issue by jstebenne** [hargata/lubelog#417]
**Checklist**

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X] I have searched through existing issues.

**Description**
When doing more than one refuel on the same date, the distance calculation is not done correctly, resulting in a negative value for the distance, which causes incorrect calculations in other fields.

It looks like instead of relying on the date to order the list, the odometer should be used. This would allow a more reliable ordering since having two identical odometer entries would not make sense. And even if there are, the calculations for fuel economy should not break, though displaying an infinity sign for fuel economy might be required, as dividing by 0 (the distance) rarely leads to a satisfying outcome.

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
No errors

**App/Container Console Error**
No errors

**Screenshots(optional)**

![2024-03-20_08-49](https://github.com/hargata/lubelog/assets/1571895/42a5412a-f89a-4189-babb-1343aa3b8451)

**Comment by hargata** [comment]
I'm having trouble trying to replicate this

![image](https://github.com/hargata/lubelog/assets/155338622/36f5a97b-64e8-4203-87f8-7e0989e87009)

**Comment by hargata** [comment]
I'm thinking that there is some form of data corruption going on in here, but I cannot replicate this, if you can send me a copy of your db with PII's removed or redacted I can troubleshoot this better, but I've tried everything on my end and cannot get the app to do this at all.

**Comment by jstebenne** [comment]
I've had the same scenario happen yesterday, but the bug did not occur.

Could it be because the refuels were not created in the same order as it is displayed? (2271 created after 2436)

![2024-03-22_09-30](https://github.com/hargata/lubelog/assets/1571895/6b7f9b59-f059-4d84-8c27-1e902937fc6d)

I do not have a good way of anonymizing the db. Do you have a tool for that?

**Comment by jstebenne** [comment]
Also, here are my settings, in case it is useful:

![image](https://github.com/hargata/lubelog/assets/1571895/d8e328ab-4930-48f5-823d-8fb2be29991a)

**Comment by hargata** [comment]
@jstebenne I don't think it's due to the order of refuels, as for anonymizing the DB, can you try Exporting your refuels to CSV and sending me the CSV? It will only contain your refuel data and nothing else.

On a side note, it also seems like your locale isn't set correctly, hence why you're seeing the default currency symbol.

**Comment by jstebenne** [comment]
Here's the CSV: [d4049ec8-8d8a-4c71-9b39-3ac94f34a280.csv](https://github.com/hargata/lubelog/files/14760342/d4049ec8-8d8a-4c71-9b39-3ac94f34a280.csv)

**Comment by hargata** [comment]
@jstebenne I imported your CSV file but was not able to re-create the bug.

![image](https://github.com/hargata/lubelog/assets/155338622/f293e86c-41c2-4bcd-9aef-1f9e4a59f159)

**Comment by jstebenne** [comment]
Sorry, I forgot about this ticket.

I deleted both entries and everything looks normal. I'll close the issue until it happens again. Maybe it was a bug that was "accidentally" fixed
