### ISSUE TITLE
[Feature Request] Vehicle purchase cost / price per day of ownership

### ISSUE THREAD

**Issue by dbrustad** [hargata/lubelog#424]
Absolutely love this app and use it religiously every fill up. Perhaps I'm the only one that would enjoy this feature, but would it be possible to have a "purchase price for the vehicle" field in the vehicle setup page, and the on the dashboard you could do all sorts of fun calculations like cost per day of ownership of the vehicle only, or with fuel and vehicle, or repairs and parts etc.

Thanks again for this awesome piece of software!

**Comment by Forceu** [comment]
Yes, both would be great additions! I currently track the purchase price as an upgrade item, which kind of skews the graph

**Comment by hargata** [comment]
In 1.2.9, you will be able to insert the Purchase and Sold price of the vehicle, which will allow you to calculate the depreciation cost, depreciation / mile and depreciation / day

![image](https://github.com/hargata/lubelog/assets/155338622/348136cd-bd98-4fb1-8e4b-1a26fac93bf8)

![image](https://github.com/hargata/lubelog/assets/155338622/946d5a73-d47f-4a8a-845d-2a8d92ccc01a)

**Comment by Forceu** [comment]
Awesome, thanks a lot!!

**Comment by hargata** [comment]
@Forceu released in 1.2.9
