### ISSUE TITLE
[Enhancement/Feature Request] Fuel Grade

### ISSUE THREAD

**Issue by coffeekomrade** [hargata/lubelog#425]
Some types of vehicles, such as light duty trucks, turbocharged, and others opt to use different fuel grades depending on the application. A driver may use 91 or 93 when towing but otherwise use 89 or 87 for daily driving. Adding fuel grade would give a finer grain insight to these users as to where there fuel costs are. The user may also have multiple vehicles that use different fuel grades (project cars, sports cars, racing)

An example would be for Ford vehicles, included is an excerpt from the owners manual for a Ford F-150 and a Ford Maverick with turbocharged ecoboost engines

> Your vehicle is designed to operate on regular unleaded gasoline with a minimum pump (R+M)/2 octane rating of 87.
> 
> For best overall vehicle and engine performance, premium fuel with an octane rating of 91 or higher is recommended. The performance gained by using premium fuel is most noticeable in hot weather as well as other conditions, for example when towing a trailer.

**Comment by hargata** [comment]
Duplicate, see #383 #34 #78
