### ISSUE TITLE
[Bug] - Deleting Planned Activity does not re-add the supplies back.

### ISSUE THREAD

**Issue by varunpan** [hargata/lubelog#429]
I noticed that there is a bug when you delete a planned activity with supplies, it does not add the used supplies back to the supplies list. 

Re-Creation Steps:

1. Create a planned activity with supplies selected for the planned activity.
2. Delete the planned activity.

You will notice that the used supplies quantities are not added back to supplies in the garage/car.

Please let me know if you need additional information.

**Comment by hargata** [comment]
Next release:

![replenishsupplieswhendelete](https://github.com/user-attachments/assets/40f58f6d-63d8-46b2-b1d6-b43a159e976f)

You'll be able to delete the requisition history for within the plan/service/repair/upgrade record and it will replenish the supply quantity, you can also delete the entire record and it will replenish all of the requisitioned supplies.

**Comment by hargata** [comment]
Released.
