### ISSUE TITLE
[Feature Request] - ability to add where the vehicle was serviced

### ISSUE THREAD

**Issue by bigbearct** [hargata/lubelog#43]
Would like the ability to track where the vehicle was serviced:

Garage Name
Phone Number
Service Advisor Name

**Comment by hargata** [comment]
This is probably better suited to be added in the Note section when adding a service record, otherwise we will have a near infinite amount of fields.

**Comment by Firemanjoe** [comment]
This isn't a bad idea and could be a reportable field later on. I understand the idea of keeping it in the notes, but if it becomes a table in the db, then users who complete services at multiple different locations could see a spread of the data and where the money was being spent.

**Comment by hargata** [comment]
@Firemanjoe @bigbearct this can potentially be covered in the tags feature in the latest release. It will allow you tag a service / repair / upgrade record by a specific workshop and allow you to filter all records associated with that shop, as for the contact information, I believe that should live in the notes or as an attachment to the record.

**Comment by hargata** [comment]
Added the ability to add custom fields to records today, watch: https://www.youtube.com/watch?v=FIlo9Q6eQBo

Will be closing this ticket.
