### ISSUE TITLE
[Feature Request] Attachments related to Supplies

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#430]
I enjoy the feature where you can add the supplies directly to the Service Records inputs.  Very helpful in tracking costs and supplies both.  However, there is currently not a way to download the supplies attachments.

I think it'd be nice if when you utilize supplies for a service order (or any other repair/upgrade for that matter), the system should auto assign the attachments for the supplies related to that service record/repair/upgrade and be included in the respective attachment for that record.  I don't add attachments to my service records related to the parts used so this would fill that gap.

**Comment by hargata** [comment]
Need some clarification on this, do you mean that when you utilize a supply on a new service/repair/upgrade record the attachments for that supply will automatically be copied over to the new service/repair/upgrade record?

**Comment by Hawkins1212** [comment]
THats correct.  For an example I can think of, Pennzoil has a 300k warranty program with their product.  If you ever have a claim, they require all receipts for oil changes.  When I perform an oil change, I don't put any documentation under the "Service Record" however, I keep my documentation attached to the Supplies.  If I ever needed to pull the attachments for the supplies related to my service records entry, there is currently no way to do that (unless I pull each PDF manually).  So recording the attachments of the supplies purchased with the Service Record in which the supply was used would be helpful for a task similar to this.

**Comment by hargata** [comment]
@Hawkins1212 Got it, in the next release, there will be a switch in the form where you select the supplies, if that is checked then it will copy over the attachments of the supplies onto the record.

![image](https://github.com/hargata/lubelog/assets/155338622/9e622592-0e6d-4136-9cf1-698a56d247ed)

**Comment by Hawkins1212** [comment]
Oh that is Excellent!  I love that!!

Also one other comment, is there a way to sort the columns of the reminders?  For example mine look like this but would be good if they show up in order:
![image](https://github.com/hargata/lubelog/assets/87832357/7eb088b2-c1de-4f8a-bf14-4794a6db6b35)

**Comment by hargata** [comment]
@Hawkins1212 currently the reminders are only sorted in descending order by their urgency, Past Due / Very Urgent reminders will show up at the very top.

The challenge with making it sort by the Metric is that the Mileage field can display either a date, an odometer reading, or "Both", so I don't think it's super feasible in the meantime, might change in the future if I re-design the reminders tab.

**Comment by hargata** [comment]
@Hawkins1212 released in 1.2.9
