### ISSUE TITLE
[Feature Request] Reminder Tags or Grouping

### ISSUE THREAD

**Issue by joshtbernstein** [hargata/lubelog#434]
This is awesome and what I've been looking for!

Would it be possible to please add tags to reminders? I'd like to group them by service interval (Inspection I, Inspection II, Standard Oil Change). Not sure if there's a better way to accomplish this.

**Comment by joshtbernstein** [comment]
Sorry to keep opening and closing this. I wasn't sure this would accomplish what I want, but I think it's worth a try.

**Comment by hargata** [comment]
Released in 1.2.9
