### ISSUE TITLE
Add recurring reminder from service does not pull miles/date

### ISSUE THREAD

**Issue by huskerluke13** [hargata/lubelog#439]
When you load a new service record, such as oil change, and select the add reminder the reminder pop-up comes up, the miles are not loaded from that service record when you select recurring.  When you select the recurring in the reminder it should update the date and miles to the service record miles/date + recurring miles/month.

Example: 
Service Record Date: 2/6/2024
Service Record Odom: 6540

Recurring Reminder
Recurring Time: 6 Months
Recurring Odom: 5000

Reminder Date: 8/6/2024
Reminder Odom: 11540

Minor formatting gripe: can the recurring "Month" be updated to "Time Interval" or something as there are years available for selection.

**Comment by hargata** [comment]
Good idea since not most people don't perform the service on the dot, this will be released 03/29/2024 in 1.2.9

**Comment by hargata** [comment]
Released in 1.2.9
