### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by hargata** [hargata/lubelog#448]
Implement a Global Search function search through Plans/Service/Repair/Upgrade/Tax records for a specific keyword in the Description, Tags, and Notes field.

The search results should include the following:

Type of Record and Description i.e.:

`Service Record - Oil Change`

Clicking on the search result will bring up the record.

**Comment by jfdid** [comment]
Awesome!

**Comment by jfdid** [comment]
@hargata Per your question, yes the Description/Tags/Notes fields should be adequate, at least for now.  Thanks very much for looking into this.  Love the project.

**Comment by hargata** [comment]
@jfdid Released in 1.3.0

Watch: https://youtu.be/qyiYu1_XkGk?si=kK8s4KUeuK1P_a9n&t=35
