### ISSUE TITLE
[Feature Request] Make Vehicle Notes similar to the Service and Repair sections.

### ISSUE THREAD

**Issue by plumpo** [hargata/lubelog#45]
Would love to have the Main Notes section mimic the style of the other data entry fields. I don't know how much work that would be, but would make it easier/faster to find the notes you're looking for and less chance of me accidently deleting the rest of my notes for the vehicle. 

Would like to just go to my Tire Sizing notes or my Immobilizer Pin code.  Just a QOL thing. 

Thanks for the work and sorry I lack the skill set to contribute, but If I'm ever looking to move to Utah I will give Price a look.

**Comment by hargata** [comment]
It's not that big of a change and can probably be implemented pretty quickly.

**Comment by hargata** [comment]
@plumpo this is completed. Please test.

**Comment by plumpo** [comment]
Thanks for the quick work! 

Only note would be maybe to have a limit to how much of the note is shown in the UI. (Or maybe don't show any of the actual note past the title?) I dumped a ton of text to see and it pushes the rest of the notes off the side of the page and you have to scroll to the right to see the end.

**Comment by hargata** [comment]
@plumpo my bad, just fixed it, can you test again?

**Comment by plumpo** [comment]
@hargata that works great! Thanks again!

**Comment by hargata** [comment]
Thank you!
