### ISSUE TITLE
[feature] set default values to (mandatory) field like cost in service + add a contract function + add insurance

### ISSUE THREAD

**Issue by chris1284** [hargata/lubelog#455]
I have a warranty and service contract. i pay 30€ / month and all services withs parts and supplies are covered.
I note all services in LubeLogger and it would be nice to have a 0,00 default value in the cost field.

for the contracts, a contract tab would be nice that books automatically every month the cost on due date.
this could also cover insurance contracts and other contracts like leasing

**Comment by hargata** [comment]
The recurring expense feature can already be found under the Taxes tab.

**Comment by chris1284** [comment]
> The recurring expense feature can already be found under the Taxes tab.

yes, i found it. it is not optimal, that i have to create each entry for paid taxes if i have already an entry for a monthly recurring tax. better would be an automation, that creates the monthly pending entry and i have only to check "paid". this, combined with an auto reminder creation would be great. for example i have a monthly insurance and created an entry starting 01.01.2023 with monthly recurring set. there is only one entry, but i have already payed the last 15 month.

**Comment by hargata** [comment]
@chris1284 I'm sorry, but that is beyond the scope of this app. LubeLogger is not a financial/budgeting app, when a record is created in Service/Repair/Upgrade/Fuel/Tax tabs, it is assumed that the record is created retroactively _after_ the event has already happened(i.e. you've already paid/performed the activity). Regardless, there is an API endpoint for LubeLogger that you can utilize to create the tax records, perhaps integrate with your financial/budgeting app to automatically create those records when you've paid them.

Regarding the previously paid taxes, you can either again utilize the API endpoint to automate the creation of those records or create them in a CSV file and import them into LubeLogger.

The default values however, is a reasonable request and I will take that into consideration. For now, I will close this ticket as _not planned_.

**Comment by chris1284** [comment]
@hargata Thx for the info. LubeLoggger seems to add all missing position of recurring taxes records. I have looked now, after some refreshes of browser tab and entering taxes tab, it has created all of the payments in the past automatically to this month.
that is great, but the refresh could be something for background tasks. this is important for my €/km statistics
![taxes auto created](https://github.com/hargata/lubelog/assets/16157117/099a6d76-8fe8-4cc5-a018-5cc498f1f368)

thanks for the goog tool
