### ISSUE TITLE
[feature]Reminders Tab configurable view

### ISSUE THREAD

**Issue by chris1284** [hargata/lubelog#457]
Please add more columns or ar menu do choose what to display to the Reminders Tab.
I think it is important to see next date/km and interval in the table view

**Comment by hargata** [comment]
The next date/km is displayed depending on which metric the reminder goes by.

if the reminder is based on odometer, the metric column will display the next odometer reading for which it is due.
if the reminder is based on date, then it will display the next date for which it is due.

if the reminder goes by both odometer and date(whichever comes first), then it will display "Both" if the reminder is in "Not Urgent" status, but once it goes to "Urgent", it will display the metric which comes first.

i.e.: If I have a reminder that looks like this:

![image](https://github.com/hargata/lubelog/assets/155338622/2775855b-5cde-46a4-b7d3-a09b432d43e5)

it will say "Both" in the metric:
![image](https://github.com/hargata/lubelog/assets/155338622/47c3e5f2-60c9-4f6d-ad80-a8dd08a9fa2b)

if I add a new odometer record 224999, then now there's only 1 mile before it is due at 225000, so it will now display the odometer reading in the metric column:
![image](https://github.com/hargata/lubelog/assets/155338622/5ebfc053-fa8d-4afd-a005-b1486ba69b0b)
