### ISSUE TITLE
[Bug] Cost of gas refuled is a number field

### ISSUE THREAD

**Issue by TheBinaryLoop** [hargata/lubelog#46]
The cost of gas refuled field is of type number. This prevents someone with a non-english locale ex. german to type the price correctly. It should be a text field like the Amount of gas refuled field. If you manually change the type from number to text it works correctly. 30,11 will be saved as 30,110€

**Comment by hargata** [comment]
I currently cannot find a good long term solution for this, but let me try a few things and I'll get back to you in a few.

**Comment by hargata** [comment]
@TheBinaryLoop this is now fixed please test :)

**Comment by hargata** [comment]
Solved alongside with #50

**Comment by TheBinaryLoop** [comment]
Works perfectly. Thx
