### ISSUE TITLE
Oauth Cookie Invalid

### ISSUE THREAD

**Issue by Tunatron** [hargata/lubelog#468]
I setup Oauth using Authentik as my provider following the docs - and it works as expected initially.
After some time, I'm assuming after a token expires, Lubelogger won't load using my domain, and eventually shows bad gateway.

Lubelogger's log shows: 

CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Cookie is invalid or does not exist.

If I restart Authentik, the domain is accessible again and I can login using Oauth again - but the problem will repeat itself.

**Comment by hargata** [comment]
I believe this is a problem with Authentik itself and not LubeLogger.

With the way OIDC works, LubeLogger doesn't "load" your domain, it redirects your browser to your instance of Authentik with a redirect url. 

If you're getting a Bad Gateway error when you click the Login via OpenID button, it will appear that you have a misconfiguration on your Authentik instance instead.

**Comment by Tunatron** [comment]
Just wanted to add a note in case anyone has the same issue  -  using Authentik's local address (containername:9000) as the Token URL in Lubelogger's variables, instead of auth.domain.com seems to have resolve this issue for me.

**Comment by KoMa1012** [comment]
> Just wanted to add a note in case anyone has the same issue - using Authentik's local address (containername:9000) as the Token URL in Lubelogger's variables, instead of auth.domain.com seems to have resolve this issue for me.

I can't get it running at all, do you mind sharing your authentik and lubelogger config? As soon as I click the login with authentik button it pop up authentik and then send me back to lubelogger login page, rinse and repeat... I checked the log which says:
`info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Cookie is invalid or does not exist.`
