### ISSUE TITLE
[Feature Request] Locales

### ISSUE THREAD

**Issue by feuertaenzer** [hargata/lubelog#476]
Hey there,
I started using this app in February and I am super amazed even by the progress I have seen in this short amount of time!
We are currently trying to track all of our "extended family" vehicles with this and since we are from Germany, we use Lubelogger with the German translation(which has drastically improved lately!) but some aspects seem to be missing which is all related to what I consider the locale:

- The date format is American(M/D/YYYY) but I'd like to be able to switch it to German(DD.MM.YYYY)
- The decimal separator is a dot and I'd like to be able switch to a comma which is the typical decimal separator for Germany
- The currency symbol still states $ and I'd like to be able to switch to €

It's not part of the translation and I haven't seen environment variables for this, so if this feature already exists please point me in the right direction.

If it doesn't exist yet consider this a low priority feature request: I'd love to be able to change the locale to German or have a config file like for the language to customize these aspects

**Comment by hargata** [comment]
Locale is configured via the .env file via the environment variables LC_ALL and LANG
