### ISSUE TITLE
Links do not change color in light mode on demo site

### ISSUE THREAD

**Issue by nichwall** [hargata/lubelog#479]
**Checklist**

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
Links on the demo site use white text in light mode. The links remain as white text in dark mode, so they are readable in dark mode. Have not installed myself yet, so not sure if this also exists in normal installs.

**Screenshots(optional)**
![Light Mode](https://github.com/hargata/lubelog/assets/5686638/0c6ddce5-eb47-437e-9401-36167774e4a2)

![Dark Mode](https://github.com/hargata/lubelog/assets/5686638/6fd1ddaf-7fca-448b-b4d3-1a54850368a0)

**Comment by hargata** [comment]
Fixed and released in 1.3.1, thanks!
