### ISSUE TITLE
no auto redirect to OIDC login

### ISSUE THREAD

**Issue by KoMa1012** [hargata/lubelog#481]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
going to lubelogger.domain.tld shows the login website eventhough OpenIDConfig__DisableRegularLogin environmental variable is set to true

**expectation**
Lube Logger is forwarding to the OIDC login website not asking for any login information

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
none

**App/Container Console Error**
```
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Cookie is invalid or does not exist.
```

**Comment by hargata** [comment]
did you provide a LogOutURL? 

https://docs.lubelogger.com/OpenID

**Comment by KoMa1012** [comment]
Didn’t expect this to be related. Fixed it, thank you!
