### ISSUE TITLE
[FeatureRequest] Allow Admin user to log in via OIDC

### ISSUE THREAD

**Issue by KoMa1012** [hargata/lubelog#482]
The first created User (aka admin user) can not log in using OIDC. I'm using my own SSO System (authentik) where I've got an extra admin user which has admin right for all services since I don't want my normal user to have admin rights.

I can create another account and give him admin rights, so I'd say this is not a high priority task in my opinion.

**Comment by auntphil** [comment]
Didn't realize this! I have been fighting with Authentik. I added a second user but still Authentik didn't work. Did you do anything special to get your OIDC working?

**Comment by MiguelNdeCarvalho** [comment]
Waiting for this feauture too :+1:

**Comment by hargata** [comment]
On next release, there will be a field named "Default Reminder Email" and a check for "Enable OIDC for Root User"

If enabled and the Default Reminder Email field is not blank, any user logging in from the OIDC provider with the same email will be granted root access.

![image](https://github.com/user-attachments/assets/c495e4bf-13e2-4e2e-966e-4c6314dbc683)

**Comment by hargata** [comment]
This is now released.
