### ISSUE TITLE
[Feature Request] VIN/Serial Number Field for Vehicles (Besides Custom Fields)

### ISSUE THREAD

**Issue by CivisMiles** [hargata/lubelog#485]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
Request to add a VIN/Serial Number Number Field for Vehicles. I know you can make a custom field for this but doing so does not show it on the Garage Homepage nor exempt you from entering a License Plate in the case of Mowers, ATVs, Tractors, Etc. Yes, you can enter it in the license plate field, but what if you want to enter both the VIN and the License for a car.

What I see it being is when editing/creating a vehicle there is two fields, one for the license plate and one for the VIN/Serial. It is mandatory to fill out one of the fields but doesn't give you an error when leaving the other blank, and if you enter both, you can select which one displays on the Garage Home page.

**Screenshots(optional)**
![image](https://github.com/hargata/lubelog/assets/7795937/d6cab6f7-abb0-4a87-af74-c82fd4223045)
![image](https://github.com/hargata/lubelog/assets/7795937/a1f88807-dd70-4526-aae4-1e249b06d33c)

**Comment by hargata** [comment]
I will do you one better.

In the next release, there will be a dropdown that will let you select which field should be the identifier, you can choose from "License Plate" and any other extra fields you have set up.

![image](https://github.com/user-attachments/assets/87ebfa0d-78f2-4508-b4ea-743e8659eb9a)

If you select any field other than "License Plate" then the License Plate will be optional, BUT the selected field must not be emtpy.

![image](https://github.com/user-attachments/assets/548eba26-c99c-4eb7-a46e-7686298bbb88)

If license plate is selected and VIN is not a required extra field

![image](https://github.com/user-attachments/assets/55da634b-f240-4879-b474-2b1042474953)

If license plate is selected and VIN is a required extra field

![image](https://github.com/user-attachments/assets/a8329e60-41b9-49e2-8b91-f366396f8bbd)

Anyways, once you have selected the field you want displayed, then it will display the value of that field everywhere license plate used to be displayed:

Garage:

![image](https://github.com/user-attachments/assets/7eab1a13-8005-48de-98e4-c40e039e3506)

Vehicle View:

![image](https://github.com/user-attachments/assets/9f8bdbdd-bc37-4215-a0fb-a9382268f73f)

Calendar:

![image](https://github.com/user-attachments/assets/349ae26b-4ca4-4997-8a5d-18b4a42b89d0)

**Comment by hargata** [comment]
Released.

**Comment by wkosmos** [comment]
Is this definitely done? I don't see this feature in the most recent windows version at all

**Comment by hargata** [comment]
@wkosmos it is, you need to have an extra field at the vehicle level for this to work
