### ISSUE TITLE
[Feature Request] Metrics selection should persist after a refresh

### ISSUE THREAD

**Issue by jstebenne** [hargata/lubelog#491]
Right now, when you select metrics in the vehicle dashboard, the selection is not persisted so after a page refresh it is reset to the full selection.

It would be nice if the previous selection is saved somewhere (probably the browser's session storage).

**Comment by jstebenne** [comment]
Actually, it would be interesting if I tried implementing this (web dev is where I spend most of my time). Do you have documentation somewhere on project setup? I think I can squeeze some time during the next week to implement this.

**Comment by hargata** [comment]
available in edge tagged docker image.

**Comment by hargata** [comment]
Released in 1.3.1
