### ISSUE TITLE
[Feature Request] Ability to change date format from month/day/year to day/month/year etc 

### ISSUE THREAD

**Issue by lennon101** [hargata/lubelog#494]
I'm in Australia and month/day/year is illogical for us (as it would be for many countries). It would be great if there was a way to change how the date was entered and displayed. The `month/day/year` date format is really only used in the United States, The vast majority of the world, including most of Europe, Asia, Africa, and South America, uses the day/month/year or year/month/day format. So, in terms of a global percentage, the month/day/year format is used by a relatively small fraction of the world's population. 

Screenshot of date format for reference: 

![image](https://github.com/hargata/lubelog/assets/1709944/fcc260cf-0ab4-4fff-a1a2-e1368601dbca)

**Comment by hargata** [comment]
duplicate, see #476
