### ISSUE TITLE
[Feature Request] Purchase cost of vehicle

### ISSUE THREAD

**Issue by boolsmith** [hargata/lubelog#495]
Thanks for making such a cool project! I was wondering if it would be possible to add a line item for purchase cost of the vehicle. I am interested in tracking both the cost/mile of a vehicle maintenance, and total cost per mile. Feel free to tell me this is out of scope for the project.

**Comment by hargata** [comment]
@boolsmith thanks for reaching out, this feature already exists under the Purchase/Sold Information section:

![image](https://github.com/hargata/lubelog/assets/155338622/ad01c5cc-c517-439f-8539-49dd998a919b)


For cost/per mile, you will need to input at least a Purchase date, Purchase cost and Sold cost, if your vehicle is not sold, you can temporarily input the current market value of the vehicle, this will allow you to calculate the depreciation cost. The cost per mile and depreciation per mile will then be visible in the Vehicle Maintenance History:


![image](https://github.com/hargata/lubelog/assets/155338622/ebb4d5b1-c0f7-4b31-b291-3c73dd79a2a6)
