### ISSUE TITLE
IP Binding

### ISSUE THREAD

**Issue by ParadoxLeon** [hargata/lubelog#497]
Hi, 
Is there a option for setting the IP somewhere?
So I can set `10.10.10.11` instead of `localhost`

**Comment by hargata** [comment]
I'm assuming this is for the Windows standalone, if so, read this:
https://docs.lubelogger.com/Troubleshooting#cant-access-lubelogger-instance-from-other-devices

If you're running the Docker container then you can just bind an IP address like any other Docker containers.

**Comment by nathanaelmoyer** [comment]
Hello!

I'm wondering the same thing. I can't access it outside of localhost. I followed the above mentioned troubleshooting guide but I can't seem to get the syntax correct. At which line are we supposed to add the "Kestrel" section?

This is the section of code I believe I need to add to the appsettings.json:
```
"Kestrel": {
   "Endpoints": {
     "Http": {
       "Url": "http://10.0.0.4:5000"
     },
     "Https": {
       "Url": "https://10.0.0.4:5011"
     },
}
```


Here is my current appsettings.json:
![image](https://github.com/hargata/lubelog/assets/36149055/102aa1f7-4c21-4e5b-95dd-276f5e7d9a5a)

Thanks!!

**Comment by nathanaelmoyer** [comment]
That worked! Thanks so much!!
