### ISSUE TITLE
[Bug] Unable to specify cost with decimal places in any category

### ISSUE THREAD

**Issue by C4ArtZ** [hargata/lubelog#50]
When adding a new record to any of the categories (Service Records, Repairs, Upgrades, Fuel, Taxes), decimal separators "." and "," get stripped from the input and get replaced with ",00".

Browser console and Container logs show no errors.

## Expected Behavior
Cost should be saved with cents in decimal places. The input "572,69" should result in the same value being displayed in the table.

Input: 
![Screenshot 2024-01-10 102437](https://github.com/hargata/lubelog/assets/30392717/efbb31a4-79ea-4c9b-aba0-7c35d77a2592)

Expected Output (Modified HTML as an example):
![Screenshot 2024-01-10 104417](https://github.com/hargata/lubelog/assets/30392717/240f96e0-fa1b-4b83-a949-d9f2afb0baf4)

## Current Behavior
"," and "." get removed from the input and "00" is added as the decimal places. So the input "572,69" becomes "57.269,00".

Input:
![Screenshot 2024-01-10 102437](https://github.com/hargata/lubelog/assets/30392717/2451f1c6-0b2a-4ac2-b4de-5f5d963c750c)

Output
![Screenshot 2024-01-10 102450](https://github.com/hargata/lubelog/assets/30392717/849b53a5-51a9-4bc2-8496-f87ccecfaf42)

## Steps to Reproduce
1. Add new vehicle.
2. Add a new record in any category.
3. Specify a Cost with decimal places.

## Environment
Docker Container running on Unraid 6.12.6 with Docker Engine 20.10.24.
Container version is the latest released 4 hours ago as of writing this issue.

**Comment by C4ArtZ** [comment]
I think the issue lies within the localization.

In the instance used above I had the variables LC_ALL and LANG set to "de_DE.UTF-8".
I have now created a new instance where the variables are set to "en_US.UTF-8".

The same input of "572,69" now results in "$ 572.69".
Changing LC_ALL back to "de_DE.UTF-8" displays the cost correctly as "572,69 €". New values however still have the issue.

So there seems to be a bug with saving new values when LC_ALL is not set to "en_US.UTF-8".

**Comment by hargata** [comment]
hey, this is actually related to #46 
It's actually not a problem with the locale of the app, but rather a problem with the HTML spec which calls for numbers to only be decimated by ".". So the JS input allows you to enter "," as decimal, the C# backend allows you to pass in a number separated by ",", BUT when .val() is called on the component the decimal is reverted back to "." which the C# backend(which runs on your locale) no longer recognizes.

I have implemented a workaround for this by converting it to type="text" and implementing some strict validation on all "Costs" field across the board. You are now capped at "999,999.999" for US locales and "999.999,999" for EU locales.

This is available to test now.

**Comment by C4ArtZ** [comment]
Thanks for the clarification.

The fix works on a new instance that was created with de_DE.UTF-8 but not on an instance that was created with en_US.UTF-8 and then changed to de_DE.UTF8.

The latter resulting in the following error in the Browser console:
![Screenshot 2024-01-10 155519](https://github.com/hargata/lubelog/assets/30392717/548d2e63-cb47-4bcb-b0f4-ea2261c228d1)

Both were updated / created with the newest release.

I don't have much data in the existing instance, so recreating it isn't an issue for me. It might be something you want to look into or just mark as a breaking change.

**Comment by hargata** [comment]
@C4ArtZ That's not a bug, your browser might have cached the older version of the JS file which doesn't have the isValidMoney function. In that case, clearing your cache should make it work.

**Comment by C4ArtZ** [comment]
Ah, you're right. Clearing the cache fixed the issue. 

This issue can be closed then. Thank you for the quick help!
