### ISSUE TITLE
SMTP not working with Proton Mail

### ISSUE THREAD

**Issue by Cyberlytical-LLC** [hargata/lubelog#500]
As the title states I am having issues getting SMTP to work through ProtonMail. I have tried every combination of ssl on/off and ports. Sometimes I get an error other times no error but I don't receive the emails. Nothing is showing in the logs either so I can;t pin point exactly what is wrong. 

Any help is much appreciated. 

Thank you

**Comment by hargata** [comment]
Sorry I don't have a way to test this out as ProtonMail SMTP is only available to their business users. Maybe someone else can chime in on this.

**Comment by Cyberlytical-LLC** [comment]
No worries! I appreciate you getting back so quickly

**Comment by Cyberlytical-LLC** [comment]
If needed I can always provide a test account with an app password for proton mail

**Comment by hargata** [comment]
@Cyberlytical-LLC that works, shoot me an email over at hargatasoftworks@gmail.com

**Comment by hargata** [comment]
@Cyberlytical-LLC I have tested with the credentials you sent me. You're right, the problem lies with the SMTP Client provided by .NET not supporting the security protocols used by ProtonMail. I'm looking at third party implementations and have found one that will work with ProtonMail, but that will require a lot of testing before I can release it.

**Comment by Cyberlytical-LLC** [comment]
Hey no worries! I am glad you found the issue. I am happy to run a beta build if you'd like me to test it as well.

**Comment by hargata** [comment]
@Cyberlytical-LLC try the :edge tagged docker image

**Comment by Cyberlytical-LLC** [comment]
Okay so I did "sudo docker compose down --rmi all" then "sudo docker pull ghcr.io/hargata/lubelogger:edge" and changed the .env file to the proton info. Is that all I should need to do?

**Comment by hargata** [comment]
yeap

**Comment by Cyberlytical-LLC** [comment]
I'm still getting an error. 
`LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
MailConfig__EmailServer="smtp.protonmail.ch"
MailConfig__EmailFrom="email@cyberlytical.org"
MailConfig__UseSSL="true"
MailConfig__Port=587
MailConfig__Username="email@cyberlytical.org"
MailConfig__Password="app password"
LOGGING__LOGLEVEL__DEFAULT=Error
`
Are these the settings you used?

**Comment by Cyberlytical-LLC** [comment]
Also what is the best way to test notifications for odometer and such? I'm not getting any emails from the gmail setup or proton. Only getting the registration emails from the gmail config.

**Comment by hargata** [comment]
@Cyberlytical-LLC you need to update docker-compose.yml file to point at the edge tag
can you explain what you mean by notifications for odometer?

**Comment by Cyberlytical-LLC** [comment]
That worked! Thank you so much for getting this done so quickly. 

I wanted to test reminders so I set s notification to notify me today and one when my odometer hit "10" I saved the reminders then changed my odometer to 10 but never received a notification.

I sent you a donation for all your help and being so kinda. Loving the app so far!

**Comment by hargata** [comment]
@Cyberlytical-LLC Thanks for the donation!

As for the reminder emails, you will need to set up a cron job to run a curl command, see [example](https://github.com/hargata/lubelog_scripts/blob/main/bash/sendreminders.sh)

This will send collaborators an email detailing the vehicle and the urgency of the reminder based on the interval of the cron job:

It looks like this:

![image](https://github.com/hargata/lubelog/assets/155338622/ba58675a-171f-4e4b-ac48-fb8baab8dcc8)

**Comment by Cyberlytical-LLC** [comment]
@hargata Hmm okay. I tried running the command with the root user and a sudo user with no luck. I also added it to cron and made a executable script file and it's none of the things I try are seeming to work. I don't have logs so I'm curious what is wrong.

**Comment by hargata** [comment]
@Cyberlytical-LLC does the curl command return any errors at all?

**Comment by Cyberlytical-LLC** [comment]
@hargata it doesn't as far as I can tell it's working, just never receive an email.  Could it be something with HA proxy?

**Comment by Cyberlytical-LLC** [comment]
So I changed the url to http://10.10.5.11:8080/api/vehicle/reminders/send?urgencies=NotUrgent&urgencies=VeryUrgent&urgencies=Urgent&urgencies=PastDue with no luck. In the browser I can hit /api but not the sting provided.

**Comment by Cyberlytical-LLC** [comment]
![image](https://github.com/hargata/lubelog/assets/108770346/97c6d1ef-a64b-4c53-b52d-11ef3ab1d358)
I get this when I do https://mydomain.com/api/vehicle/reminders

**Comment by hargata** [comment]
@Cyberlytical-LLC what happens when you run `curl -n -u "rootUser:rootPassword" --location "https://lubelogger.mydomain.com/api/vehicles"`

**Comment by Cyberlytical-LLC** [comment]
Curl command seems to work, but still no email.

**Comment by hargata** [comment]
@Cyberlytical-LLC Just to confirm, you have a vehicle set up along with a reminder, and you also have a user that is added as a collaborator on that vehicle, is that correct?

**Comment by Cyberlytical-LLC** [comment]
Correct. Below are screenshots of the setup 
![image](https://github.com/hargata/lubelog/assets/108770346/417b4f68-328e-4803-a4fc-aea4b2d5cc8f)
![image](https://github.com/hargata/lubelog/assets/108770346/6227af88-5f0b-470c-8ec1-62032f6ca3c5)
![image](https://github.com/hargata/lubelog/assets/108770346/7f17f67c-34e6-40bf-a880-a9a89bde9aee)
![image](https://github.com/hargata/lubelog/assets/108770346/83268eea-32eb-4105-8867-d4d2ec4c0bc9)

**Comment by hargata** [comment]
Can you change the reminder metric on the test reminder so that it is in "Urgent" or "Not Urgent" status and see if that works? Some email inboxes will flag emails with the wording "Very Urgent" in it so it might not get delivered

**Comment by Cyberlytical-LLC** [comment]
No luck :/

**Comment by Cyberlytical-LLC** [comment]
I changed my proxy config to allow X-forward-for and now I can reach https://lubelog.cyberlytical.org/api/vehicle/reminders but get that error page again.

**Comment by hargata** [comment]
can you check the Outbox/Sent of the SMTP account and see if it actually sent those emails out?

do `https://lubelog.cyberlytical.org/api/vehicle/reminders?vehicleId=1` that endpoint requires a vehicleId param

**Comment by Cyberlytical-LLC** [comment]
No emails being sent. That works I can see the reminders in the browser

**Comment by hargata** [comment]
@Cyberlytical-LLC kk now try `https://lubelog.cyberlytical.org/api/vehicle/reminders/send?urgencies=NotUrgent`

**Comment by Cyberlytical-LLC** [comment]
I just get a blank page
![image](https://github.com/hargata/lubelog/assets/108770346/35cd550b-2cb8-47e1-b347-34795fb9e41a)

**Comment by hargata** [comment]
@Cyberlytical-LLC are you logged in as the root user?

**Comment by Cyberlytical-LLC** [comment]
OMG I am an idiot. However after changing it to those credentials still no luck. Could it be the randomly generate password with all the symbols in it?

**Comment by hargata** [comment]
@Cyberlytical-LLC does it have a ":" in it?

**Comment by Cyberlytical-LLC** [comment]
Nope just a few "@" "#"

**Comment by hargata** [comment]
can you send a screenshot of what you're seeing when you navigate to `https://lubelog.cyberlytical.org/api/vehicle/reminders/send?urgencies=NotUrgent` while logged in as the root user?

**Comment by Cyberlytical-LLC** [comment]
Right after I typed this into my browser all the emails sent,
![image](https://github.com/hargata/lubelog/assets/108770346/473f9e56-8a94-4b44-aeac-152868179391)

**Comment by hargata** [comment]
@Cyberlytical-LLC sweet, does the curl command work? If it doesn't I'm assuming the special characters in the password must've tripped it somehow.

**Comment by Cyberlytical-LLC** [comment]
The command doesn't seem to be working. Whenever I go to the url after changing the urgencies it works though. Is there a way to change the root password?

**Comment by hargata** [comment]
yeah, see #489

**Comment by Cyberlytical-LLC** [comment]
Awesome you've helped tremendously! Thank you so much for getting me setup!

**Comment by hargata** [comment]
No problem!

**Comment by ads103** [comment]
> @Cyberlytical-LLC I have tested with the credentials you sent me. You're right, the problem lies with the SMTP Client provided by .NET not supporting the security protocols used by ProtonMail. I'm looking at third party implementations and have found one that will work with ProtonMail, but that will require a lot of testing before I can release it.

I'm running into the same issue today. I'm hosting a local instance of protonbridge on an Unraid server (per [this](https://hagensieker.com/2021/11/18/protonmail-bridge-on-unraid/) guide), and when LubeLogger v1.4.0 tries to send an email, I see this in the logs:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.
      
      The host name (10.1.1.24) did not match the name given in the server's SSL certificate (127.0.0.1).
      
       ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
         at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
         at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
         at MailKit.Net.Smtp.SmtpClient.SslHandshake(SslStream ssl, String host, CancellationToken cancellationToken)
         at MailKit.Net.Smtp.SmtpClient.PostConnect(Stream stream, String host, Int32 port, SecureSocketOptions options, Boolean starttls, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
```

Just as Cyberlytical-LLC concluded, I don't think my instance of LubeLogger is using STARTTLS. Does 1.4.0 have a setting where I can configure STARTTLS?

**Comment by hargata** [comment]
@ads103 nah, that issue was long resolved, absolutely nothing to do with what you're seeing on your end.

LubeLogger uses MailKit in order to send the email out, MailKit automatically determines if STARTTLS should be used based on the port number. Based on the logs, a TLS connection is attempted, but was rejected because of a SSL certificate error, you need to first resolve the host name issue in your SSL Certificate.

**Comment by ads103** [comment]
Okay. That brings up two questions. 

Firstly, is there a way to convince MailKit to ignore best practices and ignore the certificate error? This instance of the Protonmail bridge is kinda... janky - the bridge bonds to localhost and relies on socat to forward mail from the Ethernet interface to localhost. So the TLS cert is always for localhost. If you'd like to see additional information regarding this setup, you can see it [here](https://github.com/shenxn/protonmail-bridge-docker).

Secondly, is there a way to override the determination MailKit makes regarding automatic authentication determination? My Protonmail bridge is configured to use port 25 for SMTP, but it only support starttls authentication. I wonder if MailKit might be trying to use TLS because of port 25, which the bridge doesn't support.

**Comment by hargata** [comment]
@ads103 I'm sorry, but I'm not sure how it'd be able to support your nonstandard configuration. MailKit has an option to disable TLS connections, but if Protonmail  is expecting a TLS connection after the bridge then I'm not sure how TLS  would be re-enabled at that point.

This seems more of an issue with your setup than an issue with the software.

**Comment by ads103** [comment]
I'm sorry, I don't think I've been clear. Protonmail _isn't_ expecting a TLS connection - its expecting starttls. Other users, [as seen here](https://www.reddit.com/r/Bitwarden/comments/o0plbk/comment/ijtpcvk), are having to explicitly disable SSL, explicitly enable starttls, and explicitly enforce trusting of the email server. 

You may be right - this may be an issue with my setup. But since you said, "MailKit automatically determines if STARTTLS should be used based on the port number," and since I'm using port 25 to reach my SMTP bridge, my concern is that MailKit _isn't_ automatically selecting STARTTLS.
