### ISSUE TITLE
[Bug] Adding Fuel Records Out of Order Breaks Odometer Updates

### ISSUE THREAD

**Issue by jdh313** [hargata/lubelog#509]
**Checklist**
- [ x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [ x] I have searched through existing issues.

**Description**
When adding fuel logs out of order, the odometer does not calculate off of the correct previous entry. In this case I added the 5/1 and then the 4/27 upload. On the "Fuel" page it's correctly calculated but on the "Odometer" page it is not.

This is on version 0.30.0, however I did not see anything in the change logs that suggest a fix in the newer versions.

**Platform**
- [x ] Docker Image
- [ ] Windows Standalone Executable

**Screenshots(optional)**
![CleanShot 2024-05-04 at 13 32 17@2x](https://github.com/hargata/lubelog/assets/13279035/a129bd56-3643-4cf0-aa35-8ccf6c683357)
![CleanShot 2024-05-04 at 13 32 00@2x](https://github.com/hargata/lubelog/assets/13279035/bd9598a9-a1b5-4eef-882e-0c496251e10f)

**Comment by hargata** [comment]
https://docs.lubelogger.com/Records/Odometer#negative-distance-values
