### ISSUE TITLE
[Feature request]  The recurrence fields should be modeled on those defined for triggering.

### ISSUE THREAD

**Issue by xavier-GitHub76** [hargata/lubelog#512]
Hello,

I discovered LubeLogger, thank you for this application which allows me to delete my unsuitable spreadsheet.

When creating a reminder, it is possible to set a trigger based on :
- a date or
- a mileage or 
- both

It is also possible to define a recurrence but the user does not have the choice of the recurrence condition.

Both fields are mandatory, the user must define both fields when only one is probably useful.

This requires entering an improbable value for the unnecessary field.

The recurrence fields should be modeled on those defined for triggering.

Best regards

**Comment by hargata** [comment]
Released in 1.3.5
