### ISSUE TITLE
Sum of costs for search result is wrong when non-US locale

### ISSUE THREAD

**Issue by lisachev** [hargata/lubelog#514]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Garage -> Service Records -> Search, input a search term that has several entries matching. The list gets 'filtered' with # of Service Records indicating the number of Service Records matching the search criteria, but the Total: next to it reflects a wrong number if the locale has a space as a thousands delimiter. ru_RU as an example.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

<img width="808" alt="image" src="https://github.com/hargata/lubelog/assets/55584280/54cdb284-f170-429c-9968-ea5592134cee">

**Comment by hargata** [comment]
Fixed in edge-tagged docker-image, will schedule a release sometime in July.

**Comment by hargata** [comment]
Released
