### ISSUE TITLE
[Localization] Some strings of the UI are not respecting the Language setting

### ISSUE THREAD

**Issue by lisachev** [hargata/lubelog#527]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

There are parts of the UI that did not make it to the language file. 
"All time"
"Metrics"
"(liters)"
"(kilometers)"

I've added screenshots of the terms that are omitted from the language json

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

![SCR-20240524-ekl](https://github.com/hargata/lubelog/assets/55584280/4452d484-5f6e-4d4e-8a53-87c2d0e49738)
![SCR-20240524-ela](https://github.com/hargata/lubelog/assets/55584280/5f18b50b-f254-4b4f-a059-31a230cde4c5)

**Comment by hargata** [comment]
Fixed in edge-tagged docker-image, will schedule a release sometime in July.

**Comment by hargata** [comment]
Released
