### ISSUE TITLE
Email not successful

### ISSUE THREAD

**Issue by vspaziani** [hargata/lubelog#528]
Hello, I cannot figure out how to get the email to work after you switched to the new SMTP. Can you please point me in the right direction?

I have my own email server hosted on another server on the same subnet as this machine. When I try to send an email, I get the same message from either the webpage or terminal running as root.

this is the error that I am getting:

> {"success":false,"message":"All emails failed, check SMTP settings"}

I have an app password for the account. I have also tried non-SSL on port 25 with null as username and password.

my .env file                                                                                                          
```
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
MailConfig__EmailServer="192.168.X.XXX"
MailConfig__EmailFrom="lubelogger@Domain.com"
MailConfig__UseSSL=true
MailConfig__Port=465
MailConfig__Username="no-reply@Domain.com"
MailConfig__Password="password"
LOGGING__LOGLEVEL__DEFAULT=debug
```

**Comment by hargata** [comment]
check console for errors.

**Comment by vspaziani** [comment]
I am not sure where to look. Currently I am running the container without the detach command ie `sudo docker compose up --force-recreate `

while it is running and I try to see an email I do not see any errors. Should I be looking somewhere else?

This is what the container says:

> [+] Running 1/1
>  ✔ Container vspaziani-app-1  Recreated                                                                                                                                                                                                  0.2s 
> Attaching to app-1
> app-1  | LubeLogger 1.3.3
> app-1  | Website: https://lubelogger.com
> app-1  | Documentation: https://docs.lubelogger.com
> app-1  | GitHub: https://github.com/hargata/lubelog
> app-1  | SMTP Configured for 192.168.XX.XXX
> app-1  | Message Of The Day: Not Configured
> app-1  | dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
> app-1  |       Hosting starting
> app-1  | info: Microsoft.Hosting.Lifetime[14]
> app-1  |       Now listening on: http://[::]:8080
> app-1  | info: Microsoft.Hosting.Lifetime[0]
> app-1  |       Application started. Press Ctrl+C to shut down.
> app-1  | info: Microsoft.Hosting.Lifetime[0]
> app-1  |       Hosting environment: Production
> app-1  | info: Microsoft.Hosting.Lifetime[0]
> app-1  |       Content root path: /App
> app-1  | dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
> app-1  |       Hosting started
> app-1  | dbug: CarCareTracker.Middleware.Authen[8]
> app-1  |       AuthenticationScheme: AuthN was successfully authenticated.
> app-1  | dbug: CarCareTracker.Middleware.Authen[8]
> app-1  |       AuthenticationScheme: AuthN was successfully authenticated.
> ^X^CGracefully stopping... (press Ctrl+C again to force)


though when I look at it now I do see that it says 
> app-1  | Website: https://lubelogger.com 

and that is not my actual website if that makes a difference, my site is HTTPS://lubelogger.domain.com

**Comment by hargata** [comment]
sorry, I don't know how to help you then.

**Comment by vspaziani** [comment]
Thanks for taking a look. I will keep trying to figure it out.

**Comment by vspaziani** [comment]
If someone does find this, I did end up figuring it out-my firewall was dropping the traffic.
