### ISSUE TITLE
Cannot choose supplies for plan if supplies have zero value

### ISSUE THREAD

**Issue by tedski** [hargata/lubelog#529]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

When choosing supplies through a Plan Record, if the supplies cost is $0, the Select button never becomes available.  The supplies have 0 value because they were obtained at no cost.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

No errors or output in console.

**App/Container Console Error**

No relevant log messages in the container logs.

**Screenshots(optional)**

Supplies selected totaling 0:
<img width="807" alt="supply screen with select disabled and supplies totaling 0 value" src="https://github.com/hargata/lubelog/assets/1806188/0a147e64-7331-4906-86ec-39a845af4a87">
Supplies selected totaling > 0:
<img width="807" alt="supply screen with select disabled and supplies totaling >0 value" src="https://github.com/hargata/lubelog/assets/1806188/024804aa-89b9-445b-a049-ed71ac09957f">

**Comment by tedski** [comment]
If total `requestedQuantity` was used in [the validation](https://github.com/hargata/lubelog/blob/0707b515aba5a9b0adaaca0182f84eab5c32d86a/Views/Vehicle/_SupplyUsage.cshtml#L134), that would fix this issue.

If there's agreement, I'll work on the change.

**Comment by hargata** [comment]
Released
