### ISSUE TITLE
[Feature Request] Add Odometer and Date columns to the Reminders tab to display the set values

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#531]
A request to add columns on Reminders to show the specified metric(s) that have been configured, rather than only having the dynamic Metric column.

It would help with planning to be able to see what is upcoming but still outside the urgency threshold.

![image](https://github.com/hargata/lubelog/assets/10135929/d429334a-ec17-4c55-9c99-9b235999305f)

**Comment by hargata** [comment]
Instead of columns I've added it as a tooltip instead:

![Screen Shot 2024-08-26 at 12 39 34 PM](https://github.com/user-attachments/assets/e4dfbf8d-d2d7-458b-8d4a-930889d6ebee)

**Comment by hargata** [comment]
Next release:
![image](https://github.com/user-attachments/assets/8308449f-a0d5-4836-9544-ea7f8e4f892d)

These columns are hidden by default and can be enabled in the dropdown:

![image](https://github.com/user-attachments/assets/c1f1a2f4-0845-47a2-a7c7-5784d6cec6b3)

**Comment by hargata** [comment]
Released.
