### ISSUE TITLE
[Feature Request] Fuel type for vehicles

### ISSUE THREAD

**Issue by diabolikal1** [hargata/lubelog#534]
Simple as it gets, just asking for a Fuel type drop down, as I have Diesel and Gas vehicles. So when you do a report, it reports that my F-250 as Gas, when it is in fact Diesel. Thanks.

**Comment by Betamax21** [comment]
I'd like to second this, having a menu that lets you select which type of fuel the vehicle is using would be great. If possible too, when you select the vehicle as being electric, if the fuel pump could be replaced with a little lightning bolt picture instead that would be a nice touch.

**Comment by BOSE-git** [comment]
Hi, I am Sumit, before asking that if i can controbute or not, let me clear my confusion.
when adding a new vehicle, i should add the fuel type(petrol, diesel or electric) dropdown there right or somewhere else? will it fix the issue?

**Comment by hargata** [comment]
Added in 1.3.6:

![image](https://github.com/user-attachments/assets/9b7c63f4-e78b-4947-bc34-2ec9d70ce66c)

![image](https://github.com/user-attachments/assets/a6937165-9cc1-4bf5-8c8a-157b7e00cd33)
