### ISSUE TITLE
[Feature Request] Add odometer entry from all entries to the "Odometer" section

### ISSUE THREAD

**Issue by Uncanny5180** [hargata/lubelog#543]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [ NA] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [ X] I have searched through existing issues.

**Description**
I dont believe I saw any other related issues, but I think this might be helpful to have a cumulative running total for all odometer entries in the odometer section. Hopefully that comes through as it is in my head. What I am saying is that if you have an 'upgrade' or a 'service' entry that you put in an odometer reading for, I'd like to see them ALL come over to the odometer section. That way, if you forget to do manual entries in the odometer section, the entries are already carried over from other sections. That way there is never a massive 'gap' in readings. Make sense, and does this seem like it might be helpful? 

**Platform**
- [X ] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

**Comment by hargata** [comment]
There is an option in the settings page called "Auto Insert Odometer Records" that automates an odometer insert when a new entry is created in service record/repair/upgrades/fuel.

**Comment by Uncanny5180** [comment]
> There is an option in the settings page called "Auto Insert Odometer Records" that automates an odometer insert when a new entry is created in service record/repair/upgrades/fuel.

Dang you are ALWAYS a step ahead.....rescinded.
