### ISSUE TITLE
Is there a way of resetting the admin password if deployed as Docker?

### ISSUE THREAD

**Issue by dascgit** [hargata/lubelog#544]
Hi!

I have deployed lubelog as Dockercontainer with this docker-compose file (https://raw.githubusercontent.com/hargata/lubelog/main/docker-compose.yml). Is there a way of resetting the admin password via console?
The forget password function can not be used here because I do not have SMTP configured and I do not have a SMTP Server which I can use.

**Comment by hargata** [comment]
yeap.

1. Generate a SHA256 Hash of new admin password
2. In container, navigate to /config/userConfig.json and open it using a text editor
3. Look for variable UserPasswordHash and replace the value with the SHA256 hash of new admin password.
4. The admin password has been reset.
