### ISSUE TITLE
Not able to map "ExtraFields" property values while importing via CSV 

### ISSUE THREAD

**Issue by zibbonkhadka** [hargata/lubelog#545]
- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

I am unable to map "ExtraFields" property values while importing via CSV. In the VehicleController class at line 514, I found that the ExtraFields property is not mapped to any records. Am I overlooking something, or is that intentional? How can I map ExtraFields properties using CSV?

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Screenshots(optional)**

![Screenshot 2024-06-26 at 1 00 12 PM](https://github.com/hargata/lubelog/assets/14864940/4d20f205-ca21-4e95-9c55-4c9794da6943)

**Comment by hargata** [comment]
Released in 1.3.5, in your csv, append `extrafield_` in the column and it will be imported.
