### ISSUE TITLE
Unable to download the PWA through a mobile browser

### ISSUE THREAD

**Issue by zibbonkhadka** [hargata/lubelog#546]
- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
I am unable to download the PWA through a mobile browser. Do I need to modify the any files to make the PWA work?

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Comment by hargata** [comment]
No reproducible. PWA manifest is valid according to Google Chrome on Android. The only reason why you wouldn't be able to install it via a mobile browser might be due to your LL instance not being served via a HTTPS connection.
