### ISSUE TITLE
[Feature Request] Send email when reminders are coming due

### ISSUE THREAD

**Issue by scb147** [hargata/lubelog#547]
Provide the ability to configure a reminder to send an email when that reminder is coming due.

**Comment by alternativesurfer** [comment]
This would be excellent
Email, or push

**Comment by wxyShine** [comment]
Support for custom requests, such as access to [gotify](https://github.com/gotify/server)

**Comment by AB944736** [comment]
I agree with this request!

**Comment by PartyingChair** [comment]
I'll add my voice to this. Don't care if it's email, pushover, or even some other app, just something so I can get notified of reminders

**Comment by hargata** [comment]
We already have an API endpoint that sends reminders out, but you need to setup a cron job for it.

This API endpoint will calculate the reminder urgencies and send out an email to users

https://docs.lubelogger.com/Records/Reminders#reminder-emails

It will look somewhat like this:

![Screen Shot 2024-09-06 at 4 39 36 PM](https://github.com/user-attachments/assets/c62b4f65-9900-4efe-90cd-ff04eb8de80e)

**Comment by PartyingChair** [comment]
I'm sorry, I'm a bit of a noob and I'm still learning. I understand the basics, but I'm lost. How do I tell it which e-mails to send for, and which vehicles? I have set up (and tested) SMTP so I know that's working at least.

I ran the curl (changing rootuser and rootpass to the root username and root password) and the url to my url, but as far as I can tell, nothing happened. 

Thanks for any help

**Comment by hargata** [comment]
@PartyingChair all good, I'm assuming you're using the user account you setup when you turn on "Enable Authentication". That account is more of a service account so it doesn't have any email address tied to it, the primary purpose of that account is to manage users, configure server level settings and run certain API commands.

What you can do, is go into the Admin Panel and add another user which will require an email address, then add that user as a collaborator to the vehicles you want to get notifications for.

When you hit the API you will then receive an email with the reminders. 

Docs:
Creating new users: https://docs.lubelogger.com/Authentication#creating-inviting-new-users

**Comment by PartyingChair** [comment]
Okay. So here's what I have done so far.

I turned on enable authentication, set that up as "root" with a password.

I created a new user. I logged into the new user, and created a vehicle (and reminder) with that specific user. 

I copied the example script, and usser "root:<rootpassword> along with my ip address/port in place of the url. It looks like this:

curl -n -u "root:***********" --location "http://10.52.3.36:2010/api/vehicle/reminders/send?urgencies=NotUrgent&urgencies=VeryUrgent&urgencies=Urgent&urgencies=PastDue"

I get no e-mail for the new user I set up.

**Comment by hargata** [comment]
@PartyingChair try removing the -n flag and see if that helps. 

Additional trouble shooting steps, login as the root user on LubeLogger and then paste the url into your browser and see what response you get.

**Comment by PartyingChair** [comment]
@hargata Thank you so much for your help, but unfortunately, I'm more confused than even.

Removing the -n flag did nothing for me.

However, logged in as root, pasting the url into my browser, not only does my browser say it's a success, but I got the email as I would expect. 

I attempted running the curl command from a different machine, to see if maybe it was something weird with the machine, got nothing. Again tried the url, worked instantly.

**Comment by hargata** [comment]
@PartyingChair you might have an invalid character in the password. Try setting the root user's password to something really simple with no special chars and try again.

**Comment by PartyingChair** [comment]
I was JUST thinking the same thing. Unfortuantely, I changed the password... and then forgot what I changed it too, so had to reinstall it from scratch. Don't be like me.

But, that was the exact issue. It is now working. Thank you so much for your help!

**Comment by hargata** [comment]
@PartyingChair Awesome! curl is finicky with special chars in credentials sometimes. You can control what reminders to send email out for based on the urgency by editing the urgency param.
`urgencies=NotUrgent&urgencies=VeryUrgent&urgencies=Urgent&urgencies=PastDue` 
will send out emails for reminders of all urgencies
`urgencies=VeryUrgent&urgencies=PastDue` 
will only send out emails for Very Urgent and Past Due reminders.

This issue should be good to close for now.
