### ISSUE TITLE
Make odometer entry optional when adding upgrades

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [hargata/lubelog#563]
Currently, the odometer field is mandatory when adding upgrades. It should be optional as sometimes you can't remember or didn't take note of the odometer when buying upgrades. I am currently using "0" as workaround, but this is inconvenient. Before switching to LubeLogger (thank you for creating an awesome piece of software) I used SpritMonitor and there the odometer entry is optional for upgrades. It should be like this for LubeLogger too.

**Comment by hargata** [comment]
Next release:
![optionalodometer_upgrades](https://github.com/user-attachments/assets/0e5f0a9d-6171-4033-ab73-253dbe4c4213)

Note that if you have "auto-insert odometer record" enabled and you add a record without odometer reading it will not create that odometer record.

**Comment by hargata** [comment]
Released.
