### ISSUE TITLE
Cannot Login With Super User

### ISSUE THREAD

**Issue by gt2416** [hargata/lubelog#567]
**Description**
 After creating a user for the first time, I cannot login. It keeps saying credentials are invalid, even though I know for a fact they are not.

**Platform**
- [X ] Docker Image
- Version 1.3.5

I have tried deleting the username and password hash in userConfig.json, setting auth to false and recreating the user many times. 
I can never login after creating the user. It always says invalid login credentials. 
I have tried different usernames, passwords with 1 character etc, but nothing seems to work.  

Edit: The password and username hashes also are correct in the config file. for example, password 123456 is correctly hashed as 
8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92

**Comment by hargata** [comment]
can't reproduce, sorry.

Was it working before you updated the docker image? Have you tried to clear cookies/cache/etc ?

**Comment by gt2416** [comment]
There are no console errors whatsoever. This is installed on TrueNAS Scale.
I just installed it on alpine linux with my backup and cant reproduce the error either. Its very strange. I have even deleted and recreated the container on TrueNAS and the issue persists. I guess I will just use a more traditional docker install.
