### ISSUE TITLE
[Feature Request] Allow paste of images/docs from clipboard

### ISSUE THREAD

**Issue by Rothemich** [hargata/lubelog#570]
I've just started with LL and I'm finding it very satisfying to track service/maintenance records.  One enhancement that I would find PARTICULARLY helpful would be having the ability to paste from the clipboard; specifically a screenshot, photo or document.  

A particularly relevant use case is to be able to take a photo from my phone and immediately paste it into LubeLogger:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/df8e8e1f-c364-4723-bc85-7b3badef4793">

This would enable us to easily capture document scans and relevant photos without the need to first save them to a file.  Very helpdful, indeed.

Thanks for all the great work and documentation on this project!

**Comment by hargata** [comment]
Released in 1.3.6

![uploadonpaste](https://github.com/user-attachments/assets/726cf16a-0356-4210-a6b5-7576fe8aee77)

**Comment by Rothemich** [comment]
This implementation is spot-on perfect, @hargata.  I rely on photos to document the state of lots of maintenance/service details.  This now works **beautifully**.  Thank you!
