### ISSUE TITLE
Postgres: Cannot delete vehicle if any database tables are unpopulated.

### ISSUE THREAD

**Issue by uaeB1982** [hargata/lubelog#576]
- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
When running the application with Postgres as a database, a vehicle cannot be deleted if any tables are empty (ctext.ExecuteNonQuery() > 0 evaluates to false)

**Comment by hargata** [comment]
Fix released
