### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by helio4k** [hargata/lubelog#59]
When trying to import CSV file into the library, it errors out. I have created some example entries under "fuel" and exported to CSV file from lubblogger website, then proceeded to delete the entries and tried to import from the previously exported CSV and it fails with error message: 
![image](https://github.com/hargata/lubelog/assets/37601706/d0ee5305-fa16-41ef-91ce-452b2c3e42e6)
any help would be greatly appreciated.
Helio2k

**Comment by hargata** [comment]
Any chance you can attach the CSV that is error'ing out?

**Comment by hargata** [comment]
Ah I was able to recreate the bug, this is now fixed, please test.

**Comment by helio4k** [comment]
Yes, now it's working just fine.
Thank Your this fast fix.
