### ISSUE TITLE
Langrauge / Time Formats not changing from US

### ISSUE THREAD

**Issue by JJxVortechx** [hargata/lubelog#595]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X] I have searched through existing issues.

**Description**

Using docker and when setting the following:
-e LC_ALL=en_GB.UTF-8
-e LANG=en_GB.UTF-8 

This does not work, it keeps as en_US I have also tried the example on this link and still stays as en_US.
https://docs.lubelogger.com/International%20Locale

I have delete all files and rebuilt the container multiple times and tried other langurages but does not work.

Please note other docker containers run on this server and works perfect.

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

Nothing to show on this

**App/Container Console Error**

<img width="323" alt="logs" src="https://github.com/user-attachments/assets/4800541d-c290-4f78-b2c9-b01288eb7fa7">

**Screenshots(optional)**

<img width="622" alt="docker" src="https://github.com/user-attachments/assets/45254515-5949-4d6d-b8a2-485020de46f2">
<img width="617" alt="date_format" src="https://github.com/user-attachments/assets/ad0c366f-0a5e-4165-b2f0-ad06bb75a053">
<img width="1135" alt="lang_us" src="https://github.com/user-attachments/assets/40e1d315-054b-4a30-abf4-ae7957f836ce">

**Comment by hargata** [comment]
en_US is just the default language, translations are not affected by the environment variables, those affect date and currency formats.

For translations, see https://docs.lubelogger.com/Translations

**Comment by JJxVortechx** [comment]
Afternoon,

Thanks for confirm that the en_US will not change directly.

After some more resets etc I have got the formatiing now showing correctly
<img width="1163" alt="okay" src="https://github.com/user-attachments/assets/1cf2fbb3-2bd7-4dba-ab76-0a8d263e8a44">

**Comment by JJxVortechx** [comment]
Looking forward to moving my spreadsheet over to this system instead. CLosing case
