### ISSUE TITLE
[Feature Request] Planner tabs Colour Coding

### ISSUE THREAD

**Issue by shanduur** [hargata/lubelog#598]
Add colour coding to different icon types like in Jira, so those are easier to distinguish:

![image](https://github.com/user-attachments/assets/0f630cbb-d066-46f1-accb-676903cda015)

**Comment by hargata** [comment]
what I currently have in mind, lmk what you think
![image](https://github.com/user-attachments/assets/be0b40cc-fc45-493a-b19c-4c962d7f8c92)

**Comment by shanduur** [comment]
I was thinking of something like this (the changes were generated by LLM, thus not aligning as they should). 

<img width="226" alt="image" src="https://github.com/user-attachments/assets/24a93edd-d0bc-4700-b995-2e6a615d824d">

**Comment by hargata** [comment]
![image](https://github.com/user-attachments/assets/ab4a7741-2e9e-4be5-8f41-8abe056fb917)

Mobile:

![image](https://github.com/user-attachments/assets/effa075b-c752-4316-a9a0-c7344731d38f)

**Comment by shanduur** [comment]
Amazing!

**Comment by hargata** [comment]
Released:

![image](https://github.com/user-attachments/assets/dd79143d-8708-40e3-b52c-323a4c25db76)
