### ISSUE TITLE
[Feature Request] Light/Dark Mode based on system settings

### ISSUE THREAD

**Issue by steffenrapp** [hargata/lubelog#603]
Many apps and Web apps have an option to use the Light/Dark Mode based on system settings. In LubeLogger you can only manually switch between the two modes in the settings. It world be great to have an option for automatic switching based on the OS's setting.

**Comment by hargata** [comment]
Next Release:
![adaptivetheme](https://github.com/user-attachments/assets/ab02a445-4192-408e-ba3a-a0d0c6f0fe35)

**Comment by hargata** [comment]
Released, I have added a second toggle for adaptive color mode based on system preferences:
![adaptivetheme](https://github.com/user-attachments/assets/044967d3-d99d-470a-9795-d62a79a925aa)

**Comment by mdrxy** [comment]
(nit) would be nice if this changed in realtime without requiring a page refresh
