### ISSUE TITLE
[FEATURE REQUEST] Ability to adjust supplies without utilizing them on current vehicle (or allow supplies to carry for all vehicles0

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#604]
So my scenario is that I have 2 vehicles -- both use 0W-20 oil.  I may use 5.5 qts for one and 6.2 qts for the other; however, I don't have any overlap between the two which makes tracking my current oil supply a bit wonky because I'll use residual of one vehicle's oil inventory for the other, etc.

1) Can there a way to make "Supplies" universal for ALL vehicles so if I put supplies in under one vehicle they show up for the entire fleet.  This could be helpful for things like various liquids that can be used for any vehicle (oil, fuel treatment, brake fluid, windshield washer fluid) and other parts as well

or if 1) is not possible then,

2) Can there be a way to adjust/manual entry of supplies consumed under one vehicle so it maintains a log of how the supply was used?
For example, if I have 15 qts of oil in the supply inventory and use 5 qts for a different vehicle, I can do a manual entry that says "On [date], consumed 5 qts for vehicle XYZ" and it reduces the inventory and cost by 5 qts?

**Comment by hargata** [comment]
Shop Supplies?

https://docs.lubelogger.com/Records/Supplies#shop-supplies

**Comment by Hawkins1212** [comment]
> Shop Supplies?
> 
> https://docs.lubelogger.com/Records/Supplies#shop-supplies

Ok thats what my request was.  I'll close out. Note I had that checked but I entered the Supplies under the vehicle vs. under main "garage" screen so it wasn't working for me.  I tested it out and it works now.

Thanks!
