### ISSUE TITLE
[Feature Request] Different urgencies for different reminders

### ISSUE THREAD

**Issue by PartyingChair** [hargata/lubelog#609]
I just want to start this off by thanking the dev for being extremely helpful so far, and I feel a bit bad asking for more, but I figured if I want it, maybe other people do.

I would love the ability to customize reminders a bit more. Primarily, different reminders with different urgency dates. For example, if brakes are do, I want that to be a 30, or even 60 day notification for Urgency.

But if an oil change is due, I don't mind that only being a 7 day urgency. 

Since it's also similar, I'll chuck this feature request in as the same: It would be nice to have the ability to change the wording too maybe? Instead of "Urgent" and "Very Urgent" I might choose "Due Soon" and "Urgent"

**Comment by hargata** [comment]
Reminder-specific urgency thresholds will be included in the next release, currently planned for November 1st 2024:

![reminderspecificthreshold](https://github.com/user-attachments/assets/6bfdd2f1-cdd5-4de3-9e56-d26d1674f35a)

Regarding the wording changes, you can create a custom translation file that will allow you to change the wording as you please.

See here: https://docs.lubelogger.com/Translations

**Comment by hargata** [comment]
Released.
