### ISSUE TITLE
Reminder mails not send

### ISSUE THREAD

**Issue by prom00** [hargata/lubelog#615]
First of all I've gotta say I really love LubeLogger, awesome work at first sight!

I'm having issues on sending reminders via my SMTP server.

I've created a reminder that is now 'Very urgent':
![image](https://github.com/user-attachments/assets/2295b198-0ea4-40be-a194-8cc0df820dd7)

As you can see, I'm also missing the 'Done' button in the interface.

I've setup the SMTP env variables and I've also validated the docker inspect results. There I can see my env:
```
"Env": [
                "LOGGING__LOGLEVEL__DEFAULT=Error",
                "LANG=nl_NL.UTF-8",
                "MailConfig__EmailFrom=aaaaaaaa",
                "DEFAULT_REMINDER_EMAIL=bbbbbbbb",
                "MailConfig__UseSSL=false",
                "LC_ALL=nl_NL.UTF-8",
                "MailConfig__EmailServer=xxxxxxx",
                "MailConfig__Password=yyyyyyy",
                "MailConfig__Username=zzzzzz",
                "MailConfig__Port=587",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "APP_UID=1654",
                "ASPNETCORE_HTTP_PORTS=8080",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "DOTNET_VERSION=8.0.8",
                "ASPNET_VERSION=8.0.8"
            ],
```
            
            
When I try to send the mails via the api call:
api/vehicle/reminders/send?urgencies=NotUrgent&urgencies=VeryUrgent&urgencies=Urgent&urgencies=PastDue
            
I get this as result:
```
 {
  "success": true,
  "message": "Emails sent"
}
```

Unfortunately, I'm not receiving any mails though

Another nice to have feature would be a button to simply test the smtp mail settings where it just sends out an example mail.

What am I missing here? Can you please help me? Thanks in advance.

Kind regards!

**Comment by hargata** [comment]
Have you tried the steps outlined in #547 ?

the done button only shows up for recurring reminders.

**Comment by prom00** [comment]
No that was the only thing I didn't test. Mainly because there is a DEFAULT_REMINDER_EMAIL in the settings.

But from what I understand now, you need to create a main (admin) user, which you shouldn't use to manage cars. And if you want to manage cars, you can best create a seperate user account.

I'm using this system to manage my own and my friends/families cars which I service for them. So mostly I'm interested in the reminders and not everyone has an account.

**Comment by hargata** [comment]
@prom00 the environment variable DEFAULT_REMINDER_EMAIL is only available in the `edge` tagged Docker image, and features in that branch are still being tested. 1.3.7 is scheduled to be released on November 1st.

**Comment by hargata** [comment]
@prom00 That is now released, instead of an environment variable, you can just add the default reminder email here:

![image](https://github.com/user-attachments/assets/4e69ead8-7ac6-4151-9257-cc26b849899c)
