### ISSUE TITLE
[Feature request] Resize images to prevent data usage

### ISSUE THREAD

**Issue by prom00** [hargata/lubelog#616]
I've noticed that my backup is 10mb when I created 5 cars in the system where only 2 of them contain an image.
After looking inside the backup, I've noticed the images haven't been resized.

Maybe it's nice to resize the images to save storage space?

**Comment by prom00** [comment]
Awesome you're looking into this! 

In my system, the image is 186 x 145
![image](https://github.com/user-attachments/assets/8a64e593-265a-449c-b3a2-524638ee919a)


The original image size is now 4032 x 3024
I've now resized the image to 672 x 504

This is still looking perfectly:
![image](https://github.com/user-attachments/assets/bda30eba-2197-4f59-ac74-b147b8751c73)

The image size has changed from 4.43MB to 206kB.

What I do in PHP is using the following: https://www.php.net/manual/en/function.imagecopyresized.php 
```
imagecopyresized($thumb, $source, 0, 0, 0, 0, $newwidth, $newheight, $width, $height);
```

I input the uploaded image and the output (resized) image I save on disk to use for all future use.

I have no experience in C to do this unfortunately, but I've asked our big AI friend, if he can help us out. He came up with this:
```
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include "stb_image_resize.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#include <stdio.h>
#include <stdlib.h>

int main() {
    int width, height, channels;
    
    // Load the image
    unsigned char *img = stbi_load("input.jpg", &width, &height, &channels, 0);
    if (img == NULL) {
        printf("Error loading image\n");
        return 1;
    }

    // New dimensions for the resized image
    int new_width = 200;
    int new_height = 200;

    // Allocate memory for the resized image
    unsigned char *resized_img = (unsigned char *)malloc(new_width * new_height * channels);

    // Resize the image
    stbir_resize_uint8(img, width, height, 0, resized_img, new_width, new_height, 0, channels);

    // Save the resized image
    stbi_write_jpg("output_resized.jpg", new_width, new_height, channels, resized_img, 100);

    // Free the memory
    stbi_image_free(img);
    free(resized_img);

    return 0;
}
```

**Comment by hargata** [comment]
Released.

**Comment by prom00** [comment]
Awesome! I'd love to update my installation, but I'm a bit scared of losing everything.

Is there somewhere a description on how to update a running configuration without loosing everything?
I know I can make a backup and reload it, but it feels like this isn't the way to go?

Is it posible we move all data to a volume maybe? 
Sorry I'm new to docker....

**Comment by hargata** [comment]
The docker compose should include all the volumes that needs configured.

**Comment by prom00** [comment]
I have a docker-compose like this:
```version: '3'
services:
  lubelogger:
    image: hargata/lubelogger
    ports:
      - "8080:8080"
    env_file:
      - /pathToEnvFile/lubelogger.env
    restart: unless-stopped
    volumes:
      - myapp:/home/node/app  # use named volume


volumes:
  myapp:
```

Note that I added a volume. However it doesn't matter if I add it or dont'. Whenever I run those commands:

```docker stop <container>```
```docker rm <container>```
```docker compose up -d```

It starts a container with an updated version of lubelogger (that's great)
But I have to reload the backup manually when I go to my browser at ipaddress:8080.
All settings are gone and also all vehicles etc.

When I restore a backup, everything is fine again.

**Comment by hargata** [comment]
Your volume does not map to the directories used by the app, refer to the docker-compose.yml file found in this repository.

**Comment by prom00** [comment]
That works alot better! Thanks alot!
