### ISSUE TITLE
[Feature Request] Disable registration but keep auth

### ISSUE THREAD

**Issue by monsieurpouet** [hargata/lubelog#618]
Hi ! Thanls for your job !

It's possible to disable the registration button on the front while keeping the authentication ?
Cheers,

**Comment by hargata** [comment]
Next release:

![image](https://github.com/user-attachments/assets/ccf3e77e-0904-480a-beb5-026f6fa029a3)

Registration option won't show up in Login page:
![image](https://github.com/user-attachments/assets/9474d926-d9a8-4fde-b63b-ca4eae9413b8)

**Comment by hargata** [comment]
Released.

**Comment by rmellmer** [comment]
Did this feature get pulled? I don't see it as an option in my settings. I'm running version 1.5.5:

<img width="1302" height="638" alt="Image" src="https://github.com/user-attachments/assets/5517353f-f60e-4f53-95e8-4bc676573c93" />

**Comment by hargata** [comment]
@rmellmer no it got moved into the server settings configurator instead
