### ISSUE TITLE
[FEATURE REQUEST] Make Odometer non-mandatory

### ISSUE THREAD

**Issue by mukowman** [hargata/lubelog#619]
Currently odometer readings are mandatory for gas records. My process usually involves adding the gas record while I fill up and then come back and add the odometer from a photo I take. Would it be possible to either make the odometer not mandatory or have an option to disable the odometer from being mandatory.

**Comment by mukowman** [comment]
Similar request to https://github.com/hargata/lubelog/issues/563

**Comment by hargata** [comment]
Next release:
![optionalodometer](https://github.com/user-attachments/assets/6651ca88-ef2b-41a1-8b26-730232f2d14d)

**Comment by hargata** [comment]
Released.
