### ISSUE TITLE
App reset to default/new state after update

### ISSUE THREAD

**Issue by boomschtick** [hargata/lubelog#620]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

I went to update my containers tonight.  I ran the following commands:

docker-compose pull
docker-compose down
docker-compose up --detach

All of my containers came up, but LubeLogger reset to factory default.  I had two cars in there and had added some maintenance and fuel and they are all gone.  I have no idea how to get it back.

**Comment by hargata** [comment]
You didn't persist your volumes.

**Comment by hargata** [comment]
Closed due to user error.

**Comment by boomschtick** [comment]
Crap!  In my Docker newbness, I didn't even know I needed to do that.

I've added persistance based on the example yaml file in this thread:

https://www.reddit.com/r/selfhosted/comments/1ea3dbn/lubelogger_install/

Hopefully that'll help others in the future.
