### ISSUE TITLE
[Docs] Allow for community input into docs

### ISSUE THREAD

**Issue by jacobburrell** [hargata/lubelog#622]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [ x] I have searched through existing issues.

**Description**
Other projects such as BTCPaySever have [repos for their docs](https://github.com/btcpayserver/btcpayserver-doc) and it would be great to allow community PRs or improvements to the docs.

**Platform**
- [ x] Docker Image
- [ ] Windows Standalone Executable

**Comment by hargata** [comment]
https://github.com/hargata/lubelog_docs

Note that the screenshots are about 4 versions behind, I'll be updating docs when I come back from my vacation on November 1st.
