### ISSUE TITLE
Chart Issue

### ISSUE THREAD

**Issue by coolkid3232** [hargata/lubelog#630]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [ x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x ] I have searched through existing issues.

**Description**

After updating to 1.3.7 from 1.3.6 the charts are broken.

**Platform**
- [ x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

![image](https://github.com/user-attachments/assets/739bbfb8-9adf-4230-8e34-46e6383431f9)

**Comment by hargata** [comment]
oh boy, is this light mode on a PC with dark mode preferences?

**Comment by coolkid3232** [comment]
I think the PC is set to dark mode but the settings on LL are 
![image](https://github.com/user-attachments/assets/a9284567-a1cb-4f65-846a-8b0e5cdd37cd)

I checked on IOS with safari, phone on dark mode and the charts are the same as the pc (unable to read). 

IF I turn dark mode off on IOS the charts work as expected.

**Comment by hargata** [comment]
Makes sense, I'll try to roll a fix out for this by the weekend

**Comment by hargata** [comment]
Fixed:

![image](https://github.com/user-attachments/assets/abfdf5a2-5208-4852-9f17-99c013b45d36)
