### ISSUE TITLE
[Feature Request/bug] "smart" insertion of odometers entries in the past

### ISSUE THREAD

**Issue by redge76** [hargata/lubelog#636]
Hello,

From time to time I need to insert odometer entries in the past to record the status of my vehicle 2 or 3 years ago.
But when you do this, the initial odometer value is the last entered value.
This means that if you enter the odometer value in the past, the distance in the new record is negative. (Is this a bug? I don't see a good reason to have negative values in odometer records)
To fix this situation, you need to correct the previous and next entries to reflect the inserted value.

So my feature request is to be able to easily insert odometers in the past by automatically changing the necessary records.

Current entries:
![image](https://github.com/user-attachments/assets/3371ff14-6b5a-4725-9a31-6abcde4d0650)

I added a new entry in the past:
![image](https://github.com/user-attachments/assets/a024ba0b-7b9e-4aaf-aae9-b82cb893ca3e)

Even if you correct the original odometer of the entry, the error is hard to spot.
![image](https://github.com/user-attachments/assets/1547372b-7074-4278-97ab-cf79d8382fac)

Total distance is wrong compared to odometer
![image](https://github.com/user-attachments/assets/723c0f86-fe87-4c6e-980a-2c70fe1fe725)

I think some use cases might require this kind of manipulation (e.g. if you rely on recorded engine hours and swap an engine for a new one) but I think it should be more obvious that the odometer records are not consecutive.

**Comment by hargata** [comment]
If you select all the records, right click and select ‘recalculate distance’ it will fix the initial odometer values.

**Comment by redge76** [comment]
Ho... It's a well hidden feature. (documented here for those who find this issue report: https://docs.lubelogger.com/Records/Odometer)
Maybe a button somewhere would be better ? (in the "add odometer record" for example or better directly above the record tables)

Thank you for showing me this solution.
