### ISSUE TITLE
Feature request - support for mixed distance unit (miles / km) pr vehicle

### ISSUE THREAD

**Issue by tveyben** [hargata/lubelog#638]
I have Motorcyles using miles (imported from the US as well as Ireland) and also motorcycles using km (destined for the 'native' European market). So despite living in Europa (using the SI km unit) I need to support both types of vehicles.

The current solution have a global setting for this value, but I (and hopefully others) need to support a mix.

**Proposal for  a solution**
- Allow entering odometer values with a user selectable unit [km/miles], default to the globally selected value (for me "km")
- Store this unit as a separate value in the DB as one more metadata field for the record
- Normalize all calculations (km/l etc) to the globally selected unit (for me "km")

**Comment by hargata** [comment]
See #364 
The odometer multiplier set at the vehicle level will allow you to auto-convert miles from the odometer reading to kilometers.
This way, all vehicles are standardized to kilometers regardless of which unit their odometer reads in.

**Comment by tveyben** [comment]
Ahhh - clever you, I missed that feature when exploring the setup.
Great
