### ISSUE TITLE
Support form submit via ENTER/RETURN key

### ISSUE THREAD

**Issue by tveyben** [hargata/lubelog#639]
In general in modern web-UX there is a lack of keyboard shortcut support.
LubeLogger is not bad - it supports TABing, and pressing buttons with SPACE etc.  this is great (!)

BUT unfortunately it's missing support for SUBMIT FORM using ENTER / RETURN

**Example:**
In the **Gas -> Increment Last Reported Odometer Reading** "window" there is only one input field.
After entering a value it should be submittable via pressing the ENTER or RETURN key.
As of now one have to either use the mouse to click on the Add button OR use TAB (nice) to get focus on the Add button and THEN press [SPACE, ENTER or RETURN].

I really like to use the "old native application style" (I recall it as long back as Apples system 6 and 7 in the late 80'ies ) where there is always one button visually identifiable as the one being used when hitting the ENTER / RETURN key.

LubeLogger uses the same visual design (a special color is used for the "submit" action, but lacks the keyboard support

Here the **Quit** is the action being performed when pressing ENTER or RETURN
![](https://www.savagetaylor.com/wp-content/uploads/2018/09/softmac_820_hdscsetup_device0.gif)

Atlassian's JIRA https://jira.atlassian.com/secure/ViewKeyboardShortcuts!default.jspa  is actually a very cool example of a web GUI that have keyboard shortcuts as a "first class citizen".

**Comment by hargata** [comment]
Next release, you will be able to use the enter key to submit on the popups(i.e.: increment last reported odometer window), but for the other form fields(Odometer, Description, Cost, Tags, Notes, etc) you will need to use CTRL+Enter to submit the form.

![keyboardentry](https://github.com/user-attachments/assets/5b1e5a9c-9057-47dd-a28f-3b1913325b20)

**Comment by hargata** [comment]
Released.
