### ISSUE TITLE
Wrong colors in fuel milage graph when imperial calculation is disabled

### ISSUE THREAD

**Issue by kgraefe** [hargata/lubelog#649]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

In non-imperial mode (L/100km; how do you call it?) lower numbers on fuel consumption are better. Hence their columns should be green and higher columns should be red.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Screenshots(optional)**

![grafik](https://github.com/user-attachments/assets/5ec55228-6ead-4bd6-ad11-2f0a4414c961)

**Comment by hargata** [comment]
Next release:

when using l/100km:

![image](https://github.com/user-attachments/assets/79c77318-f6dc-43f8-8716-3a0759528ad4)

when using km/l or mpg

![image](https://github.com/user-attachments/assets/e69e3423-3647-4439-8c71-875215142d02)

![image](https://github.com/user-attachments/assets/900dc9e4-b094-418d-8095-1b6798db464b)

**Comment by hargata** [comment]
Released.
