### ISSUE TITLE
lublogger docker container keeps making connection to github !

### ISSUE THREAD

**Issue by woreibi** [hargata/lubelog#650]
Hi,

I am trying lubelogger in a docker container. I was able to deploy it. For security reasons I isolate container and do not allow internet connection outbound from it and I noticed any settings I change under settings waits for around 100 seconds before the page refresh and shows up again.

The container is showing below message in log:
fail: CarCareTracker.Controllers.HomeController[0]
      Unable to retrieve sponsors: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

and on my firewall it appears that it is trying to reach to git hub on this IP: 185.199.111.153:443

It appears docker container app was designed everytime you change a setting to make connection to github. 

Can this be disabled, as I don't see why container need to make a connection everytime I change one of the settings under settings option.

Thank you,

**Comment by hargata** [comment]
It makes a connection to a static file hosted on Github to retrieve the list of sponsors for the project.

Currently we have no plans to disable this.

**Comment by diesphink** [comment]
Just an FYI, on my installation this behavior is making the settings tab delay 100s to open, and then more 100s every time I change a value (and there's no explicit firewall rule).

I understand the reason for the file, but maaaaybe at least make an timed local cache with a few minutes? It's not much of a compromise and that would be so much better user experience on this case.

**Comment by hargata** [comment]
@diesphink this is getting fixed on the next release.
