### ISSUE TITLE
[RFE] Status Indicators on Garage Tab

### ISSUE THREAD

**Issue by fftux** [hargata/lubelog#66]
# Idea
I would like to use the Garage tab as a dashboard that provides an overview of status of all vehicles.

# Details
Add chips to vehicles on the Garage tab.  Ideally, this could be configurable.  To begin with, though, having info such as last reported mileage, avg. mpg, service/reminder status.

**Comment by hargata** [comment]
This is now being worked on:
Pretty limited so far. it will only display last reported mileage and if the vehicle has any past due or very urgent reminders.
![image](https://github.com/hargata/lubelog/assets/155338622/50c43275-e40e-473c-baa0-0bd93e0f0498)
