### ISSUE TITLE
Add days "out of service"

### ISSUE THREAD

**Issue by cmsandwich** [hargata/lubelog#660]
Add days out of service to each repair and each service. Display the total days "out of service" in the dashboard. Important metric while assessing equipment.

**Comment by hargata** [comment]
This is kinda niche, but it's definitely possible with the Custom Widgets feature we just released.

In fact, the example I used in the documentation does exactly your use-case.

First you'll need a Extra Field named `Days Out of Service` in your service records, upgrades, and repairs.

Then Follow the instructions here:

https://docs.lubelogger.com/Advanced/Custom%20Widgets#configuring-custom-widgets

The example configuration will aggregate all of the Days Out of Service values which will be visible in the `Additional Widgets` button in the Reports page.
