### ISSUE TITLE
v1.3.9 SMTP timeouts in Docker

### ISSUE THREAD

**Issue by ndrobac** [hargata/lubelog#665]
**Checklist**

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Using mailtrap.io as SMTP provider, tried their sandbox and production config, two different smtp servers, and tried with regular Gmail with app password, same error occurs, attached image of error below.
I have triple checked parameters for env variables per documentation before asking for help here.

**Platform**
- [x] Docker Image

Docker image I used is with edge tag, since it fixed the blank settings tab, which at the time of writing runs v1.3.9

**App/Container Console Error**

![Image 24 10 24  at 16 18](https://github.com/user-attachments/assets/bd229321-4415-4803-8cfd-95a8edae2866)

**Comment by hargata** [comment]
Config issue, sounds like your docker container doesn't allow outbound connections, make sure you didn't isolate it.

I just tested it myself with gmail smtp and it works.
