### ISSUE TITLE
Months Sorted Alphabetically on Reports Tab

### ISSUE THREAD

**Issue by fftux** [hargata/lubelog#67]
# Problem
<img width="644" alt="image" src="https://github.com/hargata/lubelog/assets/20529157/6fc15990-358d-4325-a39f-c7fe137aa480">

# Expected Behavior
Months ordered chronologically, not alphabetically.

**Comment by hargata** [comment]
this should be fixed already

**Comment by fftux** [comment]
Confirmed.  It is fixed now.  Thanks.
