### ISSUE TITLE
Attempting to update odometer via API returns a 500

### ISSUE THREAD

**Issue by burntcookie90** [hargata/lubelog#675]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Attempting to update a vehicles odometer throws a 500. 

request (POST using restful command in HASS, `content_type` is set to `multipart/form-data`):
```

2024-10-28 19:25:44.965 WARNING (MainThread) [homeassistant.components.rest_command] Error. Url: https://<url>/api/vehicle/odometerrecords/add?vehicleId=1. Status code 500. Payload: b'date=10/28/2024 odometer=18480'
```

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

```
      System.Collections.Generic.KeyNotFoundException: The given key 'vehicleId' was not present in the dictionary.
         at CarCareTracker.Filter.CollaboratorFilter.OnActionExecuting(ActionExecutingContext filterContext) in /App/Filter/CollaboratorFilter.cs:line 22
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
```
**Screenshots(optional)**

**Comment by hargata** [comment]
Can't reprod, will leave it open anyways just in case someone else can chime in

**Comment by burntcookie90** [comment]
Actually, good call. Tested with httpie and it completed without issue. Seems either my HASS configuration is incorrect, or there's some unexpected complexity with how HASS makes this network call.

**Comment by burntcookie90** [comment]
Just for the record:

`Payload: b'date=10/28/2024 odometer=18480'` should be `Payload: b'date=10/28/2024&odometer=18480'`
