### ISSUE TITLE
[Feature Request] Vehicle Lease Tracking

### ISSUE THREAD

**Issue by nota3k** [hargata/lubelog#678]
Add support for Lease tracking. 

**Metrics:**
- Current Mileage
- Daily Average
- Unused mileage
- Monthly average
- Excess mileage
- Excess charge
- What should my odometer read?
- How far can I drive today?
- When does my lease end?

**Lease Details:**
- Starting mileage
- Total mileage allowed
- Length of lease
- Lease start date
- Overage fee
- Document upload for contract

**Comment by hargata** [comment]
Too niche to be built into LubeLogger directly, but a lot of what you're asking for can be achieved via Custom Widgets and Extra Fields.
