### ISSUE TITLE
[Feature Request] - Add composite Dashboard to main screen

### ISSUE THREAD

**Issue by Enterprise76** [hargata/lubelog#680]
I have a fleet of multiple vehicles, each with upcoming planned projects and recurring service items.

is it possible to add a 'master dashboard' on the main screen that would show all pending planned items, and all pending reminders for the entire fleet on one screen?

This would make it easy to plan projects and order tools and supplies.

Great software!  Thanks!

**Comment by hargata** [comment]
We're working on a Kiosk view for the next release that will probably fit your use case.

It has a few modes:

- Vehicle - general overview of all vehicles.
- Reminders - show all the reminders for all vehicles(click on them to show notes)
- Plan - show all the plans for all vehicles(click on them to show notes and supplies)
- Cycle - cycle through all three of the views above.

![image](https://github.com/user-attachments/assets/1481235f-08a1-4b45-93fb-6bb566b572a0)

![reminderkiosk](https://github.com/user-attachments/assets/f9436152-7bd8-4618-ad13-0900fb2aa572)

![plankiosk](https://github.com/user-attachments/assets/7bdabe7e-bae9-4a72-b339-40f22a4b9a26)

It being a Kiosk view means that it auto refreshes at a fixed interval(approximately 1 minute) and it's pretty much designed to be displayed on a screen full time.

**Comment by hargata** [comment]
Kk this is now released, after you've updated, simply navigate to <yourlubeloggerdomain>/kiosk to get started

Further Documentation with additional configuration: https://docs.lubelogger.com/Advanced/Kiosk
