### ISSUE TITLE
[Feature Request] Fuel type by fill up

### ISSUE THREAD

**Issue by NickKatchur** [hargata/lubelog#682]
It would be nice to be able to specify the specific fuel mix per fill up. This includes E85, E15/Unleaded88, Regular, Midgrade, etc. for USA. It'd also be beneficial to be able to filter MPG by fuel mix for comparisons.

This way we could compare mileage/cost depending on the specific fuel we get at each fill up.

**Comment by hargata** [comment]
You can either use the tags or add an extra field for the fuel type which you can then use the Search function to filter out.

**Comment by NickKatchur** [comment]
Could tags be added to the API then? It doesn't appear to accept that functionality.

**Comment by hargata** [comment]
Yeap, created a ticket to track that #684
