### ISSUE TITLE
[Feature Request] Be able to change Fuel Economy calculation from l/100km to Km/l

### ISSUE THREAD

**Issue by edersong** [hargata/lubelog#69]
A setting option to change Fuel Economy calculation from l/100km to Km/l

**Comment by hargata** [comment]
this seems to be an edge case, I can't recall if I know anyone who uses km/l for fuel economy. During my time abroad I've always known people to use l/100km to measure fuel economy.

**Comment by nicolopozzato** [comment]
In Italy we use to say tot l for 100km or also tot km with one liter.
The km/l it's easy and fast to compare the "pure" cost at the gas station.
In my personal excel i use the km/l for example
(the project hammond has a select dropdown near the graph)

**Comment by userbradley** [comment]
UK uses

* l/100km
* l/km

And all the imperial ones too

**Comment by hargata** [comment]
This is added, somewhat. If you right click on the fuel mileage column and you're using metric calculations(l/100km), it will toggle between l/100km and km/l

**Comment by edersong** [comment]
Nice, thanks!
One question: Is there a way to make it permanent?

**Comment by hargata** [comment]
@edersong perhaps, I'm currently looking into ways of saving user's preferences on the gas tab.

**Comment by hargata** [comment]
@edersong the settings now persists. It will save your selected fuel mileage / consumption. Test it out and let me know if there are any issues. Might have to re-start your docker container for it to work since it technically adds a new value to your user settings.

**Comment by edersong** [comment]
Thank you, @hargata 
It's working like a charm!! :-)

**Comment by richard-lee-863** [comment]
How do you actually get lubelogger to show km? I've got the "use imperial" setting OFF, but still shows odometer and fuel economy with miles. 

![image](https://github.com/hargata/lubelog/assets/43104957/1bd3a47b-0f65-43a5-b22e-48f8e617dfb5)

![image](https://github.com/hargata/lubelog/assets/43104957/09153dd4-781b-4905-bd08-75519813d0fb)

**Comment by hargata** [comment]
@richard-lee-863 if you have UK MPG checked it will always display distance unit as miles because that is what the UK uses.

**Comment by alphamike-1612** [comment]
@hargata Thank you for this amazing piece of software.

When you guys get back from your hiatus, can you please include this feature into the Wiki? 

It would be more prominent and help more people find it easily.

Also, if you could add what other columns have this right click option to change stuff, it would be extremely helpful. (Another I found is the litres to Imp Gal. to US Gal.)

Once again, thanks for this awesome piece of software.

**Comment by hargata** [comment]
@alphamike-1612 This is already in the documentation
https://docs.lubelogger.com/Records/Fuel%20Records#alternate-fuel-units
