### ISSUE TITLE
[Feature Request] Be able to change the decinals from 3 digits to 2 digits

### ISSUE THREAD

**Issue by edersong** [hargata/lubelog#70]
A Configuration setting to change to change the decinals from 3 digits to 2 digits. 
Example: from 1.236 to 1.24

**Comment by thehijacker** [comment]
This is a good idea. In my country the price per liter of gas has three decimals (1,123), total price has two (80,20 €) and consumtion  in liters with one (30,2 liters). But this might be different elsewhere.

**Comment by hargata** [comment]
This is released

**Comment by edersong** [comment]
Awesome!
Thank you for taking this into consideration!!
