### ISSUE TITLE
[Feature Request] Change the landing tab from Service Records to Fuel

### ISSUE THREAD

**Issue by edersong** [hargata/lubelog#71]
Change the landing tab from Service Records to Fuel because most of times that we open the app is to input or consult Fuel data.

Or, a landing page where shows the tree latest inputs (any of them) and statistics like Current month Consuption, Cost etc. with a direct button to add Fuel, Service Records etc.

**Comment by nicolopozzato** [comment]
To be honest I really like the idea of a sort of landing page of that car with easy access, some graph, data, history.

**Comment by Teonyr** [comment]
I'd +1 a proper Overview tab/page if I click on a car instead of the services tab/page.

Displaying average consumption per 100km/xx miles, average monthly costs, some nice graphs, last x expenses, etc... 😁

**Comment by hargata** [comment]
@nicolopozzato @Teonyr have you guys checked out the reports page? That'll probably change into a Dashboard page pretty soon and I will add a setting for the user to choose their landing page.

**Comment by Teonyr** [comment]
Yes, thought of something like the reports tab. 👍🏻
Looking forward to it.

**Comment by hargata** [comment]
As of Release 1.0,6 you can select which tabs you want to see and which tab to set as default tab.

**Comment by hargata** [comment]
Closing this because this is released.
