### ISSUE TITLE
[Feature Request] Additional section for notes in fuel tab

### ISSUE THREAD

**Issue by Vyerni** [hargata/lubelog#72]
As per title. 

Given all the other tab entries, be nice for there to be a notes section for fuel. So key information could be entered and referenced later.

**Comment by psyciknz** [comment]
Would love this also.  A convert from fuelly, where some of my import data was not great (0 odometer readings etc),   But thankfully at the time I generally enter odometer readings in a fuelly note on each fuel receipt.

So would love just a note field for each fuel up for small notes (Trip to x, car reporting consumption of xyz).

**Comment by hargata** [comment]
This is added
