### ISSUE TITLE
Display fuel consumption with two post-comma digits only

### ISSUE THREAD

**Issue by kalipso-cyber** [hargata/lubelog#723]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**
Hi,

first of all thanks for the app - I just recently set it up and I'm quite liking it!

**TL;DR is that I want to display the number of litres as 34,92 and not 34,920 or 3492,000.**

A bit more content: My LubeLogger has the "Use Imperial Calculation" as well as the "Use UK MPG Calculation" settings both turned off. The "Use three decimals for fuel cost" option is also deactivated. The problem is that my fuel consumption is still shown with three post-comma digits.

So for instance, in an entry in the "Fuel" tab of a vehicle, where I added 34,92 litres of fuel to a vehicle, under "Consumption" it shows as _34,920_. If I enter _34.92_ instead of _34,92_, the _34,920_ changes to _3492,000_. But I don't want to show this with three digits, especially since the third digit will always be 0 anyways as no gas station around me counts three digits after the comma.

Which setting do I need to change to correctly display the number of litres with only two digits after the comma?

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**
n.a.

**App/Container Console Error**
n.a.

**Screenshots(optional)**
Here's a visual representation of my settings:

<img width="1294" alt="settings" src="https://github.com/user-attachments/assets/d19546eb-9066-4be7-87fb-c15886bbb57a">

And this is what the field in question currently looks like:

<img width="1286" alt="fuel consumption" src="https://github.com/user-attachments/assets/fbb32003-c6dc-4cf5-a2f6-70f88036d35f">

**Comment by hargata** [comment]
The next release will have a new switch in the settings page that will allow you to set the consumption to 2 decimal places.

**Comment by hargata** [comment]
Released in 1.4.1

![image](https://github.com/user-attachments/assets/0f9f50f0-5668-43b8-acb4-b2a670409aef)

![image](https://github.com/user-attachments/assets/6d5f0ceb-244d-4504-8470-3350f542420a)
