### ISSUE TITLE
How to access from all network

### ISSUE THREAD

**Issue by elbertondu62** [hargata/lubelog#729]
Hi.
I have download the windows installer. I have configured the .json file.
But only localhost can access to the website.
If i want to access on a another computer it's not possible.
i have see the AllowedHosts section. 
I have add port 5000 to the windows firewall.

thank's for your help

**Comment by hargata** [comment]
Documentation:

https://docs.lubelogger.com/Installation/Troubleshooting#cant-access-lubelogger-instance-from-other-devices

Closed Issues:
#718 
#268 
#497 

Next time, search before posting.
