### ISSUE TITLE
Add support to add/remove fields in Fuel Tab

### ISSUE THREAD

**Issue by wmdaricthompson** [hargata/lubelog#74]
Love the project. I would like to make use of the fuel tracking tab, as fuel tracking is already something I do on a per tank scale. However I found I'm already tracking several parameters that aren't currently in the fuel tracking tab. Rather than list out what they are, I would like the ability to add/remove fields as necessary to customize the information tracked to suit my specific needs.

Thank you and keep up the good work!

**Comment by Abateman121** [comment]
Instead of making another issue I would like to request the fields  "Is filled to Full" and "Missed Fuel Up" be added as fields for the fuel import csv.  
![2024-01-13_22-58-20](https://github.com/hargata/lubelog/assets/83042153/f531cef4-0246-45bf-8db7-8b89f0e13814)

**Comment by hargata** [comment]
The feature to add custom fields have now been added in 1.1.6.
Watch: https://www.youtube.com/watch?v=FIlo9Q6eQBo
