### ISSUE TITLE
Total Distance not correct

### ISSUE THREAD

**Issue by spcqike** [hargata/lubelog#742]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

the very first odometer entry isn't used to calculate total distance. you can enter "0" as initial point, but it gets overwritten on recalculation. 

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

data entered:
![grafik](https://github.com/user-attachments/assets/b0982ed5-73ec-4f8b-95b3-be09c4d5c5b2)

correct values after initial "0" was set
![grafik](https://github.com/user-attachments/assets/badf0724-e333-400f-9eaa-33ca42d5df11)

wrong value after recalculation
![grafik](https://github.com/user-attachments/assets/76eac1b6-4a46-4cb6-be4d-2dceda2391d7)

the same happens, when one entery an initial "0" odometer point

manuel added "0" and changed the "second" trip, correct values befor recalculation
![grafik](https://github.com/user-attachments/assets/3761b12c-af73-48fe-a1db-a25e871e1fc1)

wrong value after recalculation
![grafik](https://github.com/user-attachments/assets/4abbf98f-873b-4b4a-85e1-50edb58b0432)

**Comment by hargata** [comment]
Not a bug and not an issue. LubeLogger only concerns itself with the amount of distance you put on your vehicle for the duration you owned it. The first odometer reading is always ignored. I don't know where you live but no cars are ever delivered with 0 miles on it. Your first odometer reading should be the mileage when you took delivery of the car.
