### ISSUE TITLE
wrong average cost/km in dashboard

### ISSUE THREAD

**Issue by spcqike** [hargata/lubelog#743]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

the calculated average in the dashboard may be wrong, as it calculates total costs / last odometer value only

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

![grafik](https://github.com/user-attachments/assets/c28a299d-ba13-4301-aaae-7b09347e4120)

my odometer is 35806, but the calculated distance is only 35167 (as the very first odometer entry isn't used correctly, see #742)
~~couldn't check but if the calculation really uses last odometer only, one can't calculate for a used car, which was bought with odometer > 0.~~ total distance is used
![grafik](https://github.com/user-attachments/assets/05ab8a54-dfe6-4567-815c-53b8b73c76b9)

next the costs, in my case, are only fuel. but as there are several skipped fuel ups, there are missing costs.
![grafik](https://github.com/user-attachments/assets/7b236d7d-36b4-4594-8ec7-c01d6c69c40b)

so one could only calculate costs/km based on fuel costs/km without gaps.

**Comment by spcqike** [comment]
here a fake car, to show what i mean.

lets assume, i bought a car with 32.000km. skipped several fuel ups until 32.800, and fueled up at 33.000 again.
imagin a 20€ fuel up every 200km, so 5 in total, with 3 missed.

![grafik](https://github.com/user-attachments/assets/79b48481-53e1-42e7-83c6-774b5adec016)

![grafik](https://github.com/user-attachments/assets/776e95ad-91fb-4b2a-be4a-809a3bdd9970)


so we should have 10€/100km or 0.1/km as we owned the car. but it calculates 0.04€/km, as it uses the total amount (41€) by total distance (1000km)
![grafik](https://github.com/user-attachments/assets/ab7db9c9-b0eb-4bd6-bd29-62361a077404)


with consistend data, this error will be  negligible, if visible at all. but with missing fuel ups, it will increase over time.

**Comment by hargata** [comment]
uhhh, not quite sure what you're asking about here.

First you mention that the cost / distance traveled only looks at the last reported odometer, which is most definitely not true, as seen in your second comment, it tallies up the distance column in the odometer tab.

Second, I have no clue how you would get 10 euro/100km from your calculations at all. As seen in your fuel tab, you spent 1 euro fueling up at 32,000 km, 20 euros fueling up on 32,800 km and then another 20 euros fueling up at 33,000 km.

At this point you have driven 1000 km and spent a total of 41 euros on it. That seems logical to me how the app is calculating  your cost over distance.

**Comment by spcqike** [comment]
well, the app knows, that there are missing fuel ups. like it allready knows for the calculation of the economy. 
don't you think its possible and more accurate to also skip those miles/km in the calculation of costs/mile?

i know that the app can't know the costs of missed fuel ups, thats not the point. the point is, that it doesn't care about missed fuel ups for this calculation.

eg my SO forgot to give me the bills for like half a year. so one car has about 12.000km but only 440€ worth of fuel ups, with one fuel up having 40€ and 4.000km, which is insane low and breaks the statistics.

you are right, its better to have all records in the statistics, but, as missing fuel ups allready is part of the app and is considerd in the calculation of economy, i thought it would also use this information for calculation of costs per mile.

well, right now it doesn't, and so my (expensive) petrol car looks "cheaper" per mile, then my (cheaper) EV.

IMO it would be smart to not use missed fuel ups for this calculation, so in my example use only 8000km and 400€, and not 12.000km and 440€ 

of course, this doesn'T show the overall costs, but as the part "cost/mile" is broken down to every mile, in would be more accurate if only constistent fuel up data is used.

as quick and dirty workaround, i will add fake fuel ups with no km, but with high costs, to add the missed expenses, as far as i can estimate it.
