### ISSUE TITLE
Files not available Error 400

### ISSUE THREAD

**Issue by ZoXx** [hargata/lubelog#749]
Hello everyone,

I have old .pdf files and images that when I call them up, I get the following error message:
Error 400 domain.xyz/temp/a98004b0-c3df-41e0-94b3-d2d75ee9b3bd.pdf

Thanks! :)

**Comment by hargata** [comment]
Uploaded files are moved from `/temp` to `/documents` when the record is created.

Try `domain.xyz/documents/a98004b0-c3df-41e0-94b3-d2d75ee9b3bd.pdf`

**Comment by ZoXx** [comment]
doesnt work :(

**Comment by hargata** [comment]
How are you linking to these files, i.e.: where are you getting the `/temp` links from?

**Comment by ZoXx** [comment]
via notes of the vehicle and then via link
![image](https://github.com/user-attachments/assets/3f6b24e7-2037-4be9-a669-fea26e8bfce0)

**Comment by ZoXx** [comment]
Docker Version 1.4.1.
Only affected old documents (.pdf).
News files are working without problems.

**Comment by hargata** [comment]
In your docker compose, do you have this?

![image](https://github.com/user-attachments/assets/708e658d-2391-4d87-ab00-81ebe94542d6)

**Comment by ZoXx** [comment]
temp was missing. 
The only path who was missing.

another chance to get on the old files?

**Comment by hargata** [comment]
there's a good chance Docker still has the volume but it will be an anonymous volume(not named), you will have to find that volume

**Comment by hargata** [comment]
Will be closing this as this is a user oversight.
