### ISSUE TITLE
[Feature Request] Regenerate/update/linked Odometer records

### ISSUE THREAD

**Issue by B3CKDOOR** [hargata/lubelog#758]
I would love it if it was possible to regenerate the "automatic" odometer records injection.

Ive entered some information about my car and mistyped the odometer, it automatically added it to the odometer page (with the same wrong record)

ive edited the service records to be the right odometer, but now ive got to manually change all records on the odometer page.

i would love it if there was some way to "regen" the odometer records when/if deleted or to automatically update when updating a service record.

**Comment by redge76** [comment]
The odometer record is not updated automatically, but, if I understand you issue correctly, you don't have to manually change all the records. As described here: https://docs.lubelogger.com/Records/Odometer

`This tends to happen when odometer records are inserted out of chronological order, to fix this, all you have to do is select all of the records, right click on them, and select "Recalculate Distance" This will update all of the initial mileages to be in a chronological order.`

**Comment by B3CKDOOR** [comment]
That does indeed solve the first problem, however ive now since deleted all records that were wrong and would like to know if there is a way to "re-insert" the records ive deleted
