### ISSUE TITLE
Container LXC - Change the date display format and also the currency

### ISSUE THREAD

**Issue by xekil** [hargata/lubelog#762]
Hello,

I installed LUBLOGGER via [this script](https://github.com/community-scripts/ProxmoxVE/blob/main/ct/lubelogger.sh) (LXC Container) and I would like to modify the date display format and also the currency format.

I saw that an .env file was needed, but here it is not docker.

[The configurator](https://lubelogger.com/configure/) allows you to create an appsetting.json file in the case of a Standalone Linux installation, which is the case for an LXC container, but it does not seem possible to modify these parameters (date and currency).

Do you have an example of the parameters to add/modify in the appsetting.json file? I have tried several times to add and modify this file located in opt/lubelogger and with a restart of the container each time, but without success.

```
  "LUBELOGGER_LC_ALL": "fr_FR",
  "LUBELOGGER_LANG": "fr_FR",

```
```
  "LC_ALL": "fr_FR",
  "LANG": "fr_FR",
```

As for the display language, I have the desired language file and it works correctly, no problem on that side.

Thank you for your help.

**Platform**
- [ ] Proxmox LXC

**Comment by hargata** [comment]
I don't use Proxmox LXC, so my knowledge on this is very limited, but it seems like it uses a very similar process to the Linux standalone installation, in which case, all you have to do is shimmy in `LANG=fr_FR` before the lubelogger service is started.

**Comment by xekil** [comment]
Thanks for your reply, I'll look into that, it does indeed seem logical if the currency and date format are retrieved from the system information. On that subject, an option to change this directly from LUBELOGGER would be a good idea for improvement.

**Comment by xekil** [comment]
Here is the manipulation to be done in the LXC console of course:

```
localectl set-locale LANG=fr_FR.UTF-8
set LC_ALL=fr_FR.UTF-8
locale-gen “fr_FR.UTF-8”
```
