### ISSUE TITLE
[Feature Request] Input total price OR price per unit

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog#77]
Currently I need to input total price of bill when I refuel my car. And you calculate the unit cost. It would be nice to have it also vice versa. So when you add new fuel record, you can type unit price and final price gets calculated from it.

**Comment by Abateman121** [comment]
+1

**Comment by hargata** [comment]
This is added, but to preserve backwards compatibility, you can only input gas prices in Unit Cost when ADDING new records, when you go to edit an existing record you can only edit the total cost.

**Comment by hargata** [comment]
Since this is released, I will mark it as closed.
