### ISSUE TITLE
[Feature Request] EV fill up battery charge level in percentage

### ISSUE THREAD

**Issue by ramess18** [hargata/lubelog#770]
Hello, I was wondering if you could consider add another field  for each record - charge level (%). I know such calculations can be tricky but I think all EV owners will appreciate that. Spritmonitor has such thing (see screenshot):
![image](https://github.com/user-attachments/assets/24beb539-92f5-42fb-9f59-31c59b9dc495)
Thank you
Radim

**Comment by hargata** [comment]
Can this not be accomplished via an extra field? I don't see what type of calculations is required for this field.
