### ISSUE TITLE
yaml: line 216: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by MenooMeow** [hargata/lubelog#773]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [X] I have searched through existing issues.

**Description**

During `sudo docker compose up -d` I get the error: `yaml: line 216: mapping values are not allowed in this context`.

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

`yaml: line 216: mapping values are not allowed in this context`

**App/Container Console Error**

`yaml: line 216: mapping values are not allowed in this context`

**Screenshots(optional)**

**Comment by hargata** [comment]
Not a LubeLogger issue, check your docker compose file

**Comment by MenooMeow** [comment]
> Not a LubeLogger issue, check your docker compose file, you most likely have a mis-indented line somewhere

You were right!  The compose file contained HTML/CSS code instead of the docker compose file relevant content!
