### ISSUE TITLE
Reminders showing Past Due despite not reaching date or mileage values

### ISSUE THREAD

**Issue by walk0080** [hargata/lubelog#777]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [ X ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [ X ] I have searched through existing issues.

**Description**
Reminders are showing as status "Past Due", despite not yet reaching the mileage value and/or due date.

The current odometer reading is 156717. There is an entry of 156717 in the "Odometer" section and also a recent "Service Record" entry with that same km amount. Screen captures were taken today (date is Dec 31st, 2024).

In the past these entries appeared fine... so perhaps a later update broke something for my install. I will create some new entries to see what happens...

**Platform**
- [ X ] Docker Image

**Browser Console Errors(F12)**

No console/browser error received.

**App/Container Console Error**

Don't think there are any relevant errors in the logs:
![IMG_2516](https://github.com/user-attachments/assets/8639fb58-dd87-478f-821f-3a70edca6d4d)

**Screenshots(optional)**

These examples have date/km values and are showing as past due:

![IMG_2512](https://github.com/user-attachments/assets/cae1286d-c071-4ccc-a6d7-1da6f2a012e2)
![IMG_2510](https://github.com/user-attachments/assets/62399e9a-1728-4853-b97d-c42fed0b23ab)

These examples only have a due date and appear correct:

![IMG_2514](https://github.com/user-attachments/assets/c0b9fb23-e233-4f23-ad9c-82dc8c80af79)

**Comment by hargata** [comment]
Are you sure you don't have any entries with odometer exceeding 260000? Any entries from odometer/service/repair/upgrade can cause this.

**Comment by walk0080** [comment]
LOL amazing thanks for the quick response. There was an entry where my car had a million km! Thanks!

![IMG_2520](https://github.com/user-attachments/assets/b1efd563-530c-4e88-96bb-b982e0e1da2c)
