### ISSUE TITLE
[Feature Request] Gas station

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog#78]
There are different gas station vendors (Petrol, OMV, Shell, MOL, ...). It would be nice to have an option to have a database of them (self maintained, not global) and an option to select them when inputing new fuel record.

Then you can get information of average usage per 100 km per gas station for example. Or different filters to see how much you spent on gas per different gas station.

**Comment by fftux** [comment]
➕

**Comment by hargata** [comment]
@thehijacker @fftux The new tags system I just rolled out might help with this.

You can now add tags to fuel records and you can then filter them down via the the tag and it will automatically re-calculate the fuel mileage.

![gas tab tag](https://github.com/hargata/lubelog/assets/155338622/c4d255a9-c0f8-4277-ac82-78c2a037dae5)

When you are adding tags to the fuel record, it will give you options to fill in the gas station based on existing tags:

![image](https://github.com/hargata/lubelog/assets/155338622/9df8f712-501b-4e78-8fed-93a2a3fc88ee)

**Comment by thehijacker** [comment]
This is an awesom solution! Thank you very much. I have the gas station data in CSV export from poraba.com site. Can I use this for import and if so, what is the CSV header name for it? I will delete all current records on Lubelogger and reimport so I also get the gas station data as tags.

**Comment by hargata** [comment]
@thehijacker Thanks for the support!. I've just added the tags column in CSV import / export.
For the full list of importable column headers, see https://docs.lubelogger.com/Records/Fuel%20Records#importing-from-csvfuellyspiritmonitorde

The tags column are separate by " ".

**Comment by thehijacker** [comment]
Fresh import on latest version worked great. I now have also gas station records as tags that I can filter by.

![image](https://github.com/hargata/lubelog/assets/13857043/1e682705-a03d-41e0-a8d9-8496ffbee954)

If you agree, we can close this ticket now. Final thing so also my wife can start using it, is Slovenian translation. Keeping an eye on the feature request ticket regarding translation so when it is ready I will be right on it with translating.

**Comment by hargata** [comment]
Thank you! I'm currently working on the translation interface and should have something up this weekend.
