### ISSUE TITLE
[Feature request] Add tab for fines

### ISSUE THREAD

**Issue by TheBinaryLoop** [hargata/lubelog#80]
Would It be possible to record fines in LubeLogger? Or is that out of scope for this app?

**Comment by hargata** [comment]
I consider it part of the Tax tab, "going fast tax" as I like to call it.

**Comment by TheBinaryLoop** [comment]
That's a really great name for it

**Comment by hargata** [comment]
I'm gonna mark this as closed since it's too much of an edge case to justify building an entire tab to keep track of fines.
