### ISSUE TITLE
[Question] What is this expense

### ISSUE THREAD

**Issue by TheBinaryLoop** [hargata/lubelog#81]
The smallest expense chunk in this pie diagram is called "Expenses by category: 15", I don't have any expense of 15€. What is it? It is also marked as being in November of the current year
![Screenshot_2024-01-13-06-40-35-57_3aea4af51f236e4932235fdada7d1643~2.jpg](https://github.com/hargata/lubelog/assets/13447164/6e681521-ee2f-4192-b763-9a72aa511029)

**Comment by hargata** [comment]
on top of the bar charts are check boxes, if you uncheck them one by one you will know which category of expense it falls under.

**Comment by hargata** [comment]
@TheBinaryLoop Are you using a European locale? I believe I have pinpointed the problem and have released a fix for it. Bug stems from the fact that JS only accepts "." as decimal separator and so if you have European locale e.g.: 38,99 it will treat them as separate numbers.
This is fixed as of the latest docker image.

**Comment by TheBinaryLoop** [comment]
Yes, I have a european locale (German). It fixed it. Now it gets displayed correctly

**Comment by hargata** [comment]
Thank you!
