### ISSUE TITLE
[BUG] Fuel CSV import Failure

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#85]
I am trying to upload a fuel csv.  I have followed the template and even tried to reimport the template after downloading it but it fails.  I had no issue doing a csv upload for any of the other tabs (Service records, repairs, upgrades, taxes).
Here is the error in the log when i try to import the untouched fuel csv example.

fail: CarCareTracker.Controllers.VehicleController[0]
      Error Occurred While Bulk Inserting
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.Decimal.Parse(String s, NumberStyles style)
         at CarCareTracker.Controllers.VehicleController.ImportToVehicleIdFromCsv(Int32 vehicleId, ImportMode mode, String fileName) in /App/Controllers/VehicleController.cs:line 254

**Comment by hargata** [comment]
fixed, you might need to re-pull the docker image.

**Comment by Abateman121** [comment]
works great now.  Thank you!!
