### ISSUE TITLE
[QOL/Feature Request] Reset of page location after Edit

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#87]
Not sure of the best way to describe this so i am including a video.  Basically i uploaded my fuel logs from fuelly using the fuel csv template.  That worked great however i have severy tans marked partial or missed fuel ups.  I am manually adjusting those in Lube Logger but everytime i make an adjustment i am scrolled back to the top of the list and have to rescroll to my location in the list.  Is there anyway to have it stay in the same place of the list after an edit

https://github.com/hargata/lubelog/assets/83042153/6a5d781a-4041-4c41-95d4-d8d1fd5a3552

**Comment by hargata** [comment]
this is done and available on the latest docker image.

**Comment by Abateman121** [comment]
Awesome will update and check it out once I get home tonight
