### ISSUE TITLE
[Feature Request] Scheduled Backup

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#88]
A backup of the DB that runs on a schedule and that can be downloaded and imported

**Comment by helio4k** [comment]
+1

**Comment by Abateman121** [comment]
> +1

I see a fellow assassin is hanging out here

**Comment by joschygit** [comment]
+1

**Comment by psyciknz** [comment]
Or even just some commands that can be run (from external, or before a system backup) to dump a backup file to disk.
Ie if in docker a:
```
docker exec -it lubelog my backup command 
```

To a mounted folder

**Comment by hargata** [comment]
No scheduled backup yet, but as of 1.0.6 there is a function to create and restore backups:
https://youtu.be/r_n9ncgv31E?si=Q8xxWaMnmcJWAPYl&t=293

**Comment by psyciknz** [comment]
Is there a way of calling that rather than doing via giu?  Means it could be scheduled with external command

**Comment by hargata** [comment]
@psyciknz I'm currently working on the API controller for it, when it's released you will be able to hit the API endpoint using cURL and it will return a link to download the db zip file.

**Comment by hargata** [comment]
@psyciknz there is now an api endpoint you can hit with cURL and it will return a download link for the zip file.

it's /api/makebackup
You have to use root user credentials and basic auth to hit it.

**Comment by psyciknz** [comment]
Nice work.  Will have to pull a new version and try it out

**Comment by hargata** [comment]
I'm gonna close this since this feature is now released.

**Comment by GlenNicholls** [comment]
I'm using the docker image and I'd prefer to set a backup schedule and include the file with my backup tool. Having the application create the backup is one less thing I have to worry about if/when there are breaking API changes. 

@hargata No pressure to add a schedule to the app as the API works fine. I'm just curious to hear your thoughts to avoid opening a duplicate issue.

**Comment by psyciknz** [comment]
Personally I'd use deck-chores.   Allows the use of cron In various container.  But it's set up from the compose file for the container. 

Ie your lubelog container definition. Would have a cron and cron command to create the backup and store it somewhere.

It's quite a handy way of doing things and keeps the configuration in the relevant container compose. 

Eg here is a deckchores set up to run a command in a download container I have called ytdl 

labels:
      deck-chores.job-ytdl.command: bash -c "/config/runupdate.sh"
      deck-chores.job-ytdl.cron: "* * * */6 1 0 "

And so this runs a command in the ytdl container at /config/runuodate.sh

Might be a way of doing it.
