### ISSUE TITLE
Feature Request - Engine Hours

### ISSUE THREAD

**Issue by KevinKTM** [hargata/lubelog#91]
An engine hour data field would be very useful - better yet, the ability to add a custom data field(s) to a service record.

**Comment by fftux** [comment]
➕

**Comment by rtrickett337** [comment]
+1 to allow for tracking things like off-road vehicles, quads, dirt bikes, etc that are really more hours based than mileage. Also things like generators and other gas powered equipment.

**Comment by hargata** [comment]
@rtrickett337 @KevinKTM is there a reason why the existing odometer field cannot be used to track engine hours? Or is this request specific to tracking fuel mileage in hours per gallons / liters per 100 hours?

**Comment by rtrickett337** [comment]
I don't plan to track fuel consumption over hours so I think using the odometer field for hours would work for my use case. I'll  add my maintenance items for my equipment I track on hours and let you know if it isn't going to work.

**Comment by hargata** [comment]
@rtrickett337 perfect, thank you!

**Comment by KevinKTM** [comment]
> @rtrickett337 @KevinKTM is there a reason why the existing odometer field cannot be used to track engine hours? Or is this request specific to tracking fuel mileage in hours per gallons / liters per 100 hours?

My dirtbike had an odometer and hour meter. For example, I will track my tire usage by mileage but engine oil gets done by hours. I have been using Autosist but will be moving from that paid platform as they limit the number of vehicles with their bottom tier paid program. One of the features that is nice is you can define custom fields (numeric/text etc) for each vehicle. Does this introduce a new layer of complexity to your database as I'm guessing the schema is no longer constant? Maybe just burn in 5 extra data fields that can be user customized ?

**Comment by rtrickett337** [comment]
I saw there's now an option on the vehicle setup to 'Use Engine Hours' with a toggle on/off. Is that supposed to change like "Odometer" to "Hours" within that vehicle or something? When I turned it on, I didn't see a change...

**Comment by hargata** [comment]
@rtrickett337 hey so currently the only thing that switch does is calculate fuel mileage in hours / gallons. All it does is replace the distance unit with hours. I'm still trying to draft out how to best tackle the engine hours feature and have been looking into custom fields.

**Comment by rtrickett337** [comment]
Ok thanks for clarifying :)

**Comment by hargata** [comment]
@KevinKTM Additional Fields feature now added in 1.1.6
Watch: https://www.youtube.com/watch?v=FIlo9Q6eQBo

**Comment by KevinKTM** [comment]
Awesome!!!!
We are headed out sailing for a few years and I have been looking for a system to manage my boat maintenance (multiple systems from diesel engine, electrical, plumbing, sails... etc) and as well, create my spare parts inventory (and because of limited space, parts are distributed throughout the boat so not always easy to find). The extra data fields will allow me to customize the supplies list to reflect this. I have been searching on my sailing forums for solutions to this and most people are doing old school spreadsheets, some write their own database and some customize grocy...  Cloudflare tunnel in will give access to my lubelog instance running on my boatputer unraid server ... all via Starlink. Thanks again.

**Comment by hargata** [comment]
@KevinKTM I'm glad you find LubeLogger helpful, please help spread the word so that more people can discover it :)

For now, I think we can close this ticket.
