### ISSUE TITLE
[BUG] HTTP 500 error 

### ISSUE THREAD

**Issue by TruncatedFern91** [hargata/lubelog#92]
Was working as expected, until pulled new repo image and redeployed container. 

Attached log file from the container. 

[_lubelogger-app-1_logs.txt](https://github.com/hargata/lubelog/files/13933572/_lubelogger-app-1_logs.txt)

**Comment by hargata** [comment]
ah kk, did you pull the new .env file down? There are fields in there that configures SMTP, I believe to make it work you just have to set IsSSL to true or false if you don't want to set up SMTP

**Comment by TruncatedFern91** [comment]
That did the trick thanks!

**Comment by hargata** [comment]
awesome! I've also updated the .env file so that those values are no longer blank. but I'm gonna pin this issue because I'm sure there will be a lot of people facing this problem when they pull down the latest image.

**Comment by hargata** [comment]
Gonna close this issue since it's been some time since the update was released and the .env file wasn't formatted properly.
