### ISSUE TITLE
[feature request] - Add Maintenance Categories to the Maintenance Record

### ISSUE THREAD

**Issue by wiinc1** [hargata/lubelog#94]
As an owner of a vehicle, I'd like to have the different maintenance categories apart of the service record to:
- categorize costs
- create the ability to send reminders via email or toast messages on login

Example from my spreadsheet: 
![image](https://github.com/hargata/lubelog/assets/8072322/cb37eae9-c20c-429c-9bab-71c9636fd0bd)

BTW - great work on this!  I had the same idea as a simple web app to help get better at coding/dev.

**Comment by rtrickett337** [comment]
+1 along with the ability to sort the service records page by group or simply date as well as the maintenance report that can be generated.

**Comment by hargata** [comment]
@wiinc1 @rtrickett337 just released tags functionality in the latest docker image.
![image](https://github.com/hargata/lubelog/assets/155338622/1a5ef92a-7032-42cd-8355-5c46965c7f83)
![image](https://github.com/hargata/lubelog/assets/155338622/04645491-3b17-4a80-8774-94b2bd04eafd)
![image](https://github.com/hargata/lubelog/assets/155338622/fb47d578-b7b0-4a85-99c6-bd86041293fa)

Currently this functionality only exists in the Service/Repair/Upgrades tab as  well as the Garage page on a vehicular level, but I'll add it to other tabs down the road.

**Comment by rtrickett337** [comment]
So just a heads up, I pulled the image just a few minutes ago and now adding/editing any records no longer works in Safari on Mac (which I've been using this whole time). When I click on the record or the add button, nothing happens. Works fine in Chrome though... I don't know. When I pulled the latest image last night, no issues.

**Comment by hargata** [comment]
@rtrickett337 it's a caching issue. You just need to clear your cache off your web browser.

**Comment by rtrickett337** [comment]
Doh. Yup, that fixed it. Thanks for the quick response!

**Comment by hargata** [comment]
Will be closing this ticket since this feature is technically delivered via the tags functionality as well as the email reminder functionality, see https://docs.lubelogger.com/Records/Reminders#reminder-emails
