### ISSUE TITLE
[feature request] - maintenance categories & repair threshold

### ISSUE THREAD

**Issue by wiinc1** [hargata/lubelog#95]
As a car owner, I would like to be able to be reminded when a specific type of maintenance is needed on the car so that I avoid car breakdowns.

Below is an example of the pivot table I did and some vlookups to help identify the current repair status

![image](https://github.com/hargata/lubelog/assets/8072322/cd91a9b9-a4f5-45f1-a3af-7004759c9439)

**Comment by Vyerni** [comment]
This would be an awesome feature

**Comment by hargata** [comment]
@wiinc1 could this be potentially covered by the recurring reminder feature? You can set the odometer reading and it will let you know when it becomes past due, and once you've performed that service it will automatically push it back by the set mileage interval
