### ISSUE TITLE
[BUG] AuthN Corrupted Credentials

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#96]
So i was trying to set up the smtp and am having tons of issues with that.  However i noticed this in the log files when i setup the admin account and then login with the admin account.  I can still log in no problem just not sure if this is an issue or not since is it is telling me AuthN forbidden and Corrupted Credentials.

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /App
info: CarCareTracker.Middleware.Authen[13]
      AuthenticationScheme: AuthN was forbidden.
info: CarCareTracker.Middleware.Authen[13]
      AuthenticationScheme: AuthN was forbidden.
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Corrupted credentials
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Corrupted credentials
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Corrupted credentials

**Comment by hargata** [comment]
Not an issue as long as you can still login. the auth middleware tries to auth for both API via headers and Cookie for regular users, it logs an error when one of those auth methods aren't available but is a non-issue as long as you can still log in.

Also for the SMTP stuff, I've tested it with Gmail SMTP server and it worked fine but I haven't had any chance to test it with other SMTP servers.

**Comment by Abateman121** [comment]
i am doing gmail but just cannot get it to work.  Even created a new app password

**Comment by hargata** [comment]
interesting.
here are the params I used for mine.
Note that the Username and the EmailFrom needs to be the same, I think this is a Gmail specific restriction.
![image](https://github.com/hargata/lubelog/assets/155338622/feb8969a-3cf8-4857-b49d-6e286be7d0c4)

The password is the app password generated

**Comment by Abateman121** [comment]
yea thats what mine looks like.  I just deleted and recreated a new .env file and that seemed to do the trick.

**Comment by hargata** [comment]
hmmm weird, but sometimes it's just a matter of turning it off and on again. Good to close this?
