### ISSUE TITLE
[Feature Request/QOL] Freeze Column Headers when scrolling

### ISSUE THREAD

**Issue by Abateman121** [hargata/lubelog#97]
As it says is there a way to freeze the column headers on the tabs like fuel, kind like excel does so they are always visible even when you are scrolling down several hundred rows.

https://github.com/hargata/lubelog/assets/83042153/5f897892-e8b8-47d9-ae52-762bedaa1bf9

**Comment by hargata** [comment]
Added, released.

**Comment by Abateman121** [comment]
Works great thank you for the fix
